#!/usr/bin/env python3
# Lemmings 2: The Tribes In-Game Level Editor V1.0
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Assemble the WHDLoad slave and the editor and embed them, with the
install's Workbench icon, in patch.py.

Usage: python3 build.py [--vasm PATH]

Requires the vasm 68000 assembler with Motorola syntax (vasmm68k_mot).
Only the section of patch.py between the "GENERATED BY build.py" markers is
written again, so users of patch.py need only Python 3.

The slave (src/whdload/slave.s) is assembled with the length and CRC16 of
the supported main program, which it checks before it starts the game; its
gate_value stays zero here, and patch.py fills it in from the user's own
main program. The editor (src/editor/editor.s) is a relocatable hunk
executable that the slave loads as data/Editor.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import re
import struct
import subprocess
import tempfile
import textwrap

ROOT = Path(__file__).resolve().parent
PATCH = ROOT / 'patch.py'
VERSION = '1.0'
BEGIN = '# BEGIN GENERATED BY build.py - do not edit by hand\n'
END = '# END GENERATED BY build.py\n'

MAIN_SIZE, MAIN_CRC = 394024, 0xD721    # the supported main program, unpacked
EDITOR_MAX = 0x40000                    # the slave's room for the editor in ExpMem
GATE_SLOT = 0x34                        # gate_value in the slave, as in patch.py

# The install's project icon: a Workbench 1.3-style icon of two planes in
# the standard Workbench palette ('.' colour 0, 'k' 1 black, 'w' 2 white,
# 'b' 3 blue), whose default tool is WHDLoad.
ICON_PICTURE = '''\
..........kk.k.kk.........
.........kkkkkkkkk........
........kkkkkkkkkkk.......
.......kkkwwwwwwwkkk......
.......kkwwkwwwkwwkk......
........kwwwwwwwwwk.......
.........wwwwwwwww........
..........wwwwwww.........
.......bbbbbbbbbbbbb......
......bbbbbbbbbbbbbbb.....
.....wwbbbbbbbbbbbbbww....
.....ww.bbbbbbbbbbb.ww....
........bbbbbbbbbbb.......
........bbbbbbbbbbb.......
.........bbbb.bbbb........
.........bbbb.bbbb........
........wwwww.wwwww.......
.......wwwwww.wwwwww......'''
# PRELOAD keeps the game's files in memory; NOWRITECACHE makes WHDLoad
# write a saved, renamed or deleted level to the disk at once.
TOOLTYPES = ['PRELOAD', 'NOWRITECACHE']
NO_POSITION = 0x80000000


def project_icon(slave: str) -> bytes:
    """A Workbench project icon that starts WHDLoad with the slave."""
    rows = ICON_PICTURE.splitlines()
    width, height = len(rows[0]), len(rows)
    words = (width + 15) // 16
    planes = []
    for plane in (1, 2):
        data = bytearray()
        for row in rows:
            bits = 0
            for x in range(words * 16):
                colour = '.kwb'.index(row[x]) if x < width else 0
                bits = bits << 1 | (colour & plane != 0)
            data += bits.to_bytes(words * 2, 'big')
        planes.append(bytes(data))

    def string(text: str) -> bytes:
        data = text.encode('ascii') + b'\0'
        return struct.pack('>I', len(data)) + data

    disk_object = struct.pack(
        '>HH' 'IhhhhHHH' 'IIIIIHI' 'BB' 'IIIIIII',
        0xE310, 1,                                  # magic, version
        0, 0, 0, width, height + 1, 4, 3, 1,        # gadget: size, image, boolean
        1, 0, 0, 0, 0, 0, 0,                        # gadget render image only
        4, 0,                                       # WBPROJECT
        1, 1, NO_POSITION, NO_POSITION, 0, 0, 10240)
    image = struct.pack('>hhhhhIBBI', 0, 0, width, height, 2, 1, 3, 0, 0)
    tooltypes = [f'SLAVE={slave}'] + TOOLTYPES
    return (disk_object + image + b''.join(planes) + string('WHDLoad')
            + struct.pack('>I', (len(tooltypes) + 1) * 4)
            + b''.join(string(t) for t in tooltypes))


def assemble(vasm: str, source: Path, output: Path, options: list[str]) -> bytes:
    subprocess.run([vasm, '-quiet', '-Fhunkexe', '-nosym', *options,
                    '-I', str(ROOT / 'src/whdload'), '-I', str(source.parent),
                    '-o', str(output), str(source)], check=True)
    return output.read_bytes()


def check_version() -> None:
    text = (ROOT / 'src/whdload/version.i').read_text()
    found = re.search(r'dc\.b "V([0-9.]+)"', text)
    if not found or found[1] != VERSION:
        raise SystemExit('src/whdload/version.i does not hold V' + VERSION)
    for path in sorted(ROOT.glob('src/**/*.[si]')) + [ROOT / 'patch.py', ROOT / 'build.py']:
        if f'Level Editor V{VERSION}' not in path.read_text().splitlines()[1 if path.suffix == '.py' else 0]:
            raise SystemExit(f'{path.relative_to(ROOT)}: its header does not name V{VERSION}')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--vasm', default='vasmm68k_mot', help='the vasm executable')
    args = parser.parse_args()
    check_version()
    with tempfile.TemporaryDirectory() as temp:
        slave = assemble(args.vasm, ROOT / 'src/whdload/slave.s', Path(temp) / 'slave',
                         ['-no-opt', f'-DEXE_SIZE={MAIN_SIZE}', f'-DEXE_CRC=${MAIN_CRC:04x}'])
        # -kick1hunks: plain HUNK_RELOC32, which resload_Relocate handles.
        editor = assemble(args.vasm, ROOT / 'src/editor/editor.s', Path(temp) / 'editor',
                          ['-kick1hunks', '-m68000'])
    words = struct.unpack(f'>{len(slave) // 4}I', slave[:len(slave) // 4 * 4])
    if words[:5] != (0x3F3, 0, 1, 0, 0) or 0x3EC in words:
        raise SystemExit('the slave must be one hunk without relocations')
    if slave[32 + GATE_SLOT:32 + GATE_SLOT + 4] != bytes(4):
        raise SystemExit('the slave\'s gate_value is not where patch.py expects it')
    header = struct.unpack_from('>5I', editor)
    sizes = struct.unpack_from(f'>{header[2]}I', editor, 20)
    if header[:2] != (0x3F3, 0) or sum((s & 0x3FFFFFFF) * 4 + 8 for s in sizes) > EDITOR_MAX:
        raise SystemExit('the editor is not a hunk executable that fits the slave\'s room')
    blobs = {'Lemmings2.slave': slave, 'Editor': editor,
             'Lemmings2.info': project_icon('Lemmings2.slave')}

    lines = [BEGIN, 'BLOB_SHA256 = {\n']
    for name, data in blobs.items():
        lines.append(f"    '{name}': '{hashlib.sha256(data).hexdigest()}',\n")
    lines.append('}\nBLOBS = {\n')
    for name, data in blobs.items():
        text = base64.b64encode(data).decode('ascii')
        lines.append(f"    '{name}': (\n")
        lines += [f"        '{part}'\n" for part in textwrap.wrap(text, 72)]
        lines.append('    ),\n')
    lines += ['}\n', END]
    source = PATCH.read_text()
    start, end = source.index(BEGIN), source.index(END) + len(END)
    PATCH.write_text(source[:start] + ''.join(lines) + source[end:])
    for name, data in blobs.items():
        print(f'{name}: {len(data)} bytes, SHA-256 {hashlib.sha256(data).hexdigest()}')


if __name__ == '__main__':
    main()
