#!/usr/bin/env python3
# Lemmings 2: The Tribes In-Game Level Editor V1.1
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Make the WHDLoad install of Lemmings 2: The Tribes with the in-game level
editor from your own copy of the game.

Usage: python3 patch.py DISK1 DISK2 DISK3 [--out DIR]

DISK1, DISK2 and DISK3 are your images of the game's three disks, IPF or
ADF files, in any order. Each must have one of the SHA-256 hashes listed in
IMAGES (and in README.md); other versions of the game are refused. Every
input is checked before anything is written, and the inputs are only read.
The install is written to DIR (default: Lemmings2):

  Lemmings2.slave   the WHDLoad slave
  Lemmings2.info    its Workbench icon (tool types PRELOAD NOWRITECACHE)
  data/             the game's files from your disks with the main program
                    unpacked, the editor (Editor) and the editor's tile
                    flags (EditorTiles), worked out from the game's levels
  Levels/           your levels (.lvl files)

Run again over an existing install, it writes the program files again and
keeps your levels and your saved positions. Needs only Python 3.8 or later.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import struct
import sys

VERSION = '1.1'
SLAVE, ICON = 'Lemmings2.slave', 'Lemmings2.info'

# The supported disk images: SHA-256 -> (disk, format). The ADF images hold
# the standard AmigaDOS tracks of the IPF images; disk 3's protection track
# cannot be held in an ADF, and its blocks are zeros there.
IMAGES = {
    '24a005cca5ba97da00bd44233863b817f90b6a08906c65dba2fd1bcd20045509': (1, 'IPF'),
    '05b800affc4bcb5044f41606bc807d7efc5f0669b82abb1b9573f38631257965': (2, 'IPF'),
    'e5cff8776a8a09a8fb1d1b7f23767ccab5c2acc6f06b10ee0f13f54dd57f5ce5': (3, 'IPF'),
    'd1b71a2a0d5797c3c185f4d939b9ad2416921a8370ee082f2bc9df0ee73ac181': (1, 'ADF'),
    'fcbc1b870ae30bc5f79a58ee8bef81e1e7743472240de8896f21d9508abdff91': (2, 'ADF'),
    '5219ae0d109ef94ce1eb84212024b83e929def0d2e8ea68fc5c0c4abd4589fb3': (3, 'ADF'),
}

# The game's files the install needs, as they are on the disks: (disk,
# name, size, SHA-256). They go into data/ under the same names.
FILES = [
    (1, 'L2-Saved-Positions', 5022,
     'dc30b90ae8995e6b067f62b60eecff5ee470c85d256284bd377a28a4367456bf'),
    (1, 'endseq.dat', 131186,
     '2cfbfd5071837590f4112b03fbb8a7ba1fbd50a8ae582409c9c572965babd786'),
    (1, 'endtune', 34744,
     'ad7a134f3debd59eae56f244e6c563dfd85668134034882965f980194e5dd851'),
    (2, 'Maintune', 120678,
     '29cc402c8343a6ab4b44edcd4177b12a9ebe46e72d4d1c4835b6be7dbc82a6da'),
    (2, 'alemms.comp', 53204,
     '89af4a2ed258b786eb0931ffe1dd61d40906ce0c8be1e83d5faf646e497cc707'),
    (2, 'logo.dat', 52931,
     'ffb18397580a084377335d106754a10b15a99c3cd2241d455f06b0ca310d9c6c'),
    (2, 'soundfx/L2ExtendedFX', 251115,
     '87fb153c67812289b5754ead2dd2ece06324f08d89e15306c298784c8d4b92d8'),
    (2, 'soundfx/l2basicfx', 52891,
     '0055a6f5c7def2ca407d4b21e84e4a0225f7c8da43f550b25dfdfc7263576faa'),
    (3, 'beach/astyle.dat', 21978,
     '1d7b38950527c392574d255a3ec79a1220e2183462098064a140c85a6282e4bf'),
    (3, 'beach/tribe.dat', 2786,
     '2160335da3949d971e1483e1c5a102f7555b46511f7a5617978a31a7bb4afd45'),
    (3, 'beach/tune', 29638,
     '4a142af542045f800db3303c14a94dd9b245c010ffa3deb4312d13efb121e339'),
    (3, 'cavelem/astyle.dat', 32393,
     'a6a05f3b879f7c8bc2d05ac8c9a6588bd0e092f358439b3f5a941cfbe81c57b6'),
    (3, 'cavelem/tribe.dat', 2953,
     '1357213fddbfbf33ff5d292febe7c0eac62aa1e9f97ce5c06eee8e3d4dd116b0'),
    (3, 'cavelem/tune', 19894,
     'b83aeff0c188a6b33ffa04b45dc2bf884d6c7e4ddaad3bd14feadc4b5b01b4e1'),
    (3, 'circus/astyle.dat', 16680,
     'f6292ff76d824e33788d36c9c7de3229439572d235821878e2591127c2f816ba'),
    (3, 'circus/tribe.dat', 3040,
     '2643471f0f9a4bc174e051676477797aefb6a6b2834ec9254268ae0eeac5c04d'),
    (3, 'circus/tune', 21819,
     'bc577a661b73c7e4735816c41318543fc300cce73cd32f7c767fdd55cd975c7b'),
    (3, 'classic/astyle.dat', 16309,
     'e5c05d0936a870532e66c49f5362cf6fe4e777f09f851fee1b7db1c7825ed3e5'),
    (3, 'classic/tribe.dat', 3068,
     '6a29a8d991791c712c716ed78c0da6bab0baab77038e38485e0eed93d098b921'),
    (3, 'classic/tune', 36080,
     '6d74dc245f5b53547fcb0a8a985898a16ef0cb29101f4493864bf2559f26d31f'),
    (3, 'egyptian/astyle.dat', 19637,
     '6cb6e5d779d9e170105989e246867cd7c2fbe4c069db4f9a278663735ca861cf'),
    (3, 'egyptian/tribe.dat', 3124,
     '591afb60be7ec9e7e8fa8784f1734c1889ffd2d52fe62fce1cc38a9919579dc7'),
    (3, 'egyptian/tune', 28763,
     '5f0bbdc773eb8ebf159aa882fc49a63786a8778e5405c91254ec4da86c8b9985'),
    (3, 'graphics/TalBack.dat', 3745,
     '611c9c2974a32b44ed526fa066580a05201b7a8005241dd91c5b288929c0ddbd'),
    (3, 'graphics/talisman.dat', 15515,
     'cfe5048786ec6253de4fd069854991c9ec33f744f1ec8f4f02297559c779f2ab'),
    (3, 'graphics/worldmap.dat', 26217,
     '91c34bf4a16c513300ab7f6ad6c7a90aeb2a7e0696e22d04c877d789ba5c4a16'),
    (3, 'graphics/worldsprites.dat', 11451,
     '4dc8e064052215d8e411a5c3f7152bade2803541861b4c1dd397e3af764719af'),
    (3, 'highland/astyle.dat', 24145,
     'de4763baa22532c0a7fd5c842128dd53c816ccb4fb5b7f5a1a742ebf4f92e09d'),
    (3, 'highland/tribe.dat', 2707,
     '49d3d97f696cf0156dc0ce7b97b259c8a41432f256db7bb3ac70eb7e586e1584'),
    (3, 'highland/tune', 23903,
     'a07d10add2914c289356ff95456984849c8aa3f3c6db154499440672442ddc60'),
    (3, 'l2extendedfx2', 61487,
     'a58185b350d720e2ff31641cf3f8c5a34f4111fe7b141b926420350b303130a9'),
    (3, 'medieval/astyle.dat', 34903,
     'b0928ede3361d79a117da184cc0094995050147b4fc1d3ebf92b5a295c709ef1'),
    (3, 'medieval/tribe.dat', 2862,
     '7dec91ceddaf75ffa4a603513abde3ded65123bec184c1c56ca93cadb6c11923'),
    (3, 'medieval/tune', 31549,
     'f8e910b989197d3ee80d1d534380e54f4a03d7fc5ce85bf4cdf1e8c134778be6'),
    (3, 'outdoor/astyle.dat', 26310,
     'e264fc5577653d08e62ba2a8a5a5b263ce252d2b0d47c9ff2d37a78850253345'),
    (3, 'outdoor/tribe.dat', 3101,
     '54970493f99004f618587da99d0ab3e89874cc5a7a59f84bb9e90ff360310644'),
    (3, 'outdoor/tune', 23028,
     'c9f2e964b6f8c08711d5c1a801f0767fdbf9cb5d51f32f4168249fb909059a44'),
    (3, 'polar/astyle.dat', 23425,
     '7c3f45b719756ecef13a099c98508aac96cc2155f5178dc9c84c12435d1635df'),
    (3, 'polar/tribe.dat', 2324,
     'f28a164c23dd4bd88edbe03e441c089e4a8bd292d0c27b92bfcd91c9c65fb83b'),
    (3, 'polar/tune', 31990,
     'cea04159fae7b03d2a7328e58f41072c025d2544eed2dc4e45891234b2b58bec'),
    (3, 'shadow/astyle.dat', 17474,
     'cfbc24fb266b98775630b228eabd390ddb7e29be33239d206d065a20361388f4'),
    (3, 'shadow/tribe.dat', 2916,
     '7831b3f194945f2215a181929ac4de0d81175fc87f6a27327eb71b018ec95d13'),
    (3, 'shadow/tune', 25093,
     '6de96abab09b367d3bafde4759f5875778b6708c98139f646dc66c92164f7ba7'),
    (3, 'space/astyle.dat', 29025,
     '57cb6e2f44fe3379c01e3fa8a58acd1f5ed987697982e3cdceea62fc48180281'),
    (3, 'space/tribe.dat', 3097,
     'e790ef11dfefc7a6825e2cb7c697cbb7fa9655401dcf0582c3bf47b2658d2bb2'),
    (3, 'space/tune', 29724,
     'e0c383153dff1010f1e103e7229c296542a596681ec419d0af210dd361148b21'),
    (3, 'sports/astyle.dat', 22442,
     'ca4fe98d0fa3cecdd9e2b4415f8458905e6ee055862cb99d59db2170e633c18a'),
    (3, 'sports/tribe.dat', 3079,
     'd238319f9f310499fee731ae6555b0f0e19c0962901087a039b65a9ff54c55b7'),
    (3, 'sports/tune', 30113,
     'c57baf518bb40268b0bcb5c272390f14ff152d5bcf6cea12f6f878288b6aa055'),
]
SAVED_POSITIONS = 'L2-Saved-Positions'      # the player's own after the first save

# The main program, on disk 2, packed with RNC method 1: installed unpacked.
MAIN = 'Lemmings2'
MAIN_PACKED = (263294, 'f098749778dbede40e478f4784f752a7faba1f399d0f6dd67aaeff04476750c9')
MAIN_UNPACKED = (394024, '8d49aec4874845fdaf458a205d9d451c0f31546c575763cd79e56b279738627a')

# The game's own levels: RNC streams in the main program's hunk 0, each a
# bank of level records: (offset in hunk 0, unpacked size, SHA-256).
LEVEL_BANKS = [
    (0x1c66a, 86480, '653fb3560d94a41d6b34c26172eed4634fd3860a24e0e10a572fddc83fa7d08a'),
    (0x1ddac, 86480, '9bf1353258f0e4d70ee7d791a9a36b3df5ed756f16ca9fb020fc12d442b79a46'),
    (0x1fe6a, 86480, '1b61e6ba55e6d82b755a3e612d8a63d0fe4ff62a0b13a1daa87be961b59ef887'),
    (0x22298, 86480, '3edb7c1cc8d54f479e16bf9a6477d5d4d4d39b7ec8f6b073a5517db6db2cd9eb'),
    (0x24386, 86480, '5278b6fb63bc5e3c212ec05eaa02eddfcfe91b8e95ba7ab7c249656363043987'),
    (0x26c0e, 86480, 'f5101a89a833d6e218c6b0e8f9f6bd838fc19700e261cff517ed8406f84ccbd9'),
    (0x289c2, 86480, 'fdad7688e4d70a88801aa995df9cc86a60c290e256f92c1a1b25b68a8697476a'),
    (0x2b12a, 86480, '67f583215dd90d7340373012f3b628b77750f8d31f6b9cf7bd580e19127d9294'),
    (0x2d4ae, 86480, '603ef072a1aa219b03ec1ed6e9e5515dd56771522a35c8c542a7c0c57166d439'),
    (0x2ff80, 86480, '5aefc08fc9ceb4d13178f9e8effdb4aa7091b63f56e5be0023b9594467f683ac'),
    (0x31ebe, 86480, '0c532a4c28ea9c953fc721986b43087f1d5263c3e462525bdf3aef2385e56961'),
    (0x348c2, 86480, '028697cee6b58cc4a63c45e23e302f14f2be32bc0508fe6dbfc7f25b3d5df415'),
    (0x36c54, 34592, '5497c78245703f71f2f8b709968453a768932fffd918a631a9e0cfd89db1f795'),
]
RECORD_SIZE = 0x21C8                    # a level record (FORM L2LV)
RECORD_STYLE, RECORD_CELLS = 0x66, 0x74 # its style (LE16) and map (BE32 cells)
MAP_CELLS = 1971
STYLES, TILES = 12, 1024                # data/EditorTiles: a byte per style and tile
CELL_TILE, CELL_STEEL, CELL_DECOR = 0x3FF, 1 << 28, 1 << 30

# The game's disk-3 check (hunk 0 $1B6E) compares the long word at $B4 with
# the one in its own code: move.l ($b4).w,d7 / cmp.l #...,d7 at $1B76. The
# slave puts that long word at $B4; it is copied from your main program into
# the slave's gate_value, GATE_SLOT bytes into its code (src/whdload/slave.s).
GATE_CODE, GATE_OPCODES = 0x1B76, bytes.fromhex('2e3800b4bebc')
GATE_SLOT = 0x34

# BEGIN GENERATED BY build.py - do not edit by hand
BLOB_SHA256 = {
    'Lemmings2.slave': '96ffae123a0077ef3484acc30ed75502ece4b3b5b6d747160609b265d0af7175',
    'Editor': '4ab46c7a10054897d3716a1f278a425e1cc34a83f72c8c50a59e825e5a535cfa',
    'Lemmings2.info': '47756be30c5375b632acba1b570bee8dbff009ddfb6b0670daf9b1c41af53b60',
}
BLOBS = {
    'Lemmings2.slave': (
        'AAAD8wAAAAAAAAABAAAAAAAAAAAAAAEkAAAD6QAAASRw/051V0hETE9BRFMAERAGAA8AAAAA'
        'AAACHgAAAAAAWQAMAAAAOABPAGsAAAAAAAAAAAAAAAAAAExlbW1pbmdzIDI6IFRoZSBUcmli'
        'ZXMAMTk5MyBETUEgRGVzaWduIC8gUHN5Z25vc2lzAExldmVsIEVkaXRvciBWMS4xCmJ5IFRp'
        'bW8gSGVpbW9uZW4KaHR0cHM6Ly9naXRodWIuY29tL3RpbW9oZWltb25lbi9hbWlnYS1sZW1t'
        'aW5nczItZWRpdG9yLXBhdGNoAGRhdGEvTGVtbWluZ3MyAGRhdGEvRWRpdG9yAFVuc3VwcG9y'
        'dGVkIGRpc2sgb3BlcmF0aW9uAFRoaXMgaW5zdGFsbCBuZWVkcyBmYXN0IG1lbW9yeQBUaGUg'
        'aW5zdGFsbCB0b29sIGhhcyBub3QgY29tcGxldGVkIHRoaXMgc2xhdmUAZGF0YS9FZGl0b3Ig'
        'aXMgdG9vIGxhcmdlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOYAAAAJAAZGF0YS8AAAAAAAAA'
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
        'AAAAAAABF5ZKuAAEAAEbmEjn//4AAA4uG0ACsAAADjIT/AAAAAAONgC/7AEAAOVQO3wAAgAA'
        '5VQBmkItAAFqZEq4AAQAAWpoZgAA6AABa7RhAAHq/////0P6/0giiCRIIDr9+LC8ACAAAGQO'
        'SHr+zUh5AAAAK2AAAkogOv3yZg5Iev7YSHkAAAArYAACNkH6/nUiev3GTqoACLC8AAYDKGYA'
        'AWggev20TqoAMLB81yFmAAFYIHr9pEKnSHn/////LzyIEAADSHkAAAAILzyIEAACSHkAACAA'
        'LzyIEAAAIk9OqgBQT+8AHCB6/XBYiEP6/rZwA0foAAQiyyIQ5YkgQVHI//Kw/AAAZgABACZ6'
        '/phB+v7yIBhrDCIYsrMIAGYAAOpg8CJL0/wAAReWMvxO+UH6APgiiCJL0/wAARuYMvxO+UH6'
        'APYiiEPrDi4y/E65QfoBViLIIvxOcU5xMrxOcSJL0/wAAOVSMrwAMSJL0/wAAWpkMvxO+UH6'
        'AJoiyDK8TnEiS9P8AAFrtCK8TnFOcUH6/YIoevzE2fwACAAAIkxOqgAIIExCp0h5AAAACC88'
        'iBAAAiJPTqoAUE/vAAywvAAEAABjDkh6/cBIeQAAACtgAADwQfr9zE6USoBnDC8ASHkAAAAr'
        'YAAA2iR6/bZOqgAgQrgABCH6/HYAtHAAcgAkPAAIIACRyE7TSHkAAAAJYAAAsC86/ZAGlwAB'
        'auovOv2GBpcAAWciTnUbfAAwAeNCrQKCUe0B6k51SOd//gwoADoAA2YCWIhF+v15dD4U2FfK'
        '//xCEkH6/WYkev1GSgBnDgwAAAFmMiABTqoADGAWJkgoSU6qACRKgGcSIEsiTE6qAAgugEzf'
        'f/5wAE51TN9//iA8AAAAzU51SHr8hEh5AAAAK2AAABwbQAKwE/wAAAC/7AGwOvujZwJOdUh5'
        '/////y86/N5Yl051AAAD8g=='
    ),
    'Editor': (
        'AAAD8wAAAAAAAAACAAAAAAAAAAEAACKPAADEMQAAA+kAACKPYAABlkwyRUQAAnveAALK9AAA'
        'ASQAAG8kAABypAACxvQAAob0AADY5Eq4AAQAANjoZgAANAAA2uhKuAAEAADa7GcA/noAABnU'
        'YQAAEgAAGdg7QAEkAAADNkotAecAAAM6ZgD9RAAAC9ggLQJeAAAL3LC8AAAAAAuusDwACQAA'
        'C7JnAAECAACa1kotAd4AAJraZgBKrAAAAepKLQHmAAAB7mcAAD4AAPfqBgUICAAA81ZI5+D+'
        'AAFhckJtAU4AAWF2Q+0BoAABZERhAKZ2AAFkSAZAACAAAWNYUkAvAAABY1xD7QGgAAFj+NBB'
        'UkAAAPhKYQACjAAA+NgvADIAAAD5jEjnAPAAAPoUSi0B2wAAE5ZCLQHEAAABRmEAEloAAAFK'
        'YQAiSAAAFOxwAAZCAAAU8AAs4Ur/////AAFhnE65AAATigABYbYgeQABwQQAAWR4QfkAAWSG'
        'AAFj/EH5AAHBDP////8AAAEAAJD0wgAAAcT////+/////wAPALUADgANASYAkwAOABoAKAC1'
        'AAYAJwAtALUADgAsSOd/fkP5AAJ6tnAGIthRyP/8DLkAAB3AAAJ6zmUABk4meQACerpB+v5k'
        'IBhrDCIYsrMIAGYABj5g8CZ5AAJ6vkH6/4ogGGsMIhiyswgAZgAGJGDwJnkAAnq6Qfr/RCAY'
        'axgyGLJzCABmAAYKIhjSi7KzCAJmAAX+YOQgOQACesLQvAAERsAgS9H8AAHAvLCQZgAF4iPA'
        'AAJ7YiA5AAJ6wtC8AAD0ACBL0fwAAcDQsJBmAAXCI8AAAmoaIDkAAnq60LwAAAYCI8AAAnrS'
        'IDkAAnq60LwAAWXcI8AAAnrWIDkAAnq60LwAABcSI8AAAnraIDkAAnq60LwAABUOI8AAAnre'
        'IDkAAnq60LwAABUaI8AAAnriIDkAAnq60LwAABjOI8AAAnrmIDkAAnq60LwAABmuI8AAAnrq'
        'IDkAAnq60LwAABnoI8AAAnruIDkAAnq60LwAABtuI8AAAnryIDkAAnq60LwAAA/II8AAAnr2'
        'IDkAAnq60LwAAOXYI8AAAnr6IDkAAnq60LwAAOJyI8AAAnr+IDkAAnq60LwAAOKGI8AAAnsC'
        'IDkAAnq60LwAAOKqI8AAAnsGIDkAAnq60LwAAPNWI8AAAnsKIDkAAnq60LwAAQq8I8AAAnsO'
        'IDkAAnq60LwAAACAI8AAAnsSIDkAAnq60LwAAACyI8AAAnsWIDkAAnq60LwAAAM+I8AAAnsa'
        'IDkAAnq60LwAAAviI8AAAnseIDkAAnq60LwAAAu2I8AAAnsiIDkAAnq60LwAAAy2I8AAAnsm'
        'IDkAAnq60LwAAJreI8AAAnsqIDkAAnq60LwAAAHyI8AAAnsuIDkAAnq60LwAAAIuI8AAAnsy'
        'IDkAAnq60LwAAPfqI8AAAns2IDkAAnq60LwAANkeI8AAAns6IDkAAnq60LwAANpoI8AAAns+'
        'IDkAAnq60LwAAY0WI8AAAntCIDkAAnq60LwAAcPkI8AAAntGIDkAAnq+0LwAAAkEI8AAAntK'
        'IDkAAnq+0LwAAAoEI8AAAntOIDkAAnq+0LwAAAIgI8AAAntSIDkAAnq+0LwAAASkI8AAAntW'
        'IDkAAnq+0LwAAEwsI8AAAntaIDkAAnq+0LwAAEyII8AAAnteIDkAAnq60LwAABOiI8AAAntm'
        'IDkAAnq60LwAACOUI8AAAntqIDkAAnq60LwAAB8QI8AAAntuIDkAAnq60LwAAAP4I8AAAnty'
        'IDkAAnq60LwAAMpiI8AAAnt2IDkAAnq60LwAACGkI8AAAnt6IDkAAnq60LwAAAmiI8AAAnt+'
        'IDkAAnq60LwAAA9UI8AAAnuCIDkAAnq60LwAABeYI8AAAnuGIDkAAnq60LwAABKcI8AAAnuK'
        'IDkAAnq60LwAABOKI8AAAnuOIDkAAnq60LwAATwQI8AAAnuSIDkAAnq60LwAATvqI8AAAnuW'
        'IDkAAnq60LwAAA+II8AAAnuaIDkAAnq60LwAAAFOI8AAAnueIDkAAnq60LwAAcZiI8AAAnui'
        'IDkAAnq+0LwAAAg4I8AAAnumIDkAAnq+0LwAAEScI8AAAnuqIDkAAnq60LwAAMZ8I8AAAnu2'
        'IDkAAnq60LwAAMWEI8AAAnu6IDkAAnq60LwAANI6I8AAAnu+IDkAAnq60LwAAb20I8AAAnvC'
        'IDkAAnq60LwAAWFyI8AAAnvGIDkAAnq60LwAAPhKI8AAAnvKIDkAAnq60LwAAPjYI8AAAnvO'
        'IDkAAnq60LwAAPmMI8AAAnvSIDkAAnq60LwAAPoUI8AAAnvWIDkAAnq60LwAABOWI8AAAnva'
        'M/wAAQACfBIz/AADAAJ8FCA5AAJ6ytC8AAAAACPAAAJ7riA5AAJ6ytC8AAABACPAAAJ7smEA'
        'ARAieQACerrT/AAA2OQy/E75IvwAAAg+MrxOcSJ5AAJ6utP8AADa6DL8Tvki/AAACFIyvE5x'
        'InkAAnq6Q+kZ1DL8Trki/AAACNoyvE5xInkAAnq6Q+kDNjL8Tvki/AAACRQyvE5xInkAAnq6'
        'Q+kL2DL8Tvki/AAAfzgyvE5xInkAAnq6Q+kLrjL8Tvki/AAACPYyvE5xInkAAnq60/wAAJrW'
        'MvxO+SL8AAAJiDK8TnEieQACerpD6QHqMvxO+SL8AAAJaDK8TnEieQACerpD6QFGMvxO+SL8'
        'AAAqDjK8TnEieQACerpD6RTsMvxO+SL8AAAg1DK8TnFwAGAOQfoYjyAIYAZB+hhgIAhM337+'
        'TnUkeQACerZB+hijTqoAJLC8AAAwAGYOQfoYk0P5AAAjLE6qAAhOdUjn//hhABM0TN8f/y85'
        'AAJ7Ok51KHkAAnrWTpRhABGoYQARvCB5AAJ7SiJ5AAJ7Uih5AAJ6+k6UYQABJFD5AAJ74GEA'
        'BJJKQGcssHwAAmcGYQABjmAEYQAg+EpAZuRKOQACe+BnCFH5AAJ74FiPLzkAAnsWTnVhAAEU'
        'YQARQEo5AAJ74GcOUfkAAnvgLzkAAns+TnUvOQACexJOdUo5AAJ73mYMSHoADC85AAJ67k51'
        'cDw7QAEkTnWwPAAJZhBKOQACe95mCC85AAJ7Jk51LzkAAnsiTnVKLQHnZwgvOQACexJOdUo5'
        'AAJ73mYILzkAAnsaTnVhABDGYQAKwko5AAJ8VGYAdcxKQGcOsHwAAmYA/zJhACA8YARhAADG'
        'SkBmAP8iLzkAAnsWTnVKLQHmZwpKbQGUZgxR7QHmLzkAAnsyTnUvOQACey5OdUptAZRnDEot'
        'Ad5mBi85AAJ7Kk51SjkAAnvfZiQz7QFMAAJ76DPtASAAAnvqIHkAAnrGQ/kAAu78YVBQ+QAC'
        'e99OdUo5AAJ732c+QfkAAu78InkAAnrGYTI7eQACe+oBIDA5AAJ76LBtAUxnEDtAAUxhABAK'
        'KHkAAnrmTpRR+QACe95R+QACe99OdTA8CHEi2FHI//xOdWEaSkBrFEH5AALNNGEAXiZR+QAC'
        'e+xhfHAATnVhAA/IMDkAAnvka2RhAAaGSioAPGdaYQAHfiR5AAJ6tkH5AAJ8dE6qACSwvAAA'
        'IchmPkH5AAJ8dEP5AALNNE6qAAhB+QAC7HRhAAJMZiJB+QACzTRhdEpAaxYyOQACzZzgWUH5'
        'AALsfGEAAYxmAk51YQAPTnD/TnUzwAACfGgoeQACevJOlEH5AALNNCJ5AAJ6xmEA/0QwOQAC'
        'fGiwbQFMZww7QAFMKHkAAnrmTpRQ+QACe94wLQEgKHkAAnrqTpQoeQACeuJOlE51DJBGT1JN'
        'ZnoMqAAAIcAABGZwDKhMMkxWAAhmZgyoTDJMSAAMZlwMqAAAAEoAEGZSDKhMMk1IAF5mSAyo'
        'AAAABgBiZj4MqEwyTVAAbGY0DKgAAB7MAHBmKnIAEigAaeFJEigAaLJ8AAdkGHAAECgAZ+FI'
        'ECgAZrB8AAxkBmEIZgJOdXD/TnVI5/7AQ+gALHwHdAAUKQAB4UoUEbR8ADNiOlSJUc7/7CJ5'
        'AAJ6utP8AAHFouVJOjEQAJp8ABbpTTwxEALnTpx8AMBD6ABKOAVhEmYIVIk4BmEKYAJwAUzf'
        'A39OdSBJYToyAEHpAARhMjQAQekACGEqNgBKQmsgskJtHLZBbRi2RG4UMAGQQsB8AA9mCjAD'
        'kEHAfAAPTnVwAU51cAAQKAAB4UgQEE51SOf/wEP6AI5+AB4xAAAieQACerrT/AABxaLlSTox'
        'EADpTdp8AgA8MRAC507cfAIAeD9hUrB8//9nOrBHZEBhRrB8/gBtOLBFbjRyD8JAZi5hNLB8'
        '/gBtJrBGbiJyB8JAZhxhIrB8AChiFGEasHwAKGIMUYhQiFHM/7qwAGACcAFM3wP/TnVwABAo'
        'AAHhSBAQVIhOdQ4ODRESDgwPDhcNEgyQTDJCT2YIDKgAAAKAAAROdTItASxnKDAtASSQQSB5'
        'AAJ7QrBoAEpvDjItASTiSbBBbghwAk51cANOdXABTnVwAE51YQAM7mEAAmZhAAyQYQAFDGEA'
        'DKhhAAzQE/wAAQACe+FhAAF4YQBzsGEAdHpKQGoAAQKwfP/+ZySwfP/9ZwAAsLB8//tm0kH6'
        'D5lKeQACe+JnBEH6D7ZhAHUcYLwwATICsnwAFGWysnwAgGQqknwAFEjBgvwADDQ5AAJ75sT8'
        'AAnUQbR5AAJ74mSOM8IAAnvkYQAErGCCsnwAjGQA/3ywfACgZBJKeQACe+ZnAP9sU3kAAnvm'
        'YB40OQACe+ZSQjYCxvwACbZ5AAJ74mQA/0wzwgACe+Y+OQACe+bO/AAJYQB6FmEADCRhAARW'
        'YAD/LLI8AANnsLI8AARnvHD/sjwAAWcKcAGyPAACZgD/Dj45AAJ75GsA/wTeQGsA/v6+eQAC'
        'e+JkAP70YQB5zmEABBJgAP7osHwAAmcqsHwAA2c0sHwABGc0sHwABWcKUkBCOQACe+FOdUI5'
        'AAJ74WEAC3RwAE51YQAGbkpAawRwAk51kchgCmEAdwRgBGEAdTYvCCh5AAJ7Ak6UYQADkiAf'
        'ZwD+iiBAYQBz4GAA/oBwGzI5AAJ75GsQMAFhAAIScABKKgA8ZgJwA051AAgAjgBgAHAAAB6Y'
        'AAAdRABwAI4AYABlAAAfggAAHWAA2ACOAGAAbgAAHp0AAB18AAgAogBgAHIAAIiaAAAdkQBw'
        'AKIAYAB/AABgWAAAHbkA2ACiAGAAEQAAH4cAAB3Y//8ACACiAGAAcgAAIDgAAB33AHAAogBg'
        'AGUAAB+CAAAeEADYAKIAYAARAAAgPwAAHiP//wAIAKIAYAANAAAeoQAAHkQA2ACiAGAAEQAA'
        'HqgAAB5t//9CeQACe+Iz/P//AAJ8ZCA8AABAAEH6DSRD+QAChvQkeQACerZOqgAUM8AAAnxq'
        'SfkAAob0U3kAAnxqa2YgTEoYZvwjyAACfHAsCJyMU4a8fAAFZUa8fAAfYkBD6P/7DBkALmY2'
        'EBmAPAAgsDwAbGYqEBmAPAAgsDwAdmYeEBmAPAAgsDwAbGYSYQB1KmYMDHkCAAACe+JkAmE+'
        'KHkAAnxwYJIwOQACe+RqAnAAsHkAAnviZQgwOQACe+JTQDPAAAJ75HIASkBrCEjAgPwACTIA'
        'M8EAAnvmTnV4ADo5AAJ74rhFZB42BNZF4kswA2FKIkxhAAF6SkBuBjgDUkRg4joDYN5B+QAC'
        'xvQwOQACe+LQQEPwAADYREXwQACzymcGM2EAAmD2QfkAAob0IAyQiDSAUnkAAnviTnVB+QAC'
        'xvTQQDAwAABB+QAChvTQwE51LwFyADIAgvwACbJ5AAJ8ZGcMSOf/3jABYRZM33v/SEHC/ABA'
        'RfkAAsr01cEiH051PwDA/AAJPgBF+QACyvR6CL55AAJ74mQYMAdhnkjnBSBhFkzfBKBF6gBA'
        'UkdRzf/iM98AAnxkTnUiSnAPQplRyP/8Q9IS2Gb8YQAAiCZ5AAJ6tkH5AAJ8dE6rACSwvAAA'
        'IchmbEH5AAJ8dEP5AALNNE6rAAhB+QACzTRhAPmKSkBrTjVAADhB+QAC7HRhAPtEZj5B+QAC'
        '7HwwKgA4MjkAAs2c4FlhAPqMZiZB+QACzUhD6gAgcBcS2FHI//wVeQACzXgAOhV5AALNegA7'
        'UOoAPE51QfoK6EP5AAJ8dBLYZvwTfAAv//9B0hLYZvxOdUjnQMAQGLA8AEFlCrA8AFpiBNA8'
        'ACASGbI8AEFlCrI8AFpiBNI8ACCwAWYISgBm1HAAYAhiBHD/YAJwAUzfAwJOdWEAB/xB+gqN'
        'MjwAAGEACExhAAkmYQD8akH6/IJD+gqDYQBuJnAAMjwAFDQ8AUA2PAB4KHkAAnsGTpRhAAfC'
        'SnkAAnviZhxB+g0WMjwANGEACApB+g0hMjwAQGEAB/5gAAFoPjkAAnvmzvwACXwAvnkAAnvi'
        'ZAAAzDAHYQD+JHQBvnkAAnvkZgJ0ADPCAAJ8bjIGwvwADNJ8ABQzwQACfGxwCGEAB3hKKgA8'
        'Z2JB6gAgdBg2PADAYQAH7DA8AMwyOQACfGw0OQACfG5hAAdQcAAQKgA6YQAIFBb8ADpwABAq'
        'ADuwfAAKZAQW/AAwYQAH/DA8APQyOQACfGw0OQACfG5hAAcaMCoAOGEACAhgKEHSdB82PADA'
        'YQAHjDA8AMwyOQACfGw0OQACfG5hAAbwQfoMXmEAByhSR1JGvHwACWUA/y4MeQAJAAJ74mN8'
        'SnkAAnvmZxRwCDI8AIB0AWEABr5B+gw0YQAG9jA5AAJ75lJAwPwACbB5AAJ74mQWMDwA+DI8'
        'AIB0AWEABpRB+gwVYQAGzDI8AIBhAAaaQfoMDGEABrwwOQACe+ZSQGEABz5B+gv+YQAGqHAA'
        'MDkAAnviUECA/AAJYQAHJGAAB25hAAWyYQAGLDI8ABxhAAZYIHkAAntCdBhhAAacMjwAQGEA'
        'BkRB+gvBYQAGZjAtASxhAAbsQfoLvGEABlYwLQEkYQAG3EH6C7FhAAZGMjwAVmEABhRhAPiS'
        'E8AAAnxOPgBmCkH6C51hAAYoYBZB+guqYQAGHjAHYQAGpkH6C6NhAAYQMjwAZmEABd5B+guZ'
        'YQAGACB5AAJ7QjAoAEphAAaAQfoLlmEABephAAbCQfr6hEP6C5pwAGEAa8RhAAUYE/wAAgAC'
        'e+FhAGz2SkBr8EI5AAJ74T8AYQAFEjAfQfoAChAwAABIgE51AAIBAEI5AAJ8GEK5AAJ8Sih5'
        'AAJ7Ak6UYQABdGEABPoT/AAEAAJ74WEAbKxKQGdqsHwAAWd4sHz//GdysHz//WcQsHz//mbY'
        'MAEyAmEAAOxgzkH5AAJ8EnQMcP+yPAADZzJwAbI8AARnKkH5AAJ8FHQHcP+yPAABZxpwAbI8'
        'AAJnEjABYTJnmEK5AAJ8SmEAAVhgjGEAANxghmEAAkZKQGsA/35COQACe+FwAE51QjkAAnvh'
        'cP9OdbA8AAhnKrA8AH9nJGE4ZjJyABI5AAJ8GLJ8ABRkJEH5AAJ8GhGAEABSOQACfBhgDko5'
        'AAJ8GGcKUzkAAnwYcAFOdXAATnWwPAAtZyqwPABfZySwPAAwZSSwPAA5YxiwPABBZRiwPABa'
        'YwywPABhZQywPAB6YgYAPAAETnUCPAD7TnVB+QACfBJ0DLJ8AEZlKLJ8AFJlFEH5AAJ8FHQH'
        'snwAWmUUsnwAZmQOcgGwfACwZAJy/zABYAJOddBQagQwAlNAsEJlAnAAMIBhAAO2QrkAAnxK'
        'YFphAAO6QfoIOTI8AABhAAQKMjwAEnQAYQAD4kH6CC1hAAP6QfoIQjI8ADBhAAD0QfoIOzI8'
        'AEhhAADoQfoINTI8AFxhAADcYQAErmEOQfr4oEP6CDVwAGAAaa4wPABwMjwAMDQ8ANA2PAA4'
        'KHkAAnsGTpRwADI8AHQ0PAFAdgwoeQACewZOlGEAAzQyPAAwYWgyPABIYQAAlkH6B+FhAAN8'
        'MDkAAnwSYQAEKEH6B9NhAANqMjwAXGF0QfoHwWEAA1xhdDACYQAD4kH6B7lhAANMMANhAAPU'
        'QfoHp2EAAz4gOQACfEpnDjI8AHRhAAMEIEBhAAMoYAAEAGEyQfkAAnwadAAUOQACfBhgBhAY'
        'YQADFlHK//gW/ABfQfoHXGAAAvxwKHQBYQACtGAAAvAwPABwdAFgAAKmIHkAAnq60fwAAcWi'
        'MDkAAnwU5Ug0MAAANjAAAk51QfoHWko5AAJ8GGd+QfoHbQx5AgAAAnviZHBhfGEAAKBB+gd2'
        'vnkAAnviZV5B+QACfDBD+QACfHRhAG/0JHkAAnq2QfkAAnx0TqoAJEH6B0pKgGY2YQAAjGEA'
        'AeYkeQACerYgPAAAIchB+QACfHRD+QACzTROqgAMYQBv9GEA9z5hPGEAb8JwAE51I8gAAnxK'
        'YQD+dHD/TnVB+QACfBpD+QACfDBwABA5AAJ8GGACEthRyP/8QfoGbBLYZvxOdX4AvnkAAnvi'
        'ZBgwB2EA+ChD+QACfDBhAPlSSkBnBFJHYOBOdUH5AALNNDA8CHFCmFHI//xB+QACzTQgvEZP'
        'Uk0hfAAAIcAABCF8TDJMVgAIIXxMMkxIAAwhfAAAAEoAEEPoABRF+QACfBpwABA5AAJ8GHIX'
        'dCBTQGsCFBoSwlHJ//RD6AAsRegAPEf6AJhwBxKbVIkU/AAKUcj/9hF8AAUARBF5AAJ8EwBI'
        'YQD+eJR8ABbpSudLlnwAwEH5AALNNBFCAFLgShFCAFMRQwBU4EsRQwBVIXxMMk1IAF4hfAAA'
        'AAYAYhF5AAJ8EwBmEXkAAnwVAGghfEwyTVAAbCF8AAAezABwQ+gfQCL8TDJCTyL8AAACgDA8'
        'AT8y/P//Ucj/+mAATq4SFhgzExQVESh5AAJ6/k6UKHkAAnsCTpRhAFdMcAcoeQACevZOlE51'
        'IHkAAntOInkAAntWKHkAAnr6TpROdSB5AAJ7SiJ5AAJ7Vih5AAJ6+k6UTnUreQACe1oCHmAI'
        'K3kAAnteAh47fAAVAYYoeQACetpOlE51O3wANAFcKHkAAnrSTpROdUf5AAJ+9Bb8AAdOdRb8'
        'AAdCG0IbFvwAoBb8AGROdWHsFvwABBb8AAEWwBbBFvwACBbCTnUvAnQBYQQkH051FvwAB0Ib'
        '4kkWwRb8AKAW/ABkFvwABRb8AAgWwk51YdYQGGcEYQRg+E51sDwAIGUQsDwAI2cKsDwAemIE'
        'FsBOdRb8ACBOdSJLU0JrChAYZwZh2FHK//i3yWcMDCsAIP//ZgRTi2DwTnVI5wgIKHkAAns2'
        'IktTQmsgEBhnHGGseAAYK///mHwAIBg0QACWRGsGUcr/5mACU4u3yWcMDCsAIP//ZgRTi2Dw'
        'TN8QEE51wLwAAP//dACA/AAKSEDQPAAwPwBSQkJASEBKQGbqMB8WwFNCZvhOdSB5AAJ7RudI'
        '0MAQGLA8AGFlCrA8AHpiBJA8ACBhAP82dAdgAP9MQhNB+QACfvQoeQACewpOlE51IHkAAnti'
        'RfkAAny0R/rl8n4DTJsAcFSLYT5Rz//2dB0yPACycARhAADKUkCwfABDZvRSQbJ8AMRm6kX5'
        'AAJ8tEf65b5+A1iLPBs4Gzo8ALVhKFHP//JOdS8HfgswBDhGMgVhWBTCUkBTTLj8AABm8FJF'
        'Uc//6C4fTnUvB34LMAQ4RjIFFBq0PAAdZwJhZFJAU0y4/AAAZupSRVHP/+IuH051NgHG/AAo'
        'IkjTwzYA5kvSwzYARkPGfAAHTnVh5HQAByl9AGcECMIABAcpXcBnBAjCAAMHKT6AZwQIwgAC'
        'BykfQGcECMIAAQcRZwQIwgAATnVhrggCAABnBAfRYAIHkQgCAAFnBgfpH0BgBAepH0AIAgAC'
        'ZwYH6T6AYAQHqT6ACAIAA2cGB+ldwGAEB6ldwAgCAARnBgfpfQBOdQepfQBOdUxldmVscwBD'
        'dXN0b20gTGV2ZWxzAENsaWNrIGEgbGV2ZWwsIG9yIHVzZSB0aGUgY3Vyc29yIGtleXMAVGhl'
        'cmUgaXMgbm8gbGV2ZWwgeWV0OiBtYWtlIG9uZSB3aXRoIE5ldwBBIGRhbWFnZWQgZmlsZTog'
        'b25seSBSZW5hbWUgb3IgRGVsZXRlAFBsYXkgdGhlIHNlbGVjdGVkIGxldmVsIChQKQBFZGl0'
        'IHRoZSBzZWxlY3RlZCBsZXZlbCAoRSkATWFrZSBhIG5ldyBsZXZlbCAoTikAR2l2ZSB0aGUg'
        'c2VsZWN0ZWQgZmlsZSBhbm90aGVyIG5hbWUgKFIpAERlbGV0ZSB0aGUgc2VsZWN0ZWQgZmls'
        'ZSAoRGVsKQBCYWNrIHRvIHRoZSB0aXRsZSBzY3JlZW4gKEVzYykAUGxheSB0aGUgbGV2ZWwg'
        'YWdhaW4gKFIpAEVkaXQgdGhlIGxldmVsIChFKQBCYWNrIHRvIHRoZSBsaXN0IG9mIGxldmVs'
        'cyAoRXNjKQBXcml0ZSB0aGUgbmV3IGxldmVsIGFuZCBlZGl0IGl0IChSZXR1cm4pAEJhY2sg'
        'dG8gdGhlIGxpc3Qgd2l0aG91dCBhIG5ldyBsZXZlbCAoRXNjKQBQbGF5AE5ldwBDcmVhdGUA'
        'Q2FuY2VsAE5ldyBMZXZlbABFZGl0b3IgVjEuMSBieSBUaW1vIEhlaW1vbmVuAEZpbGUAU3R5'
        'bGUAU2l6ZQAubHZsADwgIAAgID4AIHggAFR5cGUgYSBuYW1lLiBDdXJzb3Iga2V5czogc3R5'
        'bGUgYW5kIHNpemUAVHlwZSBhIG5hbWUgZm9yIHRoZSBmaWxlIGZpcnN0AFRoZSBsaXN0IGlz'
        'IGZ1bGw6IDUxMiBsZXZlbHMAVGhlcmUgaXMgYSBsZXZlbCBvZiB0aGlzIG5hbWUgYWxyZWFk'
        'eQBFZGl0AEJhY2sAVGhlcmUgYXJlIG5vIGxldmVscyBpbgB0aGUgTGV2ZWxzIGRpcmVjdG9y'
        'eSB5ZXQAZGFtYWdlZAA8IFByZXZpb3VzAE5leHQgPgBQYWdlIAAgb2YgAFlvdSBzYXZlZCAA'
        'IG9mIAAgTGVtbWluZ3MATm8gTGVtbWluZ3Mgd2VyZSBzYXZlZABHcmFkZSAAIG9mIDMAQmVz'
        'dCBncmFkZTogdXAgdG8gACBsb3N0AFJlcGxheQBMZXZlbHMAUmVwbGF5IGl0LCBlZGl0IGl0'
        'LCBvciBiYWNrIHRvIHRoZSBsaXN0AEVkaXRvcjogdGhpcyBpcyBub3QgdGhlIHN1cHBvcnRl'
        'ZCBnYW1lAEVkaXRvcjogbm90IGVub3VnaCBjaGlwIG1lbW9yeSBmcm9tIHRoZSBzbGF2ZQBk'
        'YXRhL0VkaXRvclRpbGVzANR8ACwwAtBD0nwAgHYA4knjUwgCAAhnAlhDCAAACGcCVEPhSIZA'
        '4UqCQjABSEAwA0zfAA5OdQAAAAAAAAAEBAQEBAAECgoKAAAAAAofCgofCgAEDxQOBR4EGRoC'
        'BAgLEwwSFAwVEg0EBAgAAAAAAgQICAgEAggEAgICBAgAFQ4fDhUAAAQEHwQEAAAAAAAEBAgA'
        'AAAfAAAAAAAAAAAABAECAgQICBAOERMVGREOBAwEBAQEDg4RAQIECB8eAQEOAQEeAgYKEh8C'
        'Ah8QEB4BAR4OEBAeEREOHwECBAgICA4REQ4REQ4OEREPAQEOAAQAAAQAAAAEAAAEBAgCBAgQ'
        'CAQCAAAfAB8AAAgEAgECBAgOEQECBAAEDhEXFRcQDw4RER8REREeEREeEREeDxAQEBAQDx4R'
        'ERERER4fEBAeEBAfHxAQHhAQEA8QEBcREQ4REREfERERDgQEBAQEDgEBAQEREQ4REhQYFBIR'
        'EBAQEBAQHxEbFRURERERGRUTERERDhERERERDh4RER4QEBAOERERFRINHhERHhQSEQ8QEA4B'
        'AR4fBAQEBAQEERERERERDhERERERCgQREREVFRsREREKBAoRERERCgQEBAQfAQIECBAfDggI'
        'CAgIDhAICAQCAgEOAgICAgIOBAoRAAAAAAAAAAAAAB8IBAAAAAAAAAAOAQ8RDxAQHhERER4A'
        'AA4QEBAOAQEPERERDwAADhEfEA8GCAgeCAgIAA8REQ8BDhAQHhEREREEAAwEBAQOAgAGAgIS'
        'DBAQEhQYFBIMBAQEBAQOAAAaFRUVEQAAHhEREREAAA4REREOAB4RER4QEAAPEREPAQEAABYY'
        'EBAQAAAPEA4BHggIHggICAYAABEREREPAAAREREKBAAAEREVFQoAABEKBAoRABEREQ8BDgAA'
        'HwIECB8DBAQIBAQDBAQEBAQEBBgEBAIEBBgAAAkWAAAAAPQB/wABAAIAAYAAAAGCAAABhAAA'
        'AYYAAAGIAAABigAAAYwAAAGOAAABkAAAAZIAAAGUAAABlgAAAZgAAAGaAAABnAAAAZ4AAAEC'
        'AAAAkgA4AJQA0AEIAAABCgAAAOAAAADiAAAA5AAAAOYAAADoAAAA6gAAAOwAAADuAAD2Af8A'
        'AQBCAP////4AAAIjA0UEaAmrABIN3giJD8MDag5VBcYOtAAAAAAP/0H6/1YieQACe64wPABD'
        'MthRyP/8InkAAnuuQ+kAXiA5AAJ7snIDSEAygEhAM0AABFCJ0LwAAAcwUcn/7E51SOf/4EpC'
        'bwAAjkpDbwAAiDoA2kJTRXz/PgDOfAAP7m4+Bc58AA8KRwAPdP/vauhI6E2aQGYCzEIgeQAC'
        'e7LC/AAo0cHQQNDAU0MiSH4DMgQkSeJJZBaNWjAFZypTQGAENPz//1HI//qFUmAaMAZGQMFa'
        'MAVnEFNAYAJCWlHI//wwAkZAwVJD6QcwUc//xEHoAChRy/+2TN8H/051SOf/4LA8ACBjYLA8'
        'AH5iWsB8AP+QfAAgwPwAB0H6+8bQwCJ5AAJ7ssT8ACjTwjAB6EjQQNLAfBvCfAAPnEF6BngA'
        'GBjtrCRJMgN+A+JJZASJkmAGIARGgMGSReoHMFHP/+xD6QAoUc3/2EzfB/9OdUjnyIBTRGsM'
        'EBhnCGGCXEFRzP/2TN8BE051Lwhw/1JAShhm+iBfTnVI5/+AMBEyKQACNCkABHYMeAK6fAAB'
        'ZxC6fAAFZwq6fAACZgZ4CWACeANhAP6geAR2AWEA/ph0AXYMYQD+kHgF0GkABFNAYQD+hDAR'
        '0nwACzQpAAR2AWEA/nR2Brp8AANmAnYHunwAAmYCdgggaQAIYYDA/AAGU0AyKQAEkkDiQdJR'
        'NCkAAlRCeChhAP9MunwABGU2eAgwEVNAMikAAlNBNCkABFRCdgFhAP4i0nwADWEA/hoyKQAC'
        'dAF2DGEA/g7QaQAEUkBhAP4ETN8B/051SOf4gDARMikAAjQpAAR2DHgBYQD96DApAAZhABWw'
        'MhE0KQACVEI4KQAESMSI/AAGYQD+1kzfAR9OdUjn+ABwADICNDwBQHYIeAFhAP2wTNcAH3IE'
        'eDRhAP6wTN8AH051cAByADQ8AUB2LngBYQD9jkH5AAAABHAfMPz//1HI//pQ+QAAAEhQ+QAA'
        'AElQ+QAAAEdCOQAAAEZKOQAAAEZmwCJ5AAAAAEX5AAAABDARaywwKQAGYQAT5EppAAZqDko5'
        'AAAAR2cOYQD/OGAIulJnBGEA/l40xUPpABBg0EI5AAAAR0o5AAAASGdIQjkAAABISjkAAABL'
        'ZhBB+QAAAEx0HHYGYQD/NmAQMDwBEnIcdCp2CHgBYQD85ko5AAJ77mcSQfobCTI8ARJ0HHYM'
        'eAdhAP3YSjkAAABJZxpCOQAAAElB+QAAALh0JjY5AAAARGEA/uphAk51QfkAAAC4YQD9xHIz'
        'kkBB+gF0YQD9uLJAbAxB+gF+YQD9rLJAbRQ4AMD8AAYyPAE8kkB0JnYJYQD9ek51Mi0BCJJ8'
        'AMprQDAtAQYieQAAAABKUWsySmkABmsmsFFlIjQR1GkABLBCZBiyaQACZRI0KQAC1HwADLJC'
        'ZAYwKQAGTnVD6QAQYMpw/051InkAAAAASlFrDLBpAAZnCEPpABBg8JPJTnVI58DAMgBD+QAA'
        'ALhwABLYZwpSQLB8ADVl9EIRsnkAAABEZhhB+QAAALhD+QAAAO4QGLAZZgZKAGb2YBwzwQAA'
        'AERB+QAAALhD+QAAAO4S2Gb8UPkAAABJTN8DA051QfkAAABMQ/kAAACCEBiwGWYUSgBm9hA5'
        'AAJ77rA5AAAASmYCTnVB+QAAAExD+QAAAIIS2Gb8E/kAAnvuAAAASlD5AAAASE51Fthm/FOL'
        'TnVI5+AAwLwAAP//dACA/AAKSEDQPAAwPwBSQkJASEBKQGbqMB8WwFNCZvhCE0zfAAdOdVYx'
        'LjEgYnkgVGltbyBIZWltb25lbgBWMS4xIGJ5IFRpbW8gSC4AYQDgqkpAa3Q/AEH5AALNNEP5'
        'AAABJGEA4GxB+QACfHRD+QAAIuwS2Gb8UfkAAnvuUPkAAnvsYQBR7kH5AALNNGEAPoIzwQAA'
        'pfRnJkH5AALNNEP5AAABJGEA4CpB+QACzTRD+QAApgZhAOAaUPkAAnvuMB9hAOCucABOdXD/'
        'TnVKOQACe+xmFC85AAJ7ni85AAJ7ai85AAJ7Zk51Si0Bz2cIKHkAAnsmTpQT/AADAAJ74VH5'
        'AAJ781H5AAJ8F0H6AkQrSAIiM/wAEAAAbvphAAKGO3wA9wFWYQADMmEADHhKOQACfBZnMlH5'
        'AAJ8FjP5AACl9gAAdu4z+QAApfgAAHbwUPkAAHbyUfkAAnv7UfkAAG8WYQA7xmB6QnkAAG8E'
        'YQA+AkJ5AAJ8EGEAEn4z/P//AAJ79Ep5AABvHGcScAGweQAAbxxlAnAAYQAJTGAGcAFhAAl2'
        'UfkAAnvvUfkAAnvwUfkAAnv6UfkAAnv7UfkAAHbyQnkAAnv8M/z//wACe/4z/P//AAJ8AEJ5'
        'AAJ8ZmEAGx5hACOYE/wAAAACe+1hAAZ2M/z//wAAbwJKOQACfFZnClH5AAJ8VmEADQIoeQAC'
        'e2ZOlAw5AAEAAnvtZwATfgw5AAMAAnvtZwAvrGEAAoIoeQACe25OlCh5AAJ7ck6UUO0BySh5'
        'AAJ7dk6UUe0BySh5AAJ7ek6UKHkAAnt+TpRKLQG8Zg5R+QAAbxYz/P//AAB27GEAA1BhAAN2'
        'DDkAAgACe+1nUAw5AAQAAnvtZzYMOQAFAAJ77WcyEDkAAnv6ZxCwPAABZxRhADhIYQA+lGAo'
        'YQADgmEACPhgHmEAJZBhACj+YBRhAEFcYA5hAD8eYQA/bGAEYQAMpmEADQhhAA4cYQD7AmEA'
        'T/xQ7QHLSjkAAnvzZhhKOQACfBdmAEG2SjkAAnxVZgBSVGAA/wBhKmEAALQreQACe5oCIih5'
        'AAJ7kk6UO3wAyQFWUfkAAnvsQjkAAnvhYADcCHAPPwAoeQACe45OlGEAAKQwH1HI/+5OdS15'
        'AAJ7rgCEsHwABG0qSi0By2ceQi0By0JtAPwiLQHyK20B7gHyK0EB7gptAAEBFmAGO3wABAD8'
        'KHkAAnuKTpRKeQAAbvpnCFN5AABu+mE6TnVhAPdmLXkAAnuuAIQgeQACer4xfCTCAQIhfACK'
        'AAABxE51IHkAAnq+IXz////+AcQxfPTCAQJOdSB5AAJ7pmEmYTRB+vcEYBBB+QAAUyxhFmEk'
        'QfkAAFMsInkAAnuuRekASFCJYBAieQACer5F6QHEQ+kANE51s8pkOjAZsHwBgGUusHwBvmIo'
        'Mhg0EXYCeA96ATwBzEQ+As5EvkZnCGIE1EVgApRF6UzpTVHL/+YyglSJYMJOdTAtAQyQfAAW'
        '6UgzwAAAbvYwLQEO50iQfADAM8AAAG74MC0A/sB8//CweQAAbvZvBjA5AABu9jtAAP4wLQEA'
        'wHz/8LB5AABu+G8GMDkAAG74O0ABAE51YQAAmko5AAB28mcYUfkAAHbyO3kAAHbuAP47eQAA'
        'dvABAGByYQAAiDItAP40LQEACAMAAGcQsnwAEG0iknwAEFDsAAFgGAgDAAFnEjAB0HwAELB5'
        'AABu9m4EMgBQ1AgDAAJnELR8ABBtJJR8ABBQ7AACYBoIAwADZxQwAtB8ABCweQAAbvhuBjQA'
        'UOwAAztBAP47QgEAUe0Byk51MC0BFuVIKHkAAnui2MBClE51dgAQLQKvsDwAA2YECMMAALA8'
        'AARmBAjDAAGwPAABZgQIwwACsDwAAmYECMMAA0pDZjQwLQEGMi0BCLJ8AKBkHEpAZgQIwwAA'
        'sHwBP2YECMMAAUpBZhAIwwACYAqyfAD3ZgQIwwADTnUoeQACe4JOlMB8AP8zwAAAbv6wPABB'
        'ZQqwPABaYgSAPAAgM8AAAG78TnVwAAxtAKABCGUCcAGweQAAbwJnMDPAAABvAkpAZhAreQAC'
        'e6oCHjt8ABABhmAOK3kAAntaAh47fAAVAYYoeQACe4ZOlE51YQD4qDPAAABvADA5AABu/GcE'
        'YQABakotAb5nGlH5AABvFgxtAKABCGUAA+IwOQAAbwBrJGAkSi0BvGcKDG0AoAEIZQAD2kot'
        'AcJnDAxtAKABCGQEYAACFk51YQALVrp8AANnCj8AYQACUDAfYAJOdbB8ACxnAE6asHwAHGQA'
        'NWawfAABZwABgLB8AAJnAAF8sHwAA2cAAXiwfAAEZwBOPrB8AAVnAE2qsHwABmcATcCwfAAH'
        'ZwAHrLB8AAhnAAgYsHwACWcADiCwfAAKZwABnrB8AAtnAAGqsHwADGcAAbCwfAANZwABsAw5'
        'AAMAAnvtZxqwfAAOZwAOIrB8AA9nAA4ssHwAEGcADjJgGLB8AA5nACpEsHwAD2cAKlCwfAAQ'
        'ZwAqYLB8ABFnAAfisHwAEmcAB96wfAATZwAH3rB8ABRnACnUsHwAFWcAI1ywfAAWZwAjerB8'
        'ABdnACN4sHwAGGcAI3awfAAZZwAjdLB8ABpnACOksHwAG2cAI6BOdbA8AHRnAACCsDwAb2d+'
        'sDwAbGd8sDwAZWcATUSwPAB1ZwBMnrA8AHNnUrA8ABFnAAcosDwAbWcAAOgMOQABAAJ7+mcA'
        'ITIMOQACAAJ7+mcAM4qwPABwZwANELA8AHJnAACOsDwAa2cAAJqwPABkZwAAoLA8AGlnAACg'
        'TnVKOQACe+5mAAZgTnVwAGAGcAFgAnACsDkAAnv6Z1ITwAACe/pR+QACe/tR+QAAbxZCeQAC'
        'fGZB+g9CUfkAAABLEDkAAnv6ZxRB+iwIsDwAAWcKQfpB+FD5AAAASyPIAAAAADP8//8AAG8A'
        'UPkAAABGTnVGOQACe+9R+QACe/BQ+QAAAEdOdUY5AAJ78FD5AAAAR051RjkAAnvxTnVGOQAC'
        'e/JOdUYtAetnCih5AAJ7kk6UTnUoeQACe5ZOlE51O3wABQFcKHkAAnrSTpROdTAtAQbQbQD+'
        '0HwAEOhIMi0BCNJtAQDSfAAQ5klOdUjnIACwfAABbSQ0LQEMVUKwQm4asnwAAm0UNC0BDldC'
        'skJuCkzfAAQAPAAETnVM3wAEAjwA+051NgHG7QEM1kDli0H5AAABmNHDTnVI5/iAYa5mIGHi'
        'tJBnGiCCUPkAAnvuUPkAAnxPUPkAAG8iUnkAAnv4TN8BH051YQD/ZjPAAABvGDPBAABvGmF0'
        'UfkAAG8iInkAAG8SfAB6ADQZZz7EvAAAA/9KOQACe+9nBHQAYBhKOQACe/FnBAjCAB5KOQAC'
        'e/JnBAjCABwwOQAAbwzQRTI5AABvDtJGYQD/cFJFunkAAG8IZbRSRrx5AABvCmWoSjkAAG8i'
        'ZwRhABtkTnU0OQAAbwhTQuJCkEIzwAAAbww0OQAAbwpTQuJCkkIzwQAAbw5OdUo5AAJ78GZQ'
        'UPkAAG8WYAD/REo5AABvFmc8SjkAAnvwZjRKOQACe+9mFAx5AAEAAG8IZiIMeQABAABvCmYY'
        'YQD+fLB5AABvGGYA/wqyeQAAbxpmAP8ATnVR+QACe/BQ+QAAAEdhAP5WYQD+cGYsYQD+oiQQ'
        'MALAfAP/Zx5hWAgCAB5W+QACe/EIAgAcVvkAAnvyUfkAAnvvTnVB+hGOcAxgAATiM8AAAnv0'
        '5UhB+QAAU6wgcAAAcAAQKAACM8AAAG8IECgAAzPAAABvClyII8gAAG8SYCgz/P//AAJ79DPA'
        'AABvEDP8AAEAAG8IM/wAAQAAbwoj/AAAbxAAAG8SSOf8wFD5AAAARyB5AABvEjA5AABvCMD5'
        'AABvClNAQ/kAACMsMi0BTML8BADTwXYAeAB6ADIYwnwD/2cWUkMUMRAACAIAAGcCUkQIAgAB'
        'ZwJSRVHI/+DYRLhDUvkAAnvx2kW6Q1L5AAJ78kzfAz9OdQxtAKABCGR6YQD9REo5AAJ78GcI'
        'dAF2AWAAAMxhAP5OInkAAG8SfAB6ADQZZyYwOQAAbwzQRTI5AABvDtJGYQD9LGYQxHwD/0o5'
        'AAJ772cCdABhMFJFunkAAG8IZcxSRrx5AABvCmXAMDkAAG8MMjkAAG8ONDkAAG8INjkAAG8K'
        'YGROdUjn8ODpSJBtAP5rJrB8AWBkIOdJkm0BAGsYsnwAuGISIm0B8sL8ACzTweZI0sBhCGEW'
        'TN8HD051IG0CTsS8AAAD/+2K0cJOdXADJElyBzSYReoALFHJ//hD6SEAUcj/7E516UiQbQD+'
        '50mSbQEA6UrnS0jn/+AgbQHy6EDoQtRAU0I4AToB2kNTRTwEYS48BWEqPARTRVJGvEVuGkpG'
        'axS8fADAZBA+ADY8gABhKj4CdgFhJGDgTN8H/051SkZrFrx8AMBkED4AvkJuCjY8//9hBlJH'
        'YPJOdUpHaxi+fAAWZBIyBsL8ACwiSNPBMgfSQdLBYAJOdUjn/2A4ETopIQA8KUIAPiljAEX5'
        'AABu5HQAcg8DA2cicAADB2cCUEADBmcCWEADBWcCVEADBGcCUkBKMgAAZwIDwlHJ/9gyA7VB'
        'RkMcOQAAbvQeOQAAbvV6AzgRyEPiDmQCiELiD2QCiEEyhEPpIQBRzf/oTN8G/051SOf/wCB5'
        'AAJ7pnYAev8+PH//MBhhSLJFbwQ4AzoBskdsBDwDPgFSQ7Z8ABBl5BPEAABu9BPGAABu9dpH'
        'IHkAAnumQ/kAAG7kdg8wGGEQ0kGyRVPZUcv/9EzfA/9OdXIPwkDoSHQPxEDE/AAG0kLoSMB8'
        'AA/A/AAD0kBOdUjn/+AgbQHy6EDoQtRAU0I4AVREOgHaQ1dFPARhMDwFYSw8BFRGvEVsHkpG'
        'a/a8fADAZBQ+ADY8IABhAP6wPgJ2BGEA/qhg3EzfB/9OdUpGayS8fADAZB4+ADY8Cqq+QmcM'
        'YQD+iDY8qqpSR2DwxnyqqGAA/nhOdSR5AAJ6tiA8AAAhyEH5AAAi7EP5AAABJE6qAAxCrQKq'
        'Qm0CrlH5AAJ77mEAQ9hH+QAAbqRhABaEZh5B+g2RYQDxFkH5AAAi7GEA8QxB+QAAbqRwC2AA'
        'ANgvCEH6KkthAPD2IF9hAPDwQfkAAG6kcAxgAAC8SjkAAnvuZzIT/AAAAAJ8V0H6CbBhOEf5'
        'AABuLEH6DSRhAPDAQfkAACLzYQDwtkH6DSdgAPCuYQD/VFD5AAJ78051E/wAAAACe+1gAPkO'
        'E/wAAgACe+0jyAAAAABR+QAAAEsz/P//AABvAFD5AAAARk51YQDvYDPAAABvADA5AABu/LA8'
        'AA1mDEo5AAJ8V2YARapgorA8ABFnqLA8AGRmCEo5AAJ8V2eSSi0BvmcKMDkAAG8AagD2zk51'
        'M8AAAG8GQ/kAAG6ks8hnBBLYZvwz/AAoAABvBE51SnkAAG8EZxZTeQAAbwRB+QAAbqQwOQAA'
        'bwZgAO9IMDkAAG8Aa0KwfAAHZihhABVAZyJH+QAAdmgvCEH6KQthAO/KIF9hAO/EQfkAAHZo'
        'cAxgAO8SMDkAAG8AYQDu7iBpAAxwBmAA7v5B+gyuDDkAAgACe+1mFkH6C8RKOQACfFdnAACQ'
        'QfpGm2AAAIgMOQAEAAJ77WYGQfo/22B2DDkABQACe+1mBkH6QC1gZgw5AAEAAnvtZxAMOQAD'
        'AAJ77WYYQfooWWAEQfoLRQxtAKABCGVAQfoMRGA6DDkAAgACe/pnADeWDG0AoAEIZCZKOQAC'
        'e/pmAB84QfoKrko5AAJ772cEQfoKxEo5AAJ78GcEQfoK2nAHYADuTkf5AAAATEo5AAAAS2YA'
        'AJAMOQAEAAJ77WdYDG0AoAEIZFAMOQABAAJ7+mcAHUBhAPfSOAA6AUH6C3dhAO62YQDuuhb8'
        'ACwwBWEA7rAW/AAgFvwAIDAEMgVhAPfGZgphAPf4JBBhPmA2QfoLS2EA7oRgLEH6C1ZhAO56'
        'QfkAAAE4cBciSxIYZwYWwVHI//i3yWcMDCsAIP//ZgRTi2DwQhNgAO4IMALAfAP/ZghB+gs3'
        'YADuQEH6CxxhAO44YQDuPAgCAB5mDggCABxmFkH6Cx1gAO4gQfoLHGEA7hgIAgAcZwhB+gsV'
        'YADuCk51LwF6ALB8AANiEjIAU0GyOQACe/pnAAESYAABArB8AARnAAD6sHwABmIQYQBCzLp8'
        'AANnAAD6YAAA5LB8AAdmDko5AAJ77mcAAORgAADQQfkAAnvvsHwACmcAAL5B+QACe/CwfAAL'
        'ZwAAsEH5AAJ78bB8AAxnAACiQfkAAnvysHwADWcAAJSwfAAPZiIMOQADAAJ77WcMSnkAAnv2'
        'ZwAAjmB6SnkAAnwCZwAAgmBusHwAEGYqDDkAAwACe+1nEDI5AAJ79rJ5AABvIGRgYE4yOQAC'
        'fAKyeQAAcyZkUGA+sHwAEWcSsHwAKmcMsHwAMWcGsHwALGYEegRgIrB8ABRlHLB8ABxlBmEA'
        'NbJgBGEAHVy6fAADZxhgBEoQZgyweQAAbwBmClJFYAZ6AmACegMiH051SOfgEHYGsHyAAmYM'
        'QfkAAG4sdghgAADCR/kAAG58sHyACGUIYQA2LmAAAKawfIAEZQhhAB1wYAAAmLB8gANmQkH6'
        'CX9hAOyOMDkAAnv2UkBhAOyKFvwALdB8ABOweQAAbx5jBjA5AABvHmEA7HBB+uMSYQDsYDA5'
        'AABvHmEA7F5gTkp5AAJ79GswQfoJLmEA7EQwOQACe/RhAOxCFvwAIDA5AABvCGEA7DQW/AB4'
        'MDkAAG8KYQDsJmAWQfoI+GEA7BQwOQAAbxDAfAP/YQDsDkITQfkAAG58TN8IB051QnkAAG8c'
        'QnkAAG8eQnkAAnv2QfkAAGasMDwB3yD8/////1HI//hB+QAAV6wwPAO/QphRyP/8IG0CTgyo'
        'TDJCTP/2ZmBViNHo//wMkEwyQkVmUi4oAARQiEXweAA8GFNGa0JD+QAAU6x6ALHKZBq6fAEA'
        'ZBQiyGE0cAAwKAAEZwjRwFJFUc7/5DPFAABvHDA5AABvHpB8ABRqAnAAM8AAAG8gTnVCeQAA'
        'byBOdUjn//BwABAQcgASKAABdAAUKAACdgAWKAADR+gABjgA2EK4fAAUYko4AdhDuHwAYGJA'
        'uHkAAG8eYwYzxAAAbx5TQzwBzPwAFNxAPgJTR0P5AABmrBOFYABD+QAAV6w4BthEM5tAAFJG'
        'Uc//5FJBUcv/0kzfD/9OdUp5AABvHGciE/wAAQACe+1B+gNeI8gAAAAAM/z//wAAbwBQ+QAA'
        'AEZOdUH6B0JwCmAA+ngT/AAAAAJ77VH5AABvFmAA8wYwOQACe/ZVQGoacABgFjA5AAJ79lRA'
        'sHkAAG8gbwYwOQAAbyCweQACe/ZnDDPAAAJ79lD5AAAAR051YQDvrih5AAJ7ck6UKHkAAnt+'
        'TpRhAPAUYQDwOmEeYS5hAADKYQABOmEA+h5hAAF4YQDoGFDtActgAOw2YQDvhAgDAAJmgAgD'
        'AANmiE51Im0B8kPpAsI8OQACe/Z+EzgGyPwAKEf5AABXrNfEehMoSXQAvHkAAG8eZAI0G0jn'
        'BEAiTGEA9kxhAPZYTN8CIFSMUc3/3kPpAWBSRlHP/8JOdXD/dAAyLQEIsnwAoGQ85knSeQAC'
        'e/ayeQAAbx5kLML8ABQ0LQEG6ErSQkH5AABmrHAAEDAQALA8AP9mAnD/QfkAAFes0kE0MBAA'
        'TnVhAOhWM8AAAG8AMDkAAG78sDwAEWcA/rJKLQG+Zy4MbQCgAQhkGmGMSkBrRmEA9DBR+QAC'
        'e+9R+QACe/BgAP6KMDkAAG8AagDvwE51Si0BwmcgYQD/YDACwHwD/2cUYQD0MFH5AAJ771H5'
        'AAJ78GAA/lhOdWEA/z5KQGs85UhB+QAAU6wgcAAAcAAQEOlI0HwAEHIAEigAAZJ5AAJ79udJ'
        '0nwAEHQAFCgAAulKdgAWKAAD50tgAPVoTnVH+QAAAExhAP7ySkBrVDgAOgJB+gV+YQDolDAE'
        'YQDoluVMQfkAAFOsIHBAABb8ACBwABAoAAJhAOh8FvwAeBAoAANhAOhwFvwAIBb8ACAwBcB8'
        'A/9nDEH6BTRhAOhQYQDoVEITYADn/gACAAAALgABAABCUAAAQsEAMgAAAC4AAgAAQlgAAGBn'
        'AGIAAAAiAAMAAEJgAAB2ggCGAAAAHAAEAABCZgAAf8AAyAAAABwABQAAQmsAAH/gAOYAAAAc'
        'AAYAAEJwAAB/+QEEAAAAHAAHAABCdQAAQuYBIgAAABwACAAAQnoAAEMFAAIADQAoAAkAAEJ/'
        'AABDJgAuAA0AYIABAAAAAAAAAAAAkgANACIACgAAQoYAAENJALYADQAcAAsAAEKMAABDdwDU'
        'AA0AIgAMAABCkQAAQ6MA+AANACIADQAAQpcAAEPO//8AAgAAACIADgAAQp0AAEP2AOYAAAAc'
        'AA8AAEKiAABEHwEEAAAAIgAQAABCpQAARD8AKAAAALqAAwAAAAAAAAAA//8ABAAAATiAAgAA'
        'AAAAAAAAAFgADQAiABEAAEJ1AABEYQCAAA0ANAASAABCqgAARIoAugANAC4AEwAAQrIAAES3'
        '//9UZXJyYWluAE9iamVjdHMAUGFyYW0AVGVzdABVbmRvAFJlZG8AU2F2ZQBNZW51AFBpZWNl'
        'cwBFcmFzZQBQaWNrAERlY29yAFN0ZWVsAEJhY2sAVXAARG93bgBEaXNjYXJkAENhbmNlbABV'
        'bnNhdmVkAFRlcnJhaW46IGRyYXcgdGhlIGxldmVsJ3MgZ3JvdW5kIChUKQBTYXZlIHRoZSBs'
        'ZXZlbCB0byBpdHMgZmlsZSAoUykAQmFjayB0byB0aGUgbGlzdCBvZiBsZXZlbHMgKEVzYykA'
        'Q2hvb3NlIGEgdGVycmFpbiBwaWVjZSBvciB0aWxlIChQKQBFcmFzZSB3aXRoIHRoZSBicnVz'
        'aCdzIHNoYXBlIChSLCByaWdodCBjbGljaykAVGFrZSBhIHRpbGUgZnJvbSB0aGUgbGV2ZWwg'
        'YXMgdGhlIGJydXNoIChLKQBEZWNvcjogbGVtbWluZ3MgcGFzcyB0aHJvdWdoIHRoZSBjZWxs'
        'cyAoRCkAU3RlZWw6IGNhbm5vdCBiZSBkdWcgb3IgYmFzaGVkIGF3YXkgKEkpAEJhY2sgdG8g'
        'dGhlIGxldmVsIHdpdGhvdXQgY2hvb3NpbmcgKEVzYykAU2hvdyB0aGUgcm93cyBhYm92ZSAo'
        'Y3Vyc29yIHVwKQBTaG93IHRoZSByb3dzIGJlbG93IChjdXJzb3IgZG93bikAU2F2ZSB0aGUg'
        'Y2hhbmdlcywgdGhlbiB0aGUgbGlzdCAoUmV0dXJuKQBMZWF2ZSB0aGUgY2hhbmdlcyB1bnNh'
        'dmVkLCB0aGVuIHRoZSBsaXN0IChEKQBLZWVwIGVkaXRpbmcgKEVzYykAQ2xpY2s6IGRyYXcg'
        'ICAgUmlnaHQgY2xpY2s6IGVyYXNlAENsaWNrOiBlcmFzZSAgICBSaWdodCBjbGljazogZHJh'
        'dwBDbGljazogdGFrZSB0aGlzIHRpbGUgYXMgdGhlIGJydXNoAENsaWNrOiB0YWtlIHRoZSBw'
        'aWVjZSAgICBSaWdodCBjbGljazogb25lIHRpbGUAUmV0dXJuOiBzYXZlICAgRDogZGlzY2Fy'
        'ZCAgIEVzYzoga2VlcCBlZGl0aW5nAFNhdmUgdGhlIGNoYW5nZXMgdG8gAD8AU2F2ZWQgAFRo'
        'ZXJlIGlzIG5vIHRpbGUgdG8gdGFrZSBoZXJlAFRoaXMgc3R5bGUgaGFzIG5vIHRlcnJhaW4g'
        'cGllY2VzAENlbGwgAEJvcmRlciwgbm90IGVkaXRhYmxlAExldmVsOiAAVGlsZSAAUGllY2Ug'
        'AFJvd3MgAEVtcHR5ACBTb2xpZAAgRGVjb3IAIFN0ZWVsAAAASOf/+HAAKHkAAnu2TpQ+KP/+'
        'vnwAIGMCfiAzxwACfA5H+QAAbyRTR2sAAI4miGEAAJIXQAAYF0EAGUP6FtoXcQAAABpwAHIA'
        'dAB2AGEAAkJD6wAEYQAEQFD5AAB280P5AAB2smEABDBR+QAAdvMwEcB8//BEQDdAABDQaQAE'
        '0HwAD8B8//A3QAAUMCkAAsB8//hEQDdAABLQaQAGXkDAfP/4N0AAFjAQwPwADEHwCBRH6wAc'
        'Uc//dmEAAMhM3x//TnVI5z/AcgB4AHoAPCgAAj4QQegAFFNHa1Q0EAgCAA1nBAjBAAAIAgAM'
        'ZwQIwQABCAIAC2cMdgAWArZ8ABBkAgfEJigABiADwLwAABgAsLwAABAAZhBwFuCrxnwAP7Z8'
        'ABBkAgfFQegADFHP/65wALx8AAJnRnABCAUAAGY+cAIIBQABZjZwDAgFAAJmLnAIvHwAD2cm'
        'cApKRmYESkRmHEP6FaR0AAUEZwhwABAxIABqClJCtHwAEGXscA1M3wP8TnVI5//AQnkAAnwC'
        'QnkAAHMmQnkAAHMkSnkAAnwOZwAA2Dg8ABB6AHwAfgBD+QAAcqRCUXYAQfkAAG8kdAAyPAAg'
        'tHkAAnwOZGq2KAAaZly4fAAQZgJyADAE0EHQaAAUsHwBMGMiuHwAEGccvnwAH2QW2kZQRXwA'
        'UkcwB9BAM4UAADg8ABBgyNhBMUQADDFHAA7YaAAUvGgAFmQEPCgAFjAH0EAzhgBAMjwAEFJC'
        'QegAHGCOUkO2fAAFZQD/elJHM8cAAHMkU0feRzAxcADQcXBAUEByADQANgHWQ5RxMAC0fACg'
        'YwxSQbJ5AABzJGXmU0EzwQAAcyZM3wP/TnUvAcL8ABxB+QAAbyTRwSIfTnVI5//gQnkAAHa6'
        'QnkAAHa8Q/kAAHb0M8AAAHbAM8EAAHbCM8IAAHbEOgI8AzP8EAAAAHa+PhBB6AAUU0drblN5'
        'AAB2vmtmNBgIAgAPZgYwOQAAdsDQWAgCAA5nCggCAA1nClSIYAgyOQAAdsLSWFiIOBhhPggC'
        'AA1nClNFawZB6P/0YLoIAgAMZx4wOQAAdsBB6P/0CAIADWcE0mgABDo5AAB2xFNGapZRz/+U'
        'TN8H/051UnkAAHa6DHkCAAAAdrpiCDLAMsEyxDLCCAQADWYoCAIACmYiCAIAC2ccdgG4fIAA'
        'Zw4vCmEkNioAAsbqAAQkX9d5AAB2vE51MDkAAHa6sHwCAGMEMDwCAE51LwQkbQJSyHwA/+VM'
        'JHJAAigfTnUvBCRtAkYIBAAOZwQkbQI+yHwA/+VMJHJAACgfTnVh4CRqAAJOdUjnDzDUQNZB'
        'YdA+ElyKVUdrLCZaOBOwRG8CMAQ6KwACskVvAjIF2GsABLREbAI0BNprAAa2RWwCNgVRz//W'
        'lECWQUzfDPBOdXoADFIAAWMMOjkAAnxmitJCRUhFTnVI5wggOCkABAgEAA1mKjARwHz/8DIp'
        'AALCfP/4dBB2CLh8gABnNmEA/0A0KgAC6Uo2KgAE50tgJGEA/2AwEjIqAAI0KgAENioABko5'
        'AAB282cEYQD/TtBR0mkAAkzfBBBOdUjn/8AgSTg8f/86BDw8gAA+BkP5AAB29GEA/to/AGAi'
        'YQD/fLBEbAI4ALJFbAI6AdRAtEZvAjwC1kG2R28CPgNQiVNXatpUj7h8f/9mCHgAegB8EH4I'
        'SJAA8EzfA/9OdS8AQfkAACBswPwACtHAIB9OdS8IYeoyGOFZNBjhWjYY4Vs4GOFcOhjhXSBf'
        'SkFOdUjnfIBhyuFZMMHhWjDC4Vsww+FcMMThXTDFTN8BPk51SOf8gEJ5AAB2umG2axqyeQAC'
        'fA5kEmEA/SAgUDACMgM0BDYFYQD9JEzfAT9OdUjnfABwP2GMaghRyP/6cABgGlJAsHwAQGUS'
        'cABhAP92awpSQLB8AEBl8nD/TN8APkpATnVI5//wQnkAAnwEcAQjwAACfApCeQACfAhCeQAA'
        'dqhCeQAAdqpCeQAAdqxCeQAAdq4z/P//AAB2sH4ARfkAAHUoFbwA/3AARfkAAHVoQjJwAEX5'
        'AAB1qEIycABF+QAAdehQ8nAARfkAAHMoMAfnSEKyAABCsgAEMAdhAP7mawABNLJ5AAJ8DmQA'
        'ASo8AWEA/xBSeQACfARwADA5AAB2usD8AAjQvAAAABbRuQACfAowOQAAdrzReQACfAhD+QAA'
        'cygwB+dI0sBhAP4mMgZhAPwIRfkAAHUoECgAGBWAcACwPAABZgZSeQAAdqoiUDApAAKwfAAC'
        'ZyawfAANZzCwfAAOZ36wfAAPZ0SwfAAMZgAApAgpAAEAC2YAAJpgMFJ5AAB2qHIBMDkAAHao'
        'YD4wOQAAdqywfAAgZHpF+QAAdigVhwAAUnkAAHascgJgHjA5AAB2rrB8ACBkWkX5AAB2SBWH'
        'AABSeQAAdq5yA0X5AAB1qBWAcABF+QAAdWgVgXAAYDJF+QAAdWgVvAAEcAAwOQAAdrBqCDPH'
        'AAB2sGAWRfkAAHXoFYBwABWHAAAz/P//AAB2sFJHvnwAQGUA/oAwOQAAdqyweQAAdq5jBjA5'
        'AAB2rkH5AAB2KEP5AAB2SEX5AAB16HIAYBZ0ABQwEAB2ABYxEAAVgyAAFYIwAFJBskBl5nAA'
        'SnkAAHaoZgQIwAAADHkABAAAdqhjBAjAAAFKeQAAdqpmBAjAAAJKeQAAdrBrBAjAAAMyOQAA'
        'dqyyeQAAdq5jBAjAAAQMeQBAAAJ8CGMECMAABQy5AAAQAAACfApjBAjAAAYzwAACfAZB+QAA'
        'dSgwOQACe/5rFgwwAP8AAGYOM/z//wACe/5R+QACe/swOQACfABrEAwwAP8AAGYIM/z//wAC'
        'fABM3w//TnUvADA5AAJ8BmcWQfoO/OJIZQRYiGD4IFAgH7D8AABOdZHIIB+w/AAATnVI5//4'
        'QfkAACBsInkAAnvCMDwBPzIY4VkywVHI//ggbQJiQ/kAAIb0RfkAAAGYMDwHsiLQINpRyP/6'
        'KHkAAnu+TpQoeQACe7pOlCBtAmJD+QAAhvQwPAeyIhAkGWsGs4LUgmcGCMEAHyCBWIhRyP/q'
        'UO0B6GEA/LRM3x//TnVI5/+APgBIuQA+AAB2xmEA+/xIuQA+AAB20Ey5AD4AAHbGYQD8BmEA'
        '/IRKQWsaQfoUYAy5AAAQAAACfApiKkH6FCgwB2FEZiBhAP84UPkAAnvuUPkAAnxPUPkAAABH'
        'TN8B/wA8AAROdTAHTLkAPgAAdtBhAPu2YQD8NHAMYQDpTkzfAf8CPAD7TnVI58CAQfkAAHMo'
        '50jQwAxQABBtMgxoABAAAm0qMi0BDOlJknwAELJoAARtGjItAQ7nSZJ8ABCyaAAGbQpM3wED'
        'ADwABE51TN8BAwI8APtOdUjnMAA0ANRQtHwAEGwKMDwAH5BQwHz/8DYtAQzpS5Z8ABA0ANRo'
        'AAS0Q28UlmgABMZ8//AwAzQA1FC0fAAQbUw0AdRoAAK0fAAQbAwyPAAXkmgAAsJ8//g2LQEO'
        '50uWfAAQNAHUaAAGtENvFpZoAAbGfP/4MgM0AdRoAAK0fAAQbQpM3wAMAjwA/k51TN8ADAA8'
        'AAFOdTAtAQbQbQD+0HwAEDItAQjSbQEA0nwAEE51SOd/wDwAPgF6P0H5AAB1KAwwAP9QAGdY'
        'QfkAAHMoMAXnSNDAvFBtSLxoAARsQr5oAAJtPL5oAAZsNjAFYQD6gmEA+MI4AEP5AAB29GAe'
        'YQD5XrxAbRTUQLxCbA6+QW0K1kG+Q2wEMAVgDFCJUcz/4FHN/5hw/0zfA/5OdUjnIIAyOQAC'
        'e/xhAPdwWIhhAP9YNBDUaAAE4kKQQlBAwHz/8DQoAALUaAAG4kKSQlhBwnz/+GEA/pxM3wEE'
        'TnUzwAACe/5Q+QAAAEdOdWEA1pAzwAAAbwAz/P//AAJ8AAxtAKABCGQOYQD/AGEA/xYzwAAC'
        'fAAwOQAAbvxnEko5AAJ7+2cGSi0BvGYEYQDfJko5AAJ7+2cQSi0BvGYAAVBR+QACe/tOdUot'
        'Ab5nJkJ5AAB26jP5AABvAAAAduwMbQCgAQhlAAC+MDkAAG8AagDdwE51Si0BvGcmMDkAAG8A'
        'sHkAAHbsZhhhKGYUUnkAAHbqDHkAAwAAduplFGAA3ZJKLQHCZwowOQACfABqAAGGTnWwfAAW'
        'ZQywfAAZYgYAPAAETnUCPAD7TnVyFLA8AHBnQHIVsDwAf2c4chawPAAtZzByF7A8AD1nKLA8'
        'ACtnInIYsDwAW2cachmwPABdZxJyGrA8ACxnCnIbsDwALmcCTnUwAWEA6HK6fAADZwRgAN0m'
        'TnUwOQACfABqBmEAAMprWmEA/qw+AGEA+GwzwgAAdtozwwAAdtxhAP3AkEIzwAAAdt6SQzPB'
        'AAB24EH5AABzKDAH50jQwEP5AAB24jAYkEIywDAYkEMywDAYkEIywDAYkEMywFD5AAJ7+051'
        'DG0AoAEIZGBhAP1ykHkAAHbekHkAAHbaUEDAfP/w0HkAAHbaknkAAHbgknkAAHbcWEHCfP/4'
        '0nkAAHbcQfkAAHbiYQD8omUgPAA+ATA5AAJ7/msUYQD3wrxCZgS+Q2cINAY2B2AA+6ZOdWEA'
        '+BhrIj4AYQD9nmUgNAA2ATAHMjkAAnv8eAB6AGEA+4JmFDAHTnVB+hAyYARB+g/acAxhAOU4'
        'cP9OdT4Acv90/3b/eP96/2EA+1hR+QACe/u+eQACe/5mCDP8//8AAnv+R/kAAG6kQfoPkGEA'
        '1SgwB1JAYQDVKEH5AABupHAGYADk7DA5AAJ7/mqwTnUwOQACe/5rEmEA9xZKRmYE2EdgAtpH'
        'YAD6/E51fAB+/2DefAB+AWDYfAF+/2DSfAF+AWDMMDkAAnv+aghw/0pHagJwQHw/0EfAfAA/'
        'QfkAAHUoDDAA/wAAZgZRzv/qTnVhAPz4YAh+/2DKfgFgxkjnwIBB+QAAcyjnSNDAMBDQaAAE'
        '4kCQfACwwHz/8GoCcACweQAAbvZvBjA5AABu9jIoAALSaAAG4kGSfABgwnz/8GoCcgCyeQAA'
        'bvhvBjI5AABu+DPAAAB27jPBAAB28FD5AAB28kzfAQNOdQxtAKABCGQSSjkAAnv7ZgpKeQAC'
        'fABqAmEkYQABljA5AAJ7/msCYWowOQACfABrDLB5AAJ7/mcEYQAAik51YQD8AGVMPAA+ATI5'
        'AAJ7/GEA82wmSCBTMAYyB2EAAJpSeQACfGZhAAFMMCsABNBGkG0A/jIrAAbSR5JtAQA0KwAI'
        'lGsABDYrAAqWawAGYAABMk51SOf4QGEA9exhAPQsOABD+QAAdvRgEmEA9MiQbQD+km0BAGEA'
        'AQpQiVHM/+xM3wIfTnVI5/CAQfkAAHMo50jQwDAQMigAAjQoAASUQDYoAAaWQZBtAP6SbQEA'
        'YQAA0kzfAQ9OdUjn//h0AHYAYQDyzmEAAK5H+QAAdvRhAPO6PgBgSDgrAAQIBAANZjy4fIAA'
        'ZzZhAPO0YQD0MuVNKHJQBjwqAARTRjIrAALmQTAT6EA6KgACU0U0HGEA3yhSQFHN//ZSQVHO'
        '/+ZQi1HP/7ZH+QAAdvRhAPNgPgBgOjgrAAQIBAANZy5hAPN0YQDz3iBtAkYIBAAOZwQgbQI+'
        'yHwA/zATMisAAjQ8gAB2ACh5AAJ7Dk6UUItRz//ETN8f/051Si4AAgguAAYAAmb4TnVI5/+A'
        'SkJvNkpDbzIgbQHyOADYQlNEOgHaQ1NFPAFhJLpBZxo8BWEcPAFSRrxFbA4+AGFkuEBn8j4E'
        'YVxg7EzfAf9OdUjn+ABKRmtGvHwAwGRASkBqAnAAuHwBX28EODwBX7BEbiwyAMJ8AA90/+Jq'
        'NgCGfAAPtkRvEDIERkHCfAAPdv/ja8RDNgRhOjADUkBg0EzfAB9OdUjnoABKRmsgvHwAwGQa'
        'SkdrFr58AWBkEDAHwHwADzQ8gADgajAHYQZM3wAFTnVI51BAMgbC/AAsIkjTwTIA6EnSQdLB'
        'NgJhAN7KTN8CCk51R/kAAABMPjkAAnwAah5B+grYYQDRcjA5AAJ8BGEA0XBB+grPYQDRYGAA'
        'AV5B+grKYQDRVDAHUkBhANFUQfoKzWEA0UQwB2EA81YwAWEA0UAW/AAgQfkAAHUocAAQMHAA'
        'PABhAAEqQfkAAHVocgASMHAAQfkAAHWodAAUMHAAQfkAAHXodgAWMHAAsnwAAWcYsnwAAmdM'
        'snwAA2d2snwABGcAAJxgAAC6FvwAIDACYQDQ3rR8AARiHkH6CkxhANDIMDkAAHaosHwABGMC'
        'cARhANC+YAAAtEH6CjthANCqYAAAqBb8ACAwAlJAYQDQorY8AP9nFEH6CihhANCMMANSQGEA'
        '0IxgAACCQfoKH2EA0HhgdrY8AP9nHEH6Chu8fAAIZwRB+godYQDQXjACUkBhANBeYFRB+gof'
        'YQDQTGBKtjwA/2cSQfoKG2EA0DwwA1JAYQDQPGAyQfoKF2EA0CpgKDAHYQDyOmEA76xKKAAZ'
        'ZxhB+goKYQDQEDAEYQDQEhb8ACwwBWEA0AhCE2AAz7IvCLB8AA1iDkH6BCLlSCBwAABhAM/k'
        'IF9OdUH6CMNwB0o5AAJ7+2YAzyphAPUwZyJH+QAAdmgvCEH6CPFhAM+6IF9hAM+0QfkAAHZo'
        'cAxgAM8CQfoIVnAHYADO+Ejn+4B+ADwAvHwAGmUKSnkAAnwEZk5gSrx8ABVlRjA5AAJ7/ms8'
        'vHwAFWc4YQDxhmEA7vgUKAAZdgAwBLx8ABhlBHYBMAUHAmcYvHwAFmcOvHwAGGcIsHwAKGwG'
        'YAZKQG4CfgM6B0zfAd9OdUjn/oCwfIAEZiQwOQACe/xhAM8mFvwAIDI5AAJ7/GEA7p5wABAo'
        'ABhhAP8OYFqwfIAHZhRB+glBYQDO9jA5AAJ8DmEAzvRgQHwAFvwAV7B8gAVnCHwBF3wASP//'
        'FvwAIDA5AAJ7/mscYQDw3mEA7lANKAAZZw4wBEpGZwIwBWEAzrhgBBb8AC1M3wF/TnVKeQAC'
        'fA5nLlH5AAJ7+0J5AAJ8ZhP8AAMAAnvtQfoESiPIAAAAADP8//8AAG8AUPkAAABGTnVB+glT'
        'cApgAN48E/wAAAACe+1CeQACfGZhANbKTnUwOQACfAJnDlNAM8AAAnwCUPkAAABHTnUwOQAC'
        'fAKweQAAcyZkDlJAM8AAAnwCUPkAAABHTnVhANN0KHkAAntyTpQoeQACe35OlGEA09phANQA'
        'YQABDlJ5AAJ8ZmEYYQABaGEA3eBhAAGuYQDL2lDtActgAM/4YQDMyDPAAABvADA5AABu/LA8'
        'ABFnAP9gsDwAAWcA/2ywPAACZwD/fEotAb5nKAxtAKABCGQWYWhKQGsaM8AAAnv8UPkAAABH'
        'YAD/LDA5AABvAGoA1CZOdS8JQ/kAAHKkNCgADrR5AAJ8AmUs1EI0MSAAMjkAAnwC0kGUcRAA'
        'UEIyAtJoABayfACgYgwyKAAMIl8CPAD+TnUiXwA8AAFOdUjncIAMbQCgAQhkOEH5AABvJHAA'
        'sHkAAnwOZChhmmUcNi0BBpZBaxS2aAAUZA42LQEIlkJrBrZoABZlClJAQegAHGDQcP9M3wEO'
        'TnVhAPpuIG0B8kHoAsByAyJIMDwG30KZUcj//EHoIQBRyf/uR/kAAG8kfgC+eQACfA5kMiBL'
        'YQD/NmUi0msAENJtAP7SfAAQ1GsAEtRtAQDUfAAQMAEyAiBTYQD5WlJHR+sAHGDGTnVhAPoI'
        'MDkAAnv8YRRhAP9ASkBrCrB5AAJ7/GcCYQJOdUjn8IAyAGEA6+xhAP7aZRgwAdB8ABAyAtJ8'
        'ABA0KAAUNigAFmEA+dJM3wEPTnVH+QAAAExhAP74SkBrOjIAQfoFoGEAzCJhAMwmFvwAIBb8'
        'ACBhAOugcAAQKAAYYQD8EHAAECgAGWcO5UhB+gB+IHAAAGEAy/JCE2AAy6T//wv//wsDCwQF'
        'BwYJ////AAECAwMDAwMDAwMDAwQAAF82AABfPwAAX0QAAF9KAABfTwAAX1YAAF9fAABfZwAA'
        'X24AAF91AABfgAAAX4kAAF+QAABflAAAX5wAAF+xAABfygAAX9sAAF/3AABgDgAAYC8AAGMu'
        'AABjRQAAY2EAAgAAAC4AAQAAQlAAAELBADIAAAAuAAIAAEJYAABgZwBiAAAAIgADAABCYAAA'
        'doIAhgAAABwABAAAQmYAAH/AAMgAAAAcAAUAAEJrAAB/4ADmAAAAHAAGAABCcAAAf/kBBAAA'
        'ABwABwAAQnUAAELmASIAAAAcAAgAAEJ6AABDBQACAA0AIgAUAABgUgAAYJMAJwANAF6ABAAA'
        'AAAAAAAAAIgADQAoABUAAGBYAABgugCzAA0AGIAFAAAAAAAAAAAAzQANAAwAFgAAYF8AAGDo'
        'ANsADQAMABcAAGBhAABhBgDqAA0AGIAGAAAAAAAAAAABBAANAAwAGAAAYF8AAGEjARIADQAM'
        'ABkAAGBhAABhRgEhAA0ADgAaAABgYwAAYWgBMQANAA4AGwAAYGUAAGGQ//8AAgAAACIADgAA'
        'Qp0AAGG0ACgAAAC6gAcAAAAAAAAAAADmAAAAHAAPAABCogAARB8BBAAAACIAEAAAQqUAAEQ/'
        '//9FbnRyYW5jZQBFeGl0AFdhdGVyAFRyYXAASGF6YXJkAExhdW5jaGVyAEJvdW5jZXIAU3dp'
        'dGNoAFRhcmdldABUZWxlcG9ydGVyAFN3aW5naW5nAERldmljZQBJY2UAU2NlbmVyeQB0aGVy'
        'ZSBpcyBubyBlbnRyYW5jZQBvbmx5IGZvdXIgZW50cmFuY2VzIHdvcmsAdGhlcmUgaXMgbm8g'
        'ZXhpdABhIHRlbGVwb3J0ZXIgaGFzIG5vIHBhcnRuZXIAYSBzd2l0Y2ggaGFzIG5vIHRhcmdl'
        'dAB0cmFwcyBhbmQgZGV2aWNlcyBvdmVyIHRoZSBsaW1pdAB0b28gbWFueSBvYmplY3QgcGFy'
        'dHMgZm9yIHRoZSBnYW1lAFR5cGVzAERlbGV0ZQAtACsAPAA+AE9iamVjdHM6IHBsYWNlLCBt'
        'b3ZlIGFuZCBkZWxldGUgb2JqZWN0cyAoTykAQ2hvb3NlIHRoZSB0eXBlIG9mIG9iamVjdCB0'
        'byBwbGFjZSAoUCkARGVsZXRlIHRoZSBzZWxlY3RlZCBvYmplY3QgKERlbCwgcmlnaHQgY2xp'
        'Y2spAEZld2VyIGNvcGllcyBzaWRlIGJ5IHNpZGUgKC0pAE1vcmUgY29waWVzIHNpZGUgYnkg'
        'c2lkZSAoKykARmV3ZXIgY29waWVzIG9uZSB1bmRlciBhbm90aGVyIChbKQBNb3JlIGNvcGll'
        'cyBvbmUgdW5kZXIgYW5vdGhlciAoXSkAU2VsZWN0IHRoZSBwcmV2aW91cyBvYmplY3QgaW4g'
        'b3JkZXIgKCwpAFNlbGVjdCB0aGUgbmV4dCBvYmplY3QgaW4gb3JkZXIgKC4pAEJhY2sgdG8g'
        'dGhlIGxldmVsLCB0aGUgdHlwZSBhcyBpdCB3YXMgKEVzYykAQ2xpY2s6IHBsYWNlL3NlbGVj'
        'dCAgRHJhZzogbW92ZSAgUmlnaHQgY2xpY2s6IGRlbGV0ZQBSZWxlYXNlIHRoZSBidXR0b24g'
        'dG8gcHV0IHRoZSBvYmplY3QgZG93bgBDbGljazogcGxhY2Ugb2JqZWN0cyBvZiB0aGlzIHR5'
        'cGUAV2FybmluZzogAFNhdmUgKFMpOyB3YXJuaW5nOiAAU2F2ZWQ7IHdhcm5pbmc6IABPYmpl'
        'Y3RzIAAgb2YgNjQAT2JqZWN0IABUeXBlIAAgb2YgACAgVHlwZSAALCBub3QgdXNlZAAsIHRv'
        'Z2dsZXMgACwgbm8gdGFyZ2V0ACBvZiBzd2l0Y2ggACwgdGFyZ2V0IG9mIHN3aXRjaCAALCBu'
        'byBzd2l0Y2gALCBwYWlycyB3aXRoIAAsIG5vIHBhcnRuZXIAICBSZXBlYXQgACAgcmVwZWF0'
        'cyBzaWRlIGJ5IHNpZGUAICByZXBlYXRzIG9uZSB1bmRlciBhbm90aGVyACAgcmVwZWF0cyBi'
        'b3RoIHdheXMAT2JqZWN0IHR5cGVzIG9mIHRoaXMgc3R5bGU6IABEZWxldGVkIG9iamVjdCAA'
        'Tm8gcm9vbTogdGhlIG9iamVjdCB3b3VsZCBsZWF2ZSB0aGUgbWFwAE5vIHJvb206IHRoZSBn'
        'YW1lJ3Mgb2JqZWN0IG1lbW9yeSBpcyBmdWxsAEFsbCA2NCBwbGFjZXMgZm9yIG9iamVjdHMg'
        'YXJlIHVzZWQAVGhpcyBzdHlsZSBoYXMgbm8gb2JqZWN0cwAAYQDD7DPAAABvADA5AABu/GcE'
        'YQDMrkotAb5nLkJ5AAB26jP5AABvAAAAduwyLQEIsnwAoGVAsnwAymUAAZ4wOQAAbwBqAMtY'
        'TnVKLQG8ZyYwOQAAbwCweQAAduxmGGEYZhRSeQAAduoMeQADAAB26mUEYADLKk51sHwAH2cS'
        'sHwAIGcMsHwAJGUMsHwAKWIGADwABE51AjwA+051sDwAdmYWMDwAIzI5AABu/rI8AGFkPDA8'
        'AC1gNjI8ACewPAByZwoyPAApsDwAZ2YSMAEyOQAAbv6yPABhZBRTQGAQQfoAHjIYZxY0GLAB'
        'ZvYwAmEA1ga6fAADZwRgAMq6TnUAcAAdAG4AHAB/AB4ALQAfAD0AIAArACAALAAhAC4AIgBb'
        'ACQAXQAlAACwfAAcZwAHRLB8AB1nAAiEsHwAHmcAAbywfAAfZwABRLB8ACBnAAFAsHwAIWcA'
        'APqwfAAiZwAA+LB8ACNnAAQ4sHwALWcABVawfAAkZwADNrB8ACVnAAMysHwAJmcAA8qwfAAn'
        'ZwADxrB8AChnAAPMsHwAKWcAA8iwfAAqZwAHRLB8ACtnAAcwsHwALmcABaCwfAAvZwAFtLB8'
        'ADBnAAXIsHwAMWcABkiwfAAyZwAHCE51MC0BBrB8AQBkCOpIYQZnAmBATnVB+QAAAVDQwNDA'
        'YQRKQU51cgASKAAB4UkSEE51PwEQgeBJEUEAATIfTnVQ+QACe+5Q+QACfE9Q+QAAAEdOdTPA'
        'AAJ8EFD5AAAAR0jn//AwOQACfBAoeQACe85OlEzfD/9OdWEKathOdWEWatJOdTA5AAJ8EFNA'
        'awRhhmf4SkBOdTA5AAJ8EFJAsHwACGQKYQD/cGfySkBOdXD/TnV+/2ACfgEwOQACfBBhAP9W'
        'Z1xB+QAAAWByABIwAADSR0pHahCyfAABbUSyfABjYwpyY2AGsnwAY240EYEAACB5AAJ7QkHo'
        'ACg0ANRCMYEgAEHtAWQxgSAASOf/8MFBKHkAAnvSTpRM3w//YAD/Ik51MDkAAnwQYQD+7GdW'
        'QfkAAAFQQ/kAAAFgMgDSQdDB0sByBpJAaxAQ6AACEOgAAhLpAAFRyf/yQlBCETA5AAJ8EGEA'
        '/rJmCkpAZwZTeQACfBBhAACKQfoTo3AGYQDRfmAA/r5OdUjn//AkeQACe0JB+QAAATgiSnAX'
        'EthRyP/8cAAQOQAAAWgVQAA4O0ABdhA5AAABahVAADk7QAF4QfkAAAFuQ+oAPnAHYQD+WjLB'
        'VIhRyP/2MDkAAnwQYQD+OGYGU0Bq9nAAM8AAAnwQUO0B2yh5AAJ71k6UTN8P/0jn//BB+QAA'
        'AVBD+QAAAWAkeQACe0JH7QFkcABhAP4KNYEAGHIAEhk1gQAoN4EAAFSIVECwfAAQZeIoeQAC'
        'e8pOlEzfD/9gAP4aSOeweHAANjwAMxIoAGaCKABnZgJ2BkPoACxF6AA8JkkoSnQHYS6yQ2YE'
        'MAFgCBbRFukAARjSVIlSilHK/+i3yWcIQhtCG0IcYPQyAEzfHg1KQU51cgASKQAB4UkSEU51'
        'MjkAAKX0ZyJCeQAApfRB+hKMsnwABmcEQfoSs3AMYQDQNDP8AHgAAG8ETnV+/2ACfgFhAACE'
        'NABIwID8AA9KR2sEUkBgCiIASEFKQWYCU0DA/AAPsHwAD2wCcA+wfAJJbwQwPAJJSkdrBrBC'
        'b0hgBLBCbEJIwID8ADwTwAAAAWggeQACe0IRQAA4O0ABdkhAE8AAAAFqEUAAOTtAAXhI5//w'
        'UO0B2yh5AAJ71k6UTN8P/2AA/OROdXAAEDkAAAFowPwAPHIAEjkAAAFq0EFOdX7/YAJ+AUH5'
        'AAABfHQUdkxgEH7/YAJ+AUH5AAABenQ7dkphAPyK0kdrIkpHawayQmIaYAayQmMCMgJhAPx+'
        'IHkAAntCMYEwAGAA/H5OdSw5AAABci45AAABdkP5AAABbiR5AAJ7QkXqAD44LQD+OjkAAG72'
        'YS44LQEAOjkAAG74YSJB+hBOvLkAAAFyZgi+uQAAAXZnBEH6EF5wC2EAzuZgAPwmIEkyBGEA'
        '/BBB6QAEYQD7/LJEbgowBJBBwHwAD2cKMgTCfAAPYQD78DVBAARB6QAIYQD72LJEbQowAZBE'
        'wHwAD2cOMgWSRMJ8//DSRGEA+8g1QQAINIRUiVSKTnVD+QAApfphVkH5AACl+jAQMigAAjQ8'
        'AUA2PACgYSphAMtEMCgABDIoAAY0KAAIlEDUfAFAxHz/8DYoAAqWQdZ8AKBhBGAAzJiQbQD+'
        '0HwAEMB8//CSbQEA0nwAEE51QfkAAAFucAVhAPtGMsFUiFHI//ZOdUP5AAJ8WGHiE/wABQAC'
        'e+1B+gqYI8gAAAAAUfkAAABLM/z//wAAbwBQ+QAAAEZQ+QAAAEdOdWEAvPIzwAAAbwAwOQAA'
        'bvxnLnIxsDwADWcgcjKwPAARZxhyLrA8AHRnEHIvsDwAYmcIcjCwPAB3ZgYwAWAAxHxKLQG+'
        'ZwowOQAAbwBqAMRWTnVB+QACfFhgAP8KQfkAAnxYOC0A/mFYVIg4LQEAYVBQ+QAAAEdOdUH5'
        'AAJ8WDgtAP5hWFSIOC0BAGFQUPkAAABHTnVB+QACfFhCaAAEMXkAAG72AAhhUlSIQmgABDF5'
        'AABu+AAIYUJQ+QAAAEdOdTFEAAQyKAAIskRsAjIEkkTCfP/w0kQxQQAIYB4xRAAIMigABLJE'
        'bwIyBDQElEHEfP/wMgSSQjFBAAQyEDQoAASyQmwCMgKyaAAIbwQyKAAIkkLCfP/w0kIwgU51'
        'Q/kAAnxYQfkAAAFuJHkAAntCReoAPnQAdgBwBWEA+cqyUWcQdAGwfAAEZQJ2ATIRYQD5wjTB'
        'VIhUiVHI/+BKQmcAAIZB+g4ZSkNnBEH6DkZwC2EAzGphAPmqYGxB+QAAAThD+QAApdhwFxIY'
        'sjwAIGUMsjwAemIGsjwAI2YCciASwVHI/+ZB+QAApdhwGAwwACAA/2YEU0Bm9BPAAACl8BP8'
        'AAQAAnvtQfoIfCPIAAAAAFH5AAAASzP8//8AAG8AUPkAAABGTnUT/AAAAAJ77WAAxIxwABA5'
        'AACl8EH5AACl2HIXsEFiChG8ACAQAFHJ//RD+QAAATgkeQACe0J0AHIXEBiwEWcCdAESwBTA'
        'Ucn/8kpCZ7JhAPjqYKxhALq6M8AAAG8AMDkAAG7+Z2SwPAANZ6CwPAARZ46wPAAIZz6wPAB/'
        'ZziwPAAgZUawPAB6YkCwPAAjZzpyABI5AACl8LJ8ABhkLEH5AACl2BGAEABSOQAApfBQ+QAA'
        'AEdgFEo5AACl8GcMUzkAAKXwUPkAAABHSi0BvmcKMDkAAG8AagDB6E51UPkAAnwXTnVR+QAC'
        'fBcz7QD+AACl9jPtAQAAAKX4YQC+bmEAvvYreQACe5oCIjt8AMkBVhP8AAUAAnvhYQCr0GEA'
        'At5wByh5AAJ69k6UYU5KOQAApfFmBmEAAlxgCkH6DL1wBmEAyrRhAKuOUPkAAnwWQfkAAAEk'
        'Q/kAAs00YQCbpmEAq5RB+QAAAYphAPe2MAFhAJwyLzkAAnsWTnUkeQACerrV/AABYZxB+gF4'
        'JUgAAiR5AAJ6utX8AAFhtjS8TnUkeQACerrV/AABZHhB+gKGJUgAAiJ5AAJ6utP8AAFkRDL8'
        'Trki/AAAcEgyvE5xInkAAnq60/wAAWNYMvxOuSL8AABwbjK8TnEieQACerrT/AABY/oy/E65'
        'IvwAAHB+MrxOcUH5AAABimEA9xhKQVf5AACl8mEAAgphAADYMXwABAAiUfkAAKXxQi0Bwih5'
        'AAJ7xk6UJHkAAnq6IArQvAAAE4rV/AABYZwlQAACJHkAAnq61fwAAWG2NLwgeSR5AAJ6uiAK'
        '0LwAAWSG1fwAAWR4JUAAAiR5AAJ6utX8AAFkRCT8YQCmdiS8BkAAICR5AAJ6utX8AAFjWCT8'
        'UkAvACS8Q+0BoCR5AAJ6uiAK0LwAAcEM1fwAAWP6NPxSQDT8QfkkgGEAAVxhKjF8AAUAIih5'
        'AAJ72k6UIHkAAnq+QegFREJoAAJCaAAGQmgACkJoAA5OdSB5AAJ6utH8AAHBBCBQTnVI5+DI'
        'KHkAAnuOTpR0AUotAcJmECh5AAJ7gk6UsDwAEWcCdABKQkzfEwdmAk51UPkAAKXxWI9OdUjn'
        'BAhKOQAApfJnCLp8AAVmAnoyKHkAAnsOTpRM3xAg0HwAIE51UkBhHiJfLwAvCUPtAaBOdVJA'
        'YQ4geQACerrR/AABwQxOdUo5AACl8mcIsHwABmYCcDNOdUH5AAABUEP5AAClwHAXEthRyP/8'
        'Re0BoEH5AAABUEf5AAABYH4HMhphAPVwVIh0CkP5AAClwEn5AACl0HYHeAAYKQAB4UwYEVSJ'
        'uEFmBkoUZwIUFFKMUcv/5hbCUc//yEJ5AAJ8EGAA9UAgeQACe1YwGLB8//9nErB8AYBlCLB8'
        'Ab5iAkJQVIhg5k51SOfA4CR5AAJ6tk6qACBM3wcDTnUHBwBEoGQFCAFDaG9vc2UgdGhlIDgg'
        'c2tpbGxzIG9mIHRoZSBsZXZlbC4HAEqgZAUIAVJpZ2h0IGJ1dHRvbiBvciBFc2M6IGtlZXAg'
        'dGhlIG9sZCBvbmVzLgBB+ggrMi0BCLJ8AKBlDkH6CICyfADKZQRB+tSGcAdgALbMLwAwOQAC'
        'fBBhAPRYZxBB+QAAAWByABIwAAACPAD7TN8AAU51SOf7gH4APAC8fAAeZ068fAAfZ1a8fAAg'
        'Z168fAAhZ2a8fAAiZ2i8fAAkZ2q8fAAlZ3B0FEH5AAABfLx8ACZnbrx8ACdncnQ7QfkAAAF6'
        'vHwAKGdavHwAKWdeYGgwOQACfBBhAPPaZ1pgWmEA/3BnUrJ8AAFjTGBMYQD/YmdEsnwAY2Q+'
        'YD5hAPQkazZgNmEA9C5rLmAuYQD28LB8AA9jImAiYQD25LB8AklkFmAWYQDznkpBZwxgDGEA'
        '85SyQmQCYAJ+AzoHTN8B3051SOfggLB8gAhmIEH6A4xhALZwYQD+/GcKMAFhALZsYAAA5hb8'
        'AC1gAADesHyACWYyQfoDbWEAtkpwABA5AAABaGEAtkYW/AA6cAAQOQAAAWqwfAAKZAQW/AAw'
        'YQC2LGAAAKawfIAKZhBB+gM7YQC2EkH5AAABfGAUsHyAC2YaQfoDK2EAtfxB+QAAAXphAPL0'
        'MAFhALX0YG6wfIANZkZB+gMZYQC13EH5AAJ8XHIQdBBhGkH6AxthALXIQfkAAnxgMjwBTzQ8'
        'AK9hAmA6MBjQQehIYQC1tBb8ACwwENBC5khgALWmQfoCy2EAtZZB+QAApdhwABA5AACl8GAC'
        'FthRyP/8FvwAX0ITTN8BB051AAIAAAAuAAEAAEJQAABCwQAyAAAALgACAABCWAAAYGcAYgAA'
        'ACIAAwAAQmAAAHaCAIYAAAAcAAQAAEJmAAB/wADIAAAAHAAFAABCawAAf+AA5gAAABwABgAA'
        'QnAAAH/5AQQAAAAcAAcAAEJ1AABC5gEiAAAAHAAIAABCegAAQwUAAgANACIAHAAAdgIAAHay'
        'ACcADQAoAB0AAHYIAAB2zQBSAA0AKAAeAAB2DwAAdvgAfQANADSACAAAAAAAAAAAALMADQAM'
        'AB8AAGBfAAB3GADBAA0ADAAgAABgYQAAdzgA0AANAA4AIQAAYGMAAHdXAOAADQAOACIAAGBl'
        'AAB3eADxAA0AIgAjAAB2FgAAd5oBFQANACgALQAAdhwAAHe9AAIAGgA6gAkAAAAAAAAAAAA+'
        'ABoADAAkAABgXwAAeLAATAAaAAwAJQAAYGEAAHjEAFwAGgAugAoAAAAAAAAAAACMABoADAAm'
        'AABgXwAAeNgAmgAaAAwAJwAAYGEAAHkAAKoAGgAugAsAAAAAAAAAAADaABoADAAoAABgXwAA'
        'eR0A6AAaAAwAKQAAYGEAAHlF//8ABAAAATiADAAAAAAAAAAAAFgADQAiACoAAHZDAAB5ZgCA'
        'AA0ALgArAABCsgAAeX7//wAEAAABOIANAAAAAAAAAAAABAANADQALgAAdiMAAHfyADoADQBM'
        'AC8AAHYsAAB4IQCIAA0AOgAwAAB2OQAAeFMA3AANACIAMQAAdkMAAHh8AQQADQAuADIAAEKy'
        'AAB4lv//VGl0bGUAU2tpbGxzAFJlbW92ZQBTdGFydABMaW1pdHMAVG9wIGxlZnQAQm90dG9t'
        'IHJpZ2h0AFdob2xlIG1hcABPSwBDb3VudCAAVGltZSAAUmF0ZSAATG9zdCAAVGl0bGU6IABT'
        'Y3JvbGwgbGltaXRzOiBjZWxscyAAIHRvIABQYXJhbWV0ZXJzOiB0aXRsZSwgc2tpbGxzLCB0'
        'aW1lIGFuZCBncmFkaW5nIChMKQBUeXBlIHRoZSBsZXZlbCdzIHRpdGxlIChOKQBDaG9vc2Ug'
        'OCBza2lsbHMgd2l0aCB0aGUgZ2FtZSdzIHBpY2tlciAoUCkAUmVtb3ZlIHRoZSBzZWxlY3Rl'
        'ZCBza2lsbCAoRGVsKQBGZXdlciBvZiB0aGUgc2VsZWN0ZWQgc2tpbGwgKC0pAE1vcmUgb2Yg'
        'dGhlIHNlbGVjdGVkIHNraWxsICgrKQBTZWxlY3QgdGhlIHNraWxsIHRvIHRoZSBsZWZ0ICgs'
        'KQBTZWxlY3QgdGhlIHNraWxsIHRvIHRoZSByaWdodCAoLikAU3RhcnQgdGhlIGxldmVsIHdp'
        'dGggdGhpcyB2aWV3IChWKQBMaW1pdCB0aGUgc2Nyb2xsaW5nIGFuZCB0aGUgbGVtbWluZ3Mn'
        'IGFyZWEgKFNoaWZ0K1YpAFRoZSBsZXZlbCBzY3JvbGxzIHVwIGFuZCBsZWZ0IHRvIHRoaXMg'
        'dmlldyAoVCkAVGhlIGxldmVsIHNjcm9sbHMgZG93biBhbmQgcmlnaHQgdG8gdGhpcyB2aWV3'
        'IChCKQBUaGUgbGV2ZWwgc2Nyb2xscyBvdmVyIHRoZSB3aG9sZSBtYXAgKFcpAFVzZSB0aGVz'
        'ZSBsaW1pdHMgKFJldHVybikAS2VlcCB0aGUgb2xkIGxpbWl0cyAoRXNjKQAxNSBzZWNvbmRz'
        'IGxlc3MgKFspADE1IHNlY29uZHMgbW9yZSAoXSkATGVtbWluZ3MgY29tZSBvdXQgbW9yZSBz'
        'bG93bHkgKFNoaWZ0K1IpAExlbW1pbmdzIGNvbWUgb3V0IGZhc3RlciAoUikAQmVzdCBncmFk'
        'ZTogZmV3ZXIgbWF5IGJlIGxvc3QgKFNoaWZ0K0cpAEJlc3QgZ3JhZGU6IG1vcmUgbWF5IGJl'
        'IGxvc3QgKEcpAFVzZSB0aGlzIHRpdGxlIChSZXR1cm4pAEtlZXAgdGhlIG9sZCB0aXRsZSAo'
        'RXNjKQBUeXBlIHRoZSB0aXRsZSAgIEJhY2tzcGFjZTogZGVsZXRlICAgUmV0dXJuOiBkb25l'
        'AEZyYW1lOiBzdGFydCB2aWV3IChWKS4gRG90dGVkOiBsaW1pdHMgKFNoaWZ0K1YpAFNjcm9s'
        'bCB0aGUgdmlldywgdGhlbiBzZXQgVG9wIGxlZnQgb3IgQm90dG9tIHJpZ2h0AENsaWNrIGEg'
        'c2tpbGwgaW4gdGhlIHBhbmVsIHRvIHNlbGVjdCBpdABUaGUgbGV2ZWwgbm93IHN0YXJ0cyB3'
        'aXRoIHRoaXMgdmlldwBTdGFydCB2aWV3IHNldDsgdGhlIHNjcm9sbCBsaW1pdHMgd2VyZSB3'
        'aWRlbmVkAExpbWl0cyBzZXQ7IGxlbW1pbmdzIHRoYXQgbGVhdmUgdGhlIGRvdHRlZCBmcmFt'
        'ZSBkaWUATGltaXRzIHNldDsgdGhlIHN0YXJ0IHZpZXcgbW92ZWQgaW5zaWRlIHRoZW0AVGhl'
        'IHNraWxscyBhcmUgYXMgdGhleSB3ZXJlAFNraWxsIHJlbW92ZWQ7IHRoZSBsYXRlciBvbmVz'
        'IG1vdmVkIGxlZnQAQXR0cmFjdG9yIHJlbW92ZWQ6IGl0IGZhaWxzIGluIHRoZSBDbGFzc2lj'
        'IHN0eWxlAEJsb2NrZXIgcmVtb3ZlZDogaXQgd29ya3Mgb25seSBpbiB0aGUgQ2xhc3NpYyBz'
        'dHlsZQAAQnkAAnxQQnkAAnxSQrkAAOmWUfkAAnxPQfkAAAEkQ/kAAKYGYQCOOEH5AAABJEP5'
        'AADHzmAAjijlSEX5AADpliAyAABF+QAA6hrVwE51MDwIcbOIVsj//E51QfkAAAEkQ/kAAMfO'
        'YeZW+QACe+5OdUo5AAJ8T2cAAKhKLQG8ZgAAoEotAcBmAACYSi0Cr2YAAJBKOQACfE9nAACG'
        'UfkAAnxPQfkAAKYGQ/kAAAEkYZ5nZDP5AAJ8UgACfFAMeQAgAAJ8UGQSMDkAAnxQYQD/arC8'
        'AAFeKGMEYUhg4GEAAJIwOQACfFBSQDPAAAJ8UDPAAAJ8UuVIQfkAAOmWlfwAAOoaIYoAAEH5'
        'AAABJEP5AACmBmEAjUphAP9CUPkAAABHTnUiOQAA6ZowOQACfFBhAP8IkIFD+QAA6hpB8RgA'
        '5IhgAiLYU4Bq+kH5AADpljA5AAJ8UFNAJCgABJSBIMJRyP/2U3kAAnxQU3kAAnxSTnVB+QAA'
        'pgZD+QAAASRyALJ8CHJkRCQYJhlSQbaCZ/BTQTTBJkpCWngAegC1gyTDUkRSRUqDZwJ6AFJB'
        'snwIcmQMunwAA2QGJBgmGWDemEU2hNpF2kWUxWC2JPz//wAATnVhAP5mMhqyfP//ZyI0GuVJ'
        'QfkAAAEk0MFD+QAApgbSwVNCJhq3mLeZUcr/+GDWTnVKLQG8ZgD/Ggx5AFUAAG7+Zx5hAP5+'
        'MDkAAnxSZwD/AlNAM8AAAnxSYaZB+gKHYCBhAP5gMDkAAnxSsHkAAnxQZAD+3mGKUnkAAnxS'
        'QfoCbC8IYQD+BmEA0LBhAOmAUPkAAABHIF9wBmAAuuiwfAAFZhJKOQACfE9mIkp5AAJ8UmYa'
        'YBZKOQACfE9mDjI5AAJ8UrJ5AAJ8UGUCegNOdWEA0D5nLi8IE/wAAQACfFdB+gEqYQC6Mkf5'
        'AABuLEH64+9hAKq4IF9hAKqyQfoBvWAAqqoMOQACAAJ77WYEYQC5/FD5AAJ8VU51UfkAAnxV'
        'M+0A/gAApfYz7QEAAACl+GEArcZhAK5OK3kAAnuaAiIoeQACe5JOlDt8AMkBVkI5AAJ74VH5'
        'AAJ77FD5AAJ8VEH5AAABJEP5AALNNGEAiyJhAJsQQfkAAAGKYQDnMjABYQCLri85AAJ7Fk51'
        'SkBn0FH5AAJ8VLB8AAJnEEo5AAJ77mcAiVpQ+QACfFZQ+QACe+xgAO8iSjkAAnxUZhIvOQAC'
        'ex4gLQJesLwAAAAITnUgLQJesLwAAAAIby4geQACe0oieQACer5D6QA0KHkAAnr6TpQreQAC'
        'e5oCIih5AAJ7kk6UWI9wAmCCTnUABAAAATiAAgAAAAAAAAAAAFgADQAiACwAAEJmAACAGgCA'
        'AA0ALgATAABCsgAARLf//1BsYXkgdGhlIGxldmVsIGFzIGl0IGlzIG5vdyAoRSkAVW5kbyB0'
        'aGUgbGFzdCBjaGFuZ2UgKFUpAFJlZG8gdGhlIGNoYW5nZSB1bmRvbmUgKFNoaWZ0K1UpAFRl'
        'c3QgcGxheSBpdCBhbGwgdGhlIHNhbWUgKFJldHVybikALiBUZXN0PwBSZXR1cm46IHRlc3Qg'
        'ICAgRXNjOiBrZWVwIGVkaXRpbmcAVW5kb25lAFJlZG9uZQAAI8gAAmoeI8kAAmoiM8AAAmou'
        'M/z//wACajBCuQACaipCeQACajJCbQKuCDkABgC/4AFn9ih5AAJ7fk6UYQRgAAHoJHkAAmoe'
        'fABKUmsKYWJF6gAQUkZg8mEAmVwkeQACah5KUmsKYQAApkXqABBg8mAAmn4yOQACai6xQWcy'
        'M8AAAmouJHkAAmoefABKUmsgDQFnFEjnQiBhGGEAmRphbmEAmk5M3wRCReoAEFJGYNxOdUjn'
        '/+B4Hnoffh0wOQACai4NAGcGeBx6HX4PTJIABzwCdhJhAAHaOAV2AWEAAdJ0AXYSYQAByjgH'
        '0EZTQFJBdhFhAAG8TJIAB1JA0nwAEVNCdgFhAAGqTN8H/051FvwABzAS4kgWwDAqAAJYQOJI'
        'FsAwEtBqAATiSBbAFvwAZBb8AAUW/AAIQhsgagAIYACY1Ch5AAJ7jk6UKHkAAnt+TpRhAK08'
        'MC0BBjItAQhhejPAAAJqMGEAAMAyOQAAbvxnJCR5AAJqHnAASlJrDrJqAAZnNkXqABBSQGDu'
        'MjkAAG7+cP1OdXD8Si0BwmYacP9KLQG+ZxIwOQACajBqDHD+Mi0BBjQtAQhOdTI5AAJqLgEB'
        'ZhBCeQACajI/AGEAl9gwH051MgBw+051JHkAAmoedAA2EmsosENlHNZqAASwQ2QUNioAArJD'
        'ZQzWfAASskNkBDACTnVF6gAQUkJg1HD/TnUjyAACaiYz/ACWAAJqMkK5AAJqKk51SnkAAmoy'
        'ZxBTeQACajIgeQACaiZ0AGAcIHkAAmoiMDkAAmowawwieQACah7pSCBxAAx0AbH5AAJqKmdK'
        'I8gAAmoqSOcggHAAMjwAuDQ8AUB2DCh5AAJ7Bk6UTN8BBGEAly4W/AAHQhsW/ABcFvwAoBb8'
        'AGQW/AAFFvwACBbCYQCXbGAAmEROdUjn/+AgeQACahrC/AAo0cEyAOZJ0ME6ANpCU0U+BeZP'
        'nkHAfAAHcv/gKcp8AAdwB5BFdP/hKkpHZgLCAnwEIkg6A1NFJEkIBAAAZxpKR2YEgxJgMoMa'
        'MAdVQGsGUNpRyP/8hRJgIEYBRgJKR2YEwxJgEMMaMAdVQGsGUdpRyP/8xRJGAUYCQ+kAKFHN'
        '/7hB6B9A4kxRzv+oTN8H/051KHkAAnsCTpRhAJZeQfoErjI8AABhAJauYQAAikH6BNEyPABg'
        'YQCWnmEAl3hB+gRKQ/oE2HAAYQD8ehP8AAYAAnvhYQD9sLB8//xnBkpAa+pnCkI5AAJ74ZHI'
        'TnVCOQACe+FhAJXcYQADuGEAAJBB+gVMSkBrIEf5AAJqdkH6BTVhAKToQfkAAnx7YQCk3kIT'
        'QfkAAmp2LwhhAIsiYQCVmCBfTnVB+ppsMjwAMGEAkx5B+gQrMjwAQGEAkxIyPAAwYQCTFjA5'
        'AAJ75GEAjD5B0nQfNjwAzmEAljYyPABAYQCS+EH6BANKKgA8ZwCV2kHqACB0GDY8AM5gAJYU'
        'SOd/fiR5AAJ6tkH5AAJ8dE6qAFhhAANcQfkAAnx0TqoAJEqAZkZH+QACarY+OQACajRgFEH5'
        'AAJ8eyJLYQCM7kpAZyRH6wAgUc//6gx5AIAAAmo0ZBIiS0H5AAJ8exLYZvxSeQACajRwAGAC'
        'cP9M337+TnUyOQACajRnIkP5AAJqtlNBIExI50BAYQCMoEzfAgJKQGcMQ+kAIFHJ/+iwAE51'
        'IExD+QACfHRhAAKGSOcAICR5AAJ6tkH5AAJ8dE6qACQkX0qAV8BKAE51MDkAAnvkYQCLOkPS'
        'RfkAAnwacgAQGbA8AC5mBkopAANnFGEAkDBmDLJ8ABRkBhTAUkFg4HIAE8EAAnwYQrkAAnxK'
        'KHkAAnsCTpRhAJRUQfoCsTI8AABhAJSkYQD+gEH6ArsyPABYYQCRnGEAlW5hUkH6AmBD+gLo'
        'cABhAPpuE/wABwACe+FhAPuksHz//GcosHz//WYSMAFhAI90Z+BCuQACfEphHGDWSkBr0mYK'
        'YUxKQGoGYQxgxpHIQjkAAnvhTnUwPABwMjwAWDQ8ANB2DCh5AAJ7Bk6UcAAyPAB0NDwBQHYM'
        'KHkAAnsGTpRhAJOyMjwAWGEAkOZgAJDIQfqYlko5AAJ8GGcAAUZhAJHEMDkAAnvkYQCKLEHS'
        'Q/kAAnwwYQCLPkH6AvhKQGcAASJhAJHGQfqYnL55AAJ74mUAARBB+QACfDBD+QACfHRhAAEY'
        'JHkAAnq2QfkAAnx0TqoAJEH6mG5KgGYAAOZhAADsQfkAAnx0Q/kAAmo2Ethm/CR5AAJ6tkH5'
        'AAJqNk6qACQuAEH6Aqu+vAABgABiAACyLwdhAJLWLh8keQACerZKh2cQQfkAAmo2Q/kAAOoa'
        'TqoACEH5AAJ8MEP5AAJ8dGEAAJggB0H5AAJ8dEP5AADqGk6qAAxhAADCQfkAAnx0TqoAJLCH'
        'ZlJB+QACajZD+QACfHQS2Gb8YQD9LkH6AntKQGsgR/kAAmp2QfoB+mEAoYZB+QACfDBhAKF8'
        'QhNB+QACanYvCGEAh8BhAJC+YUJhAJIwIF9wAE51YQCSJkH6AhcjyAACfEpw/051MDkAAnvk'
        'YQCI4mAAieAvCEH6lMQS2Gb8E3wAL///IF8S2Gb8TnW+eQACe+JlCD45AAJ74lNHM8cAAnvk'
        'aw5wADAHgPwACTPAAAJ75k51Qq0CqkJtAq5OdQAIAKIAYAANAABgWAAAiQgA2ACiAGAAEQAA'
        'HqgAAIkq//8ACACiAGAADQAAiJoAAIk+ANgAogBgABEAAB6oAACJX///RGVsZXRlIExldmVs'
        'AFJlbmFtZSBMZXZlbABSZW5hbWUAVGl0bGUATmV3AGRhbWFnZWQARGVsZXRpbmcgY2Fubm90'
        'IGJlIHVuZG9uZS4AUmV0dXJuOiBkZWxldGUgICAgRXNjOiBrZWVwAFR5cGUgdGhlIG5ldyBu'
        'YW1lIG9mIHRoZSBmaWxlAERlbGV0ZSB0aGUgZmlsZSBmb3IgZ29vZCAoUmV0dXJuKQBLZWVw'
        'IHRoZSBmaWxlIChFc2MpAEdpdmUgdGhlIGZpbGUgdGhpcyBuYW1lIChSZXR1cm4pAEtlZXAg'
        'dGhlIG9sZCBuYW1lIChFc2MpAERlbGV0ZWQgAFRoZSBmaWxlIGNvdWxkIG5vdCBiZSBkZWxl'
        'dGVkAFJlbmFtZWQgdG8gAFRoZSBmaWxlIGhhcyB0aGlzIG5hbWUgYWxyZWFkeQBUaGlzIGZp'
        'bGUgaXMgdG9vIGxhcmdlIHRvIHJlbmFtZSBoZXJlAFRoZSBuZXcgZmlsZSBjb3VsZCBub3Qg'
        'YmUgd3JpdHRlbgBDb3BpZWQsIGJ1dCB0aGUgb2xkIGZpbGUgaXMgc3RpbGwgdGhlcmUAAE5x'
        'AAAD7AAAAM8AAAAAAAAHHAAABzYAAAdOAAAHZgAAB34AAAeWAAAHsAAAB8gAAAfgAAAH+AAA'
        'DtIAAA7WAAAO4gAADuYAAA7yAAAO9gAADwIAAA8GAAAPEgAADxYAAA8iAAAPJgAADzQAAA84'
        'AAAPRAAAD0gAAA9UAAAPWAAAD2YAAA9qAAAPdgAAD3oAAEDyAABA9gAAQQIAAEEGAABBEgAA'
        'QRYAAEEiAABBJgAAQTIAAEE2AABBQgAAQUYAAEFSAABBVgAAQWIAAEFmAABBcgAAQXYAAEGS'
        'AABBlgAAQaIAAEGmAABBsgAAQbYAAEHCAABBxgAAQdQAAEHYAABB5AAAQegAAEH0AABB+AAA'
        'QiYAAEIqAABCNgAAQjoAAEJGAABCSgAAXWIAAF1mAABdagAAXW4AAF1yAABddgAAXXoAAF1+'
        'AABdggAAXYYAAF2KAABdjgAAXZIAAF2WAABdmgAAXZ4AAF2iAABdpgAAXaoAAF2uAABdsgAA'
        'XbYAAF26AABdvgAAXcoAAF3OAABd2gAAXd4AAF3qAABd7gAAXfoAAF3+AABeCgAAXg4AAF4a'
        'AABeHgAAXioAAF4uAABeOgAAXj4AAF5KAABeTgAAXmoAAF5uAABeigAAXo4AAF6aAABengAA'
        'XroAAF6+AABeygAAXs4AAF7aAABe3gAAXuoAAF7uAABe/AAAXwAAAF8cAABfIAAAXywAAF8w'
        'AABu1AAAbu4AAG8IAABzxAAAc8gAAHPUAABz2AAAc+QAAHPoAABz9AAAc/gAAHQEAAB0CAAA'
        'dBQAAHQYAAB0JAAAdCgAAHQ0AAB0OAAAdEQAAHRIAAB0VAAAdFgAAHRkAAB0aAAAdIQAAHSI'
        'AAB0lAAAdJgAAHSkAAB0qAAAdLQAAHS4AAB0xAAAdMgAAHTUAAB02AAAdPQAAHT4AAB1BAAA'
        'dQgAAHUkAAB1KAAAdTQAAHU4AAB1VAAAdVgAAHVkAAB1aAAAdYYAAHWKAAB1lgAAdZoAAHW4'
        'AAB1vAAAdcgAAHXMAAB12AAAddwAAHXoAAB17AAAdfgAAHX8AAB/pgAAf6oAAH+2AAB/ugAA'
        'iEQAAIhIAACIVAAAiFgAAIhmAACIagAAiHYAAIh6AAAFNgAAAAEAAAAIAAAADAAAABAAAAAU'
        'AAAAGAAAABwAAAAgAAABngAAAbAAAAG6AAAB1AAAAe4AAAIUAAACLgAAAjQAAAJOAAACVAAA'
        'AmAAAAJmAAACcgAAAngAAAKEAAACigAAApYAAAKcAAACqAAAAq4AAAK6AAACwAAAAswAAALS'
        'AAAC3gAAAuQAAALwAAAC9gAAAwIAAAMIAAADFAAAAxoAAAMmAAADLAAAAzgAAAM+AAADSgAA'
        'A1AAAANcAAADYgAAA24AAAN0AAADgAAAA4YAAAOSAAADmAAAA6QAAAOqAAADtgAAA7wAAAPI'
        'AAADzgAAA9oAAAPgAAAD7AAAA/IAAAP+AAAEBAAABBAAAAQWAAAEIgAABCgAAAQ0AAAEOgAA'
        'BEYAAARMAAAEWAAABF4AAARqAAAEcAAABHwAAASCAAAEjgAABJQAAASgAAAEpgAABLIAAAS4'
        'AAAExAAABMoAAATWAAAE3AAABOgAAATuAAAE+gAABQAAAAUMAAAFEgAABR4AAAUkAAAFMAAA'
        'BTYAAAVCAAAFSAAABVQAAAVaAAAFZgAABWwAAAV4AAAFfgAABYoAAAWQAAAFnAAABaIAAAWu'
        'AAAFtAAABcAAAAXGAAAF0gAABdgAAAXkAAAF6gAABfYAAAX8AAAGCAAABg4AAAYaAAAGIAAA'
        'BiwAAAYyAAAGPgAABkQAAAZQAAAGVgAABmIAAAZoAAAGdAAABnoAAAaGAAAGjAAABpgAAAae'
        'AAAGqgAABrAAAAa8AAAGwgAABs4AAAbWAAAG3gAABuQAAAbwAAAG9gAABwIAAAcMAAAHJgAA'
        'B0AAAAdYAAAHcAAAB4gAAAegAAAHugAAB9IAAAfqAAAIGgAACDQAAAhMAAAIVAAACGQAAAhq'
        'AAAIcAAACHwAAAieAAAIpgAACK4AAAi+AAAIxgAACMwAAAjUAAAI3AAACOgAAAj+AAAJBgAA'
        'CQ4AAAkcAAAJJAAACSwAAAk8AAAJYgAACXoAAAmCAAAJlgAACZ4AAAmoAAAJsAAACbYAAAm8'
        'AAAJxAAACcwAAAnUAAAJ2gAACeIAAAnqAAAJ/gAACgYAAAoMAAAKJgAACjAAAApAAAAKVgAA'
        'ClwAAApuAAAKdAAACn4AAAqKAAAKlgAACp4AAAq0AAAKugAACsIAAArIAAAK0gAACuIAAArq'
        'AAAK9AAACvwAAAusAAAMQAAADPAAAA0wAAANYAAADYwAAA2YAAANoAAADboAAA3EAAANzAAA'
        'DdoAAA3kAAAN6gAADiIAAA4yAAAOYgAADmoAAA6UAAAOsgAAD4IAAA+KAAAPmgAAD6AAAA+q'
        'AAAPsAAAD7YAAA/EAAAQEgAAEBwAABAkAAAQLgAAEDYAABA+AAAQUgAAEFwAABCEAAAQigAA'
        'EKYAABCyAAAQugAAEMYAABDaAAAQ9AAAEQgAABEQAAARMAAAEUwAABFSAAARZAAAEWoAABF0'
        'AAARhgAAEZIAABGcAAARqgAAEbwAABHEAAAR1gAAEmIAABJuAAASkgAAEp4AABKwAAASugAA'
        'EsoAABLuAAAS9AAAEyQAABMqAAATTgAAE1QAABN0AAATfAAAE5gAABOkAAAT0gAAE+gAABQM'
        'AAAUVAAAFI4AABS8AAAUygAAFOgAABTuAAAU9AAAFQYAABU2AAAVTgAAFWwAABWIAAAVkgAA'
        'Fa4AABW6AAAVxAAAFcwAABXUAAAWHgAAFjIAABZqAAAW3AAAFvAAABcSAAAXUAAAF2wAABd0'
        'AAAXqAAAF7QAABfKAAAX2AAAF+oAABfyAAAX+AAAGAIAABgIAAAYIgAAGC4AABg0AAAYUAAA'
        'GF4AABhkAAAYbAAAGIYAABiUAAAYqAAAGLgAABjoAAAY8AAAGSYAABk+AAAZaAAAGXAAABmw'
        'AAAZuAAAGcYAABnQAAAZ1gAAGdwAABnmAAAZ7AAAGfIAABn8AAAaBgAAGhQAABokAAAaLgAA'
        'GtgAABtCAAAbagAAG3AAABt6AAAbgAAAG7QAACRSAAAkYgAAJGwAACTEAAAlSgAAJwAAACcQ'
        'AAAnFgAAJxwAACciAAAnKAAAJzAAACc2AAAnTgAAJ2wAACdyAAAnegAAJ4AAACeIAAAnqAAA'
        'J8IAACfKAAAn0AAAJ9gAACfmAAAoMAAAKHAAACiQAAAopgAAKK4AACi0AAAoxgAAKMwAACjS'
        'AAAo3AAAKOgAACjuAAAo/gAAKQQAACkOAAApFAAAKSIAACkeAAApKAAAKZoAACmgAAApqgAA'
        'KbAAACm6AAApwAAAKcoAACnUAAAp3AAAKeIAACnsAAAp8gAAKfwAACoQAAAqGAAAKh4AACok'
        'AAAqMgAAKjwAACpCAAAqSAAAKlgAACpwAAAqeAAAKoIAACp+AAAqjAAAKogAACqSAAAqmAAA'
        'Kp4AACqqAAAqtAAAKsAAACrGAAAq0AAAKuYAACrsAAAq8gAAKvgAACr+AAArBAAAKwwAACsU'
        'AAArGgAAKyoAACs2AAArPAAAK0QAACtOAAArWAAAK2QAACtyAAAregAAK4YAACuSAAArmgAA'
        'K6gAACuwAAArwAAAK8oAACvUAAAr3AAALDAAACw4AAAsQgAALFYAACxeAAAsbAAALHIAACyA'
        'AAAslAAALMwAACzUAAAs3AAALOoAACzyAAAtCAAALR4AAC0uAAAtOAAALT4AAC1MAAAtpgAA'
        'LbYAAC3EAAAtzAAALd4AAC3mAAAt9gAALf4AAC4EAAAuDAAALkQAAC5yAAAulAAALwgAAC8U'
        'AAAvKgAALz4AAC9GAAAvUAAAL2AAAC9uAAAvfAAAL4IAAC+UAAAvpAAAMGIAADEyAAAxPgAA'
        'MXIAADGIAAAxkAAAMZYAADGcAAAxogAAMawAADGyAAAxyAAAMc4AADHWAAAx3AAAMeQAADHq'
        'AAAx8AAAMfgAADH+AAAyBgAAMg4AADIcAAAyJgAAMjYAADKgAAAyugAAMsAAADLGAAAyzAAA'
        'MtwAADLiAAAy6gAAMvAAADMEAAAzEAAAMxwAADMoAAAzMAAAMz4AADNIAAAzUAAAM14AADNq'
        'AAAzcAAAM3wAADOEAAAzjAAAM5YAADOeAAAzpgAAM7AAADO6AAAzxgAAM9AAADPcAAAz4gAA'
        'NAYAADQQAAA0FgAANCgAADQwAAA0QAAANEoAADRSAAA0XAAANGIAADRqAAA0cgAANHwAADR4'
        'AAA0hgAANIwAADSSAAA0mAAANKAAADTcAAA05gAANP4AADUSAAA1IAAANSgAADU6AAA1SAAA'
        'NVIAADVaAAA1YAAANWYAADVsAAA2fgAANrgAADa+AAA26gAANxQAADcaAAA3IgAANygAADfa'
        'AAA35gAAN+wAADf+AAA4CAAAOBwAADgmAAA4QgAAOE4AADhYAAA4ZAAAOHIAADiIAAA4kgAA'
        'OJ4AADikAAA4qgAAOLIAADi4AAA4xAAAOMoAADjWAAA47gAAOPwAADkIAAA5DgAAOR4AADkm'
        'AAA5LgAAOTQAADk6AAA5RAAAOVgAADluAAA5egAAOZQAADmgAAA5tAAAOcQAADnUAAA53gAA'
        'OgAAADoSAAA6IAAAOiwAADo+AAA6RAAAOlAAADpiAAA6uAAAOzgAADtqAAA7eAAAO4YAADuU'
        'AAA7ogAAO7gAADvAAAA7zAAAO+AAADvoAAA77gAAO/gAADv+AAA8RgAAPGgAADx0AAA8pAAA'
        'PLgAADzAAAA80gAAPN4AADzuAAA8/AAAPQoAAD0eAAA9LgAAPToAAD1AAAA9RgAAPUwAAD1g'
        'AAA9nAAAPcIAAD3IAAA91gAAPd4AAD4YAAA+IAAAPjQAAD4+AAA+XgAAPmgAAD5yAAA+egAA'
        'PoAAAD6UAAA+mgAAPqQAAD6yAAA+ugAAPsIAAD7IAAA+0AAAPtYAAD7iAAA+6gAAPzQAAD9C'
        'AAA/UAAAP44AAD+UAAA/qAAAP7wAAD/OAAA/1AAAP/oAAEAAAABACgAAQCwAAEAyAABASAAA'
        'QGIAAECEAABApgAARkYAAEZaAABGYAAARpgAAEaeAABGqAAAR8YAAEfMAABH0gAAR9gAAEfs'
        'AABH9gAASAIAAEiAAABIqAAASLIAAEjEAABI1AAASNoAAEjgAABI5gAASOwAAEjyAABI/gAA'
        'SQ4AAEkeAABJNgAASVoAAEluAABJggAASYoAAEnCAABJygAASmYAAEq+AABK6AAASzgAAEuK'
        'AABLlAAAS+wAAEv0AABL+gAATAAAAEwGAABMDAAATBIAAEwaAABMIgAATC4AAEw4AABMQgAA'
        'TEwAAExoAABMeAAATIAAAEyQAABMlgAATJwAAEyiAABMuAAATMwAAE0EAABNDAAATRQAAE0g'
        'AABNKgAATTQAAE1AAABNSgAATVIAAE1cAABNaAAATXQAAE18AABNhAAATZQAAE2kAABNqgAA'
        'TbIAAE24AABNvgAATcQAAE3qAABN+AAATgQAAE4QAABOHAAATiIAAE4wAABOQAAATkwAAE5S'
        'AABOWAAATmoAAE5wAABOdgAATogAAE6WAABOwgAATsgAAE7gAABO5gAATvgAAE8AAABPDAAA'
        'T0QAAE9QAABPWAAAT3IAAE+IAABPjgAAT5QAAE+oAABPygAAUNAAAFDeAABRDAAAUUYAAFGC'
        'AABRiAAAUZQAAFGcAABRsgAAUbgAAFHAAABR0gAAUeIAAFHwAABR+gAAUfYAAFIKAABSHAAA'
        'UiIAAFIuAABSNgAAUkgAAFLGAABS3gAAUuQAAFLwAABS+AAAUv4AAFMKAABTKAAAUzwAAFNC'
        'AABTTgAAU1QAAFNaAABTZgAAU2wAAFN8AABTrgAAU+YAAFPsAABT9gAAU/wAAFQSAABUHgAA'
        'VCgAAFRcAABUdAAAVJoAAFS4AABUwAAAVNwAAFTkAABU6gAAVPAAAFT2AABVCgAAVRIAAFUg'
        'AABVKgAAVTIAAFVKAABVYAAAVaIAAFXKAABWCAAAVmIAAFagAABXqgAAV7AAAFfAAABX/gAA'
        'WBAAAFgcAABYKAAAWGoAAFlYAABZaAAAWX4AAFmiAABZsgAAWgoAAFoYAABaPAAAWmAAAFqO'
        'AABalgAAWpwAAFqkAABargAAWrYAAFq8AABa0AAAWtYAAFriAABa7AAAWvIAAFr6AABbAAAA'
        'WwoAAFsQAABbHAAAWyQAAFs4AABbXAAAW2IAAFuUAABbmgAAW6QAAFuyAABbvAAAW8oAAFwE'
        'AABcDAAAXGYAAFxuAABcrgAAXL4AAFz4AABkOAAAZD4AAGRQAABkWgAAZFYAAGRyAABkhAAA'
        'ZIoAAGSWAABkngAAZNoAAGUCAABmIgAAZkwAAGZSAABmWAAAZmAAAGZmAABmcAAAZnYAAGaQ'
        'AABmogAAZsQAAGbQAABm/AAAZxwAAGcuAABnOgAAZ0AAAGdoAABneAAAZ5YAAGecAABnrgAA'
        'Z7wAAGfKAABn4gAAZ/QAAGf+AABoDgAAaBQAAGgaAABoRAAAaLQAAGi8AABo2AAAaS4AAGk0'
        'AABpRAAAaVoAAGluAABpegAAaYoAAGmcAABpwgAAadIAAGnYAABp3gAAaeQAAGnyAABp/gAA'
        'agoAAGoSAABqhAAAaowAAGriAABq+AAAawIAAGsMAABrEgAAaxoAAGsgAABrJgAAazIAAGs4'
        'AABrdAAAa4AAAGuKAABrngAAa6YAAGu6AABrwgAAa8wAAGvcAABr5gAAbEoAAGxQAABsVgAA'
        'bKYAAGysAABs0AAAbOQAAGzsAABs9gAAbPwAAG0EAABtCgAAbRQAAG0gAABtJgAAbTwAAG1C'
        'AABtagAAbXAAAG2kAABtsAAAbboAAG3AAABtyAAAbdAAAG3WAABt4gAAbe4AAG32AABt/gAA'
        'bgYAAG4UAABuJAAAbjQAAG4+AABuWgAAbmAAAG5mAABudAAAboQAAG6MAABuoAAAbrAAAG7E'
        'AABu3gAAbvgAAG8SAABvHgAAbzIAAG88AABvRAAAb1wAAG9sAABvhAAAb5wAAG+0AABv3gAA'
        'b+YAAHACAABwFgAAcCYAAHBAAABwTgAAcF4AAHCEAABwkgAAcKQAAHCqAABwvAAAcMIAAHDU'
        'AABw2gAAcQQAAHEOAABxNAAAccIAAHHOAAByGAAAciwAAHJAAABy6gAAcvoAAHMgAABzNgAA'
        'c1YAAHNqAABznAAAc6QAAHu2AAB7vAAAe8IAAHvIAAB7zgAAe9QAAHveAAB75AAAe/AAAHv6'
        'AAB8EAAAfBYAAHweAAB8JgAAfEgAAHxSAAB8WAAAfF4AAHxsAAB8aAAAfHQAAHx8AAB8lgAA'
        'fJ4AAHykAAB8rAAAfLIAAHy8AAB8wgAAfNAAAHzYAAB83gAAfOoAAHz+AAB9BAAAfRgAAH0e'
        'AAB9JgAAfSwAAH2WAAB9ngAAfcAAAH3MAAB92AAAfeoAAH3wAAB9/AAAfhQAAH4oAAB+MAAA'
        'fjoAAH5CAAB+SAAAfl4AAH5sAAB+igAAfpYAAH6eAAB+pgAAfq4AAH68AAB+xAAAftIAAH7Y'
        'AAB+3gAAfuQAAH7qAAB++AAAfwgAAH8UAAB/IAAAfyoAAH8wAAB/OgAAf0IAAH9gAAB/ZgAA'
        'f3AAAH94AAB/gAAAgHgAAIB+AACAhAAAgIwAAICSAACAmAAAgKwAAIC6AACA1AAAgOwAAID2'
        'AACA/AAAgTQAAIG6AACBwgAAgdgAAIHiAACB6gAAggQAAIIeAACCMgAAgjwAAIJSAACCigAA'
        'gpIAAIKYAACCoAAAgqgAAIKuAACCuAAAgr4AAILGAACC1AAAgtwAAILyAACDLAAAg8YAAIQC'
        'AACEGAAAhCIAAIQ8AACESgAAhFYAAISKAACExgAAhMwAAITaAACE6AAAhO4AAIT2AACFEAAA'
        'hRoAAIUkAACFNgAAhT4AAIVmAACFdAAAhXoAAIWOAACFmgAAhcQAAIXKAACF0AAAhg4AAIYs'
        'AACGSAAAhl4AAIZyAACGjgAAhpwAAIaoAACGxAAAhs4AAIbUAACG3gAAhuQAAIb8AACHAgAA'
        'hwwAAIcSAACHNAAAhz4AAIdEAACHTgAAh1QAAIdgAACHZgAAh3QAAIeCAACHiAAAh54AAIes'
        'AACHuAAAh9wAAIfmAACIDAAAiBQAAIgcAACILAAAAAAAAAPyAAAD6wAAxDEAAAPy'
    ),
    'Lemmings2.info': (
        '4xAAAQAAAAAAAAAAABoAEwAEAAMAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAB'
        'AAAAAYAAAACAAAAAAAAAAAAAAAAAACgAAAAAAAAaABIAAgAAAAEDAAAAAAAANYAAAH/AAAD/'
        '4AABwHAAAZEwAACAIAAAAAAAAAAAAAH/8AAD//gAAf/wAAD/4AAA/+AAAP/gAAB7wAAAe8AA'
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAG7AAAB/wAAAf8AAAD+AAAH/8AAD//gAB//8AAb/'
        '7AAA/+AAAP/gAAB7wAAAe8AAAPvgAAH78AAAAAAIV0hETG9hZAAAAAAQAAAAFlNMQVZFPUxl'
        'bW1pbmdzMi5zbGF2ZQAAAAAIUFJFTE9BRAAAAAANTk9XUklURUNBQ0hFAA=='
    ),
}
# END GENERATED BY build.py


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def embedded(name: str) -> bytes:
    """A file build.py embedded: the slave, the editor or the icon."""
    if name not in BLOBS:
        raise SystemExit(f'{name} is missing: run build.py first')
    data = base64.b64decode(BLOBS[name])
    if sha256(data) != BLOB_SHA256[name]:
        raise SystemExit(f'{name}: the embedded copy is damaged')
    return data


# --- Disk images -------------------------------------------------------------

SPREAD = [sum(((byte >> bit) & 1) << (2 * bit) for bit in range(8)) for byte in range(256)]


def mfm_longs(odd: bytes, even: bytes) -> list[int]:
    """Long words from their odd and their even bits, 16 bits each, as an
    AmigaDOS sector stores them before MFM encoding."""
    return [(SPREAD[odd[i]] << 16 | SPREAD[odd[i + 1]]) << 1
            | SPREAD[even[i]] << 16 | SPREAD[even[i + 1]] for i in range(0, len(odd), 2)]


def mfm_checksum(data: bytes) -> int:
    value = 0
    for i in range(0, len(data), 2):
        value ^= SPREAD[data[i]] << 16 | SPREAD[data[i + 1]]
    return value


def ipf_to_adf(image: bytes) -> bytes:
    """The AmigaDOS sectors of an IPF image as an ADF image.

    An IPF image holds a track's blocks as streams of elements; on an
    AmigaDOS track each sector is a block whose data element is the 540
    bytes after the sync words, before MFM encoding: the sector header
    (format, track, sector, sectors to the gap), the label, the two
    checksums and the 512 data bytes, each long word as its odd bits, then
    its even bits. A track without such sectors (disk 3's protection
    track) leaves zeros."""
    if image[:4] != b'CAPS':
        raise SystemExit('not an IPF image')
    tracks, areas = {}, {}
    at = 0
    while at < len(image):
        kind = image[at:at + 4]
        length = struct.unpack_from('>I', image, at + 4)[0]
        if kind == b'IMGE':
            fields = struct.unpack_from('>14I', image, at + 12)
            tracks[fields[13]] = fields                # by data key
        elif kind == b'DATA':
            size, _, _, key = struct.unpack_from('>4I', image, at + 12)
            areas[key] = image[at + 28:at + 28 + size]
            at += size
        at += length
    adf = bytearray(80 * 2 * 11 * 512)
    for key, (cylinder, side, *_rest) in tracks.items():
        if cylinder >= 80:
            continue                                    # unformatted extra cylinders
        area, blocks = areas[key], tracks[key][10]
        for block in range(blocks):
            descriptor = struct.unpack_from('>8I', area, 32 * block)
            flags, at = descriptor[5], descriptor[7]
            sector = None
            while area[at] & 31:                        # 0: the stream's end
                kind, width = area[at] & 31, area[at] >> 5
                size = int.from_bytes(area[at + 1:at + 1 + width], 'big')
                at += 1 + width
                count = (size + 7) // 8 if flags & 2 else size
                if kind == 2 and count == 540:          # data
                    sector = area[at:at + 540]
                if kind != 5:                           # fuzzy bits store nothing
                    at += count
            if sector is None:
                continue
            header = mfm_longs(sector[0:2], sector[2:4])[0]
            header_sum = mfm_longs(sector[20:22], sector[22:24])[0]
            data_sum = mfm_longs(sector[24:26], sector[26:28])[0]
            track, number = header >> 16 & 255, header >> 8 & 255
            if (header >> 24 != 0xFF or track != cylinder * 2 + side or number > 10
                    or mfm_checksum(sector[0:20]) != header_sum
                    or mfm_checksum(sector[28:540]) != data_sum):
                raise SystemExit(f'IPF image: a damaged sector on track {cylinder}.{side}')
            words = mfm_longs(sector[28:284], sector[284:540])
            place = (track * 11 + number) * 512
            adf[place:place + 512] = struct.pack('>128I', *words)
    return bytes(adf)


def ofs_files(adf: bytes) -> dict[str, bytes]:
    """Every file of an AmigaDOS (OFS) disk image, by its path."""
    def block(number: int) -> bytes:
        return adf[number * 512:(number + 1) * 512]

    def long(data: bytes, offset: int) -> int:
        return struct.unpack_from('>I', data, offset)[0]

    files: dict[str, bytes] = {}

    def walk(directory: bytes, prefix: str) -> None:
        for slot in range(72):
            key = long(directory, 24 + 4 * slot)
            while key:
                header = block(key)
                name = prefix + header[433:433 + header[432]].decode('latin-1')
                kind = struct.unpack_from('>i', header, 508)[0]
                if kind == 2:                           # a directory
                    walk(header, name + '/')
                elif kind == -3:                        # a file
                    chunks, part = [], header
                    while True:
                        for index in range(long(part, 8)):
                            data = block(long(part, 308 - 4 * index))
                            chunks.append(data[24:24 + long(data, 12)])
                        extension = long(part, 504)
                        if not extension:
                            break
                        part = block(extension)
                    content = b''.join(chunks)
                    if len(content) != long(header, 324):
                        raise SystemExit(f'{name}: its size does not match its blocks')
                    files[name] = content
                key = long(header, 496)

    walk(block(880), '')
    return files


# --- RNC method 1 --------------------------------------------------------------

def crc16(data: bytes) -> int:
    """CRC-16 with the polynomial $8005, reflected (RNC's and WHDLoad's)."""
    table = []
    for i in range(256):
        value = i
        for _ in range(8):
            value = (value >> 1) ^ 0xA001 if value & 1 else value >> 1
        table.append(value)
    value = 0
    for byte in data:
        value = (value >> 8) ^ table[(value ^ byte) & 0xFF]
    return value


class BitStream:
    """RNC's bit stream: 16-bit little-endian words, read from the low bit,
    with the literal bytes between them."""

    def __init__(self, data: bytes):
        self.data = data
        self.cursor = 0
        self.pending = 0
        self.buffer = self.peek_word()

    def peek_word(self) -> int:
        # The decoder looks up to two bytes past the end; zeros are safe there.
        return int.from_bytes(self.data[self.cursor:self.cursor + 2], 'little')

    def read(self, width: int) -> int:
        value = self.buffer & ((1 << width) - 1)
        if width > self.pending:
            available = min(16, (len(self.data) - self.cursor) * 8)
            if width - self.pending > available:
                raise ValueError('truncated RNC stream')
            self.buffer >>= self.pending
            width -= self.pending
            self.cursor += 2
            self.buffer = (self.buffer & 0xFFFF) | (self.peek_word() << 16)
            self.pending = available
        self.pending -= width
        self.buffer >>= width
        return value

    def literals(self, count: int) -> bytes:
        if count == 0:
            return b''
        end = self.cursor + count
        if end > len(self.data):
            raise ValueError('truncated RNC literals')
        data = self.data[self.cursor:end]
        self.cursor = end
        self.buffer &= (1 << self.pending) - 1
        self.buffer |= self.peek_word() << self.pending
        return data


def huffman_table(bits: BitStream, previous):
    count = bits.read(5)
    if count == 0:
        return previous
    if count > 16:
        raise ValueError('RNC table over 16 symbols')
    widths = [bits.read(4) for _ in range(count)]
    table, code = [], 0
    for width in range(1, 17):
        for symbol, size in enumerate(widths):
            if size == width:
                table.append((width, int(f'{code:0{width}b}'[::-1], 2), symbol))
                code += 1
        code <<= 1
    return table


def huffman_value(bits: BitStream, table) -> int:
    for width, code, symbol in table or ():
        if bits.buffer & ((1 << width) - 1) == code:
            bits.read(width)
            return symbol if symbol < 2 else (1 << (symbol - 1)) | bits.read(symbol - 1)
    raise ValueError('invalid RNC code')


def rnc_unpack(data: bytes) -> bytes:
    """An RNC method 1 stream ("RNC", 1, its 18-byte header) unpacked, both
    of its CRCs checked."""
    if data[:4] != b'RNC\x01':
        raise ValueError('not an RNC method 1 stream')
    size, packed, unpacked_crc, packed_crc, _, blocks = struct.unpack_from('>IIHHBB', data, 4)
    stream = data[18:18 + packed]
    if len(stream) != packed or crc16(stream) != packed_crc:
        raise ValueError('RNC stream damaged')
    bits = BitStream(stream)
    bits.read(2)
    out = bytearray()
    tables = [None] * 3
    for _ in range(blocks):
        tables = [huffman_table(bits, previous) for previous in tables]
        chunks = bits.read(16)
        for index in range(chunks):
            count = huffman_value(bits, tables[0])
            if len(out) + count > size:
                raise ValueError('RNC stream damaged')
            out += bits.literals(count)
            if index + 1 == chunks:
                break
            distance = huffman_value(bits, tables[1]) + 1
            count = huffman_value(bits, tables[2]) + 2
            if distance > len(out) or len(out) + count > size:
                raise ValueError('RNC stream damaged')
            for _ in range(count):
                out.append(out[-distance])
    if len(out) != size or crc16(out) != unpacked_crc:
        raise ValueError('RNC stream damaged')
    return bytes(out)


# --- The install ---------------------------------------------------------------

def hunk0(program: bytes) -> int:
    """The file offset of hunk 0's contents in a hunk executable."""
    if struct.unpack_from('>2I', program) != (0x3F3, 0):
        raise SystemExit('not a hunk executable')
    count = struct.unpack_from('>I', program, 8)[0]
    at = 4 * (5 + count)
    if struct.unpack_from('>I', program, at)[0] not in (0x3E9, 0x3EA):
        raise SystemExit('hunk 0 is not a code or data hunk')
    return at + 8


def complete_slave(slave: bytes, main: bytes) -> bytes:
    """The slave with gate_value from the main program's disk-3 check."""
    code = hunk0(main) + GATE_CODE
    if main[code:code + len(GATE_OPCODES)] != GATE_OPCODES:
        raise SystemExit('the main program is not the supported version')
    value = main[code + len(GATE_OPCODES):code + len(GATE_OPCODES) + 4]
    slot = hunk0(slave) + GATE_SLOT
    if slave[slot:slot + 4] != bytes(4):
        raise SystemExit('the embedded slave is not the one patch.py expects')
    return slave[:slot] + value + slave[slot + 4:]


def tile_flags(main: bytes) -> bytes:
    """data/EditorTiles: for each style and tile, the flags most of the
    tile's cells have in the game's own levels: bit 0 Decor (non-colliding,
    cell bit 30), bit 1 Steel (indestructible, cell bit 28). The editor
    gives a new tile these flags."""
    base = hunk0(main)
    counts = [[[0, 0, 0] for _ in range(TILES)] for _ in range(STYLES)]
    for offset, size, digest in LEVEL_BANKS:
        at = base + offset
        packed = struct.unpack_from('>I', main, at + 8)[0]
        bank = rnc_unpack(main[at:at + 18 + packed])
        if len(bank) != size or sha256(bank) != digest:
            raise SystemExit('the main program\'s levels are not the expected ones')
        for record in range(0, size, RECORD_SIZE):
            style = struct.unpack_from('<H', bank, record + RECORD_STYLE)[0]
            for cell in struct.unpack_from(f'>{MAP_CELLS}I', bank, record + RECORD_CELLS):
                tile = cell & CELL_TILE
                if tile:
                    count = counts[style][tile]
                    count[0] += 1
                    count[1] += bool(cell & CELL_DECOR)
                    count[2] += bool(cell & CELL_STEEL)
    table = bytearray(STYLES * TILES)
    for style in range(STYLES):
        for tile, (cells, decor, steel) in enumerate(counts[style]):
            table[style * TILES + tile] = (2 * decor > cells) | (2 * steel > cells) << 1
    return bytes(table)


def read_images(paths: list[Path]) -> dict[int, dict[str, bytes]]:
    """The files of the three disks, from images checked by SHA-256."""
    disks: dict[int, dict[str, bytes]] = {}
    for path in paths:
        data = path.read_bytes()
        known = IMAGES.get(sha256(data))
        if known is None:
            raise SystemExit(f'{path}: not a supported disk image (SHA-256 {sha256(data)})')
        number, kind = known
        if number in disks:
            raise SystemExit(f'{path}: disk {number} given twice')
        disks[number] = ofs_files(ipf_to_adf(data) if kind == 'IPF' else data)
    missing = {1, 2, 3} - disks.keys()
    if missing:
        raise SystemExit(f'disk {min(missing)} is missing')
    return disks


def make_install(disks: dict[int, dict[str, bytes]]) -> dict[str, bytes]:
    """Every file of the install, checked, by its path in the install."""
    out = {}
    for number, name, size, digest in FILES:
        data = disks[number].get(name)
        if data is None or len(data) != size or sha256(data) != digest:
            raise SystemExit(f'disk {number}: {name} is not the expected file')
        out[f'data/{name}'] = data
    packed = disks[2].get(MAIN)
    if packed is None or (len(packed), sha256(packed)) != MAIN_PACKED:
        raise SystemExit(f'disk 2: {MAIN} is not the expected file')
    main = rnc_unpack(packed)
    if (len(main), sha256(main)) != MAIN_UNPACKED:
        raise SystemExit(f'disk 2: {MAIN} did not unpack to the expected program')
    out[f'data/{MAIN}'] = main
    out['data/Editor'] = embedded('Editor')
    out['data/EditorTiles'] = tile_flags(main)
    out[SLAVE] = complete_slave(embedded(SLAVE), main)
    out[ICON] = embedded(ICON)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('images', nargs=3, type=Path, metavar='DISK',
                        help='your images of the three disks (IPF or ADF), in any order')
    parser.add_argument('--out', type=Path, default=Path('Lemmings2'),
                        help='the install directory (default: Lemmings2)')
    args = parser.parse_args()
    for path in args.images:
        if not path.is_file():
            raise SystemExit(f'{path}: no such file')
    files = make_install(read_images(args.images))
    out = args.out
    if out.exists() and not out.is_dir():
        raise SystemExit(f'{out}: not a directory')
    written, kept = 0, []
    for name, data in sorted(files.items()):
        path = out / name
        if name == f'data/{SAVED_POSITIONS}' and path.exists():
            kept.append(name)                           # the player's saved positions
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        written += 1
    (out / 'Levels').mkdir(exist_ok=True)
    levels = len(list((out / 'Levels').glob('*.lvl')))
    print(f'{out}: Lemmings 2: The Tribes with the in-game level editor V{VERSION} '
          f'for WHDLoad, {written} files written'
          + (f', {", ".join(kept)} kept' if kept else '')
          + f'; Levels holds {levels} level{"" if levels == 1 else "s"}.')


if __name__ == '__main__':
    main()
