#!/usr/bin/env python3
# Lemmings 2: The Tribes In-Game Level Editor V1.0
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Make the WHDLoad install of Lemmings 2: The Tribes with the in-game level
editor from your own copy of the game.

Usage: python3 patch.py DISK1 DISK2 DISK3 [--out DIR]

DISK1, DISK2 and DISK3 are your images of the game's three disks, IPF or
ADF files, in any order. Each must have one of the SHA-256 hashes listed in
IMAGES (and in README.md); other versions of the game are refused. Every
input is checked before anything is written, and the inputs are only read.
The install is written to DIR (default: Lemmings2):

  Lemmings2.slave   the WHDLoad slave
  Lemmings2.info    its Workbench icon (tool types PRELOAD NOWRITECACHE)
  data/             the game's files from your disks with the main program
                    unpacked, the editor (Editor) and the editor's tile
                    flags (EditorTiles), worked out from the game's levels
  Levels/           your levels (.lvl files)

Run again over an existing install, it writes the program files again and
keeps your levels and your saved positions. Needs only Python 3.8 or later.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import struct
import sys

VERSION = '1.0'
SLAVE, ICON = 'Lemmings2.slave', 'Lemmings2.info'

# The supported disk images: SHA-256 -> (disk, format). The ADF images hold
# the standard AmigaDOS tracks of the IPF images; disk 3's protection track
# cannot be held in an ADF, and its blocks are zeros there.
IMAGES = {
    '24a005cca5ba97da00bd44233863b817f90b6a08906c65dba2fd1bcd20045509': (1, 'IPF'),
    '05b800affc4bcb5044f41606bc807d7efc5f0669b82abb1b9573f38631257965': (2, 'IPF'),
    'e5cff8776a8a09a8fb1d1b7f23767ccab5c2acc6f06b10ee0f13f54dd57f5ce5': (3, 'IPF'),
    'd1b71a2a0d5797c3c185f4d939b9ad2416921a8370ee082f2bc9df0ee73ac181': (1, 'ADF'),
    'fcbc1b870ae30bc5f79a58ee8bef81e1e7743472240de8896f21d9508abdff91': (2, 'ADF'),
    '5219ae0d109ef94ce1eb84212024b83e929def0d2e8ea68fc5c0c4abd4589fb3': (3, 'ADF'),
}

# The game's files the install needs, as they are on the disks: (disk,
# name, size, SHA-256). They go into data/ under the same names.
FILES = [
    (1, 'L2-Saved-Positions', 5022,
     'dc30b90ae8995e6b067f62b60eecff5ee470c85d256284bd377a28a4367456bf'),
    (1, 'endseq.dat', 131186,
     '2cfbfd5071837590f4112b03fbb8a7ba1fbd50a8ae582409c9c572965babd786'),
    (1, 'endtune', 34744,
     'ad7a134f3debd59eae56f244e6c563dfd85668134034882965f980194e5dd851'),
    (2, 'Maintune', 120678,
     '29cc402c8343a6ab4b44edcd4177b12a9ebe46e72d4d1c4835b6be7dbc82a6da'),
    (2, 'alemms.comp', 53204,
     '89af4a2ed258b786eb0931ffe1dd61d40906ce0c8be1e83d5faf646e497cc707'),
    (2, 'logo.dat', 52931,
     'ffb18397580a084377335d106754a10b15a99c3cd2241d455f06b0ca310d9c6c'),
    (2, 'soundfx/L2ExtendedFX', 251115,
     '87fb153c67812289b5754ead2dd2ece06324f08d89e15306c298784c8d4b92d8'),
    (2, 'soundfx/l2basicfx', 52891,
     '0055a6f5c7def2ca407d4b21e84e4a0225f7c8da43f550b25dfdfc7263576faa'),
    (3, 'beach/astyle.dat', 21978,
     '1d7b38950527c392574d255a3ec79a1220e2183462098064a140c85a6282e4bf'),
    (3, 'beach/tribe.dat', 2786,
     '2160335da3949d971e1483e1c5a102f7555b46511f7a5617978a31a7bb4afd45'),
    (3, 'beach/tune', 29638,
     '4a142af542045f800db3303c14a94dd9b245c010ffa3deb4312d13efb121e339'),
    (3, 'cavelem/astyle.dat', 32393,
     'a6a05f3b879f7c8bc2d05ac8c9a6588bd0e092f358439b3f5a941cfbe81c57b6'),
    (3, 'cavelem/tribe.dat', 2953,
     '1357213fddbfbf33ff5d292febe7c0eac62aa1e9f97ce5c06eee8e3d4dd116b0'),
    (3, 'cavelem/tune', 19894,
     'b83aeff0c188a6b33ffa04b45dc2bf884d6c7e4ddaad3bd14feadc4b5b01b4e1'),
    (3, 'circus/astyle.dat', 16680,
     'f6292ff76d824e33788d36c9c7de3229439572d235821878e2591127c2f816ba'),
    (3, 'circus/tribe.dat', 3040,
     '2643471f0f9a4bc174e051676477797aefb6a6b2834ec9254268ae0eeac5c04d'),
    (3, 'circus/tune', 21819,
     'bc577a661b73c7e4735816c41318543fc300cce73cd32f7c767fdd55cd975c7b'),
    (3, 'classic/astyle.dat', 16309,
     'e5c05d0936a870532e66c49f5362cf6fe4e777f09f851fee1b7db1c7825ed3e5'),
    (3, 'classic/tribe.dat', 3068,
     '6a29a8d991791c712c716ed78c0da6bab0baab77038e38485e0eed93d098b921'),
    (3, 'classic/tune', 36080,
     '6d74dc245f5b53547fcb0a8a985898a16ef0cb29101f4493864bf2559f26d31f'),
    (3, 'egyptian/astyle.dat', 19637,
     '6cb6e5d779d9e170105989e246867cd7c2fbe4c069db4f9a278663735ca861cf'),
    (3, 'egyptian/tribe.dat', 3124,
     '591afb60be7ec9e7e8fa8784f1734c1889ffd2d52fe62fce1cc38a9919579dc7'),
    (3, 'egyptian/tune', 28763,
     '5f0bbdc773eb8ebf159aa882fc49a63786a8778e5405c91254ec4da86c8b9985'),
    (3, 'graphics/TalBack.dat', 3745,
     '611c9c2974a32b44ed526fa066580a05201b7a8005241dd91c5b288929c0ddbd'),
    (3, 'graphics/talisman.dat', 15515,
     'cfe5048786ec6253de4fd069854991c9ec33f744f1ec8f4f02297559c779f2ab'),
    (3, 'graphics/worldmap.dat', 26217,
     '91c34bf4a16c513300ab7f6ad6c7a90aeb2a7e0696e22d04c877d789ba5c4a16'),
    (3, 'graphics/worldsprites.dat', 11451,
     '4dc8e064052215d8e411a5c3f7152bade2803541861b4c1dd397e3af764719af'),
    (3, 'highland/astyle.dat', 24145,
     'de4763baa22532c0a7fd5c842128dd53c816ccb4fb5b7f5a1a742ebf4f92e09d'),
    (3, 'highland/tribe.dat', 2707,
     '49d3d97f696cf0156dc0ce7b97b259c8a41432f256db7bb3ac70eb7e586e1584'),
    (3, 'highland/tune', 23903,
     'a07d10add2914c289356ff95456984849c8aa3f3c6db154499440672442ddc60'),
    (3, 'l2extendedfx2', 61487,
     'a58185b350d720e2ff31641cf3f8c5a34f4111fe7b141b926420350b303130a9'),
    (3, 'medieval/astyle.dat', 34903,
     'b0928ede3361d79a117da184cc0094995050147b4fc1d3ebf92b5a295c709ef1'),
    (3, 'medieval/tribe.dat', 2862,
     '7dec91ceddaf75ffa4a603513abde3ded65123bec184c1c56ca93cadb6c11923'),
    (3, 'medieval/tune', 31549,
     'f8e910b989197d3ee80d1d534380e54f4a03d7fc5ce85bf4cdf1e8c134778be6'),
    (3, 'outdoor/astyle.dat', 26310,
     'e264fc5577653d08e62ba2a8a5a5b263ce252d2b0d47c9ff2d37a78850253345'),
    (3, 'outdoor/tribe.dat', 3101,
     '54970493f99004f618587da99d0ab3e89874cc5a7a59f84bb9e90ff360310644'),
    (3, 'outdoor/tune', 23028,
     'c9f2e964b6f8c08711d5c1a801f0767fdbf9cb5d51f32f4168249fb909059a44'),
    (3, 'polar/astyle.dat', 23425,
     '7c3f45b719756ecef13a099c98508aac96cc2155f5178dc9c84c12435d1635df'),
    (3, 'polar/tribe.dat', 2324,
     'f28a164c23dd4bd88edbe03e441c089e4a8bd292d0c27b92bfcd91c9c65fb83b'),
    (3, 'polar/tune', 31990,
     'cea04159fae7b03d2a7328e58f41072c025d2544eed2dc4e45891234b2b58bec'),
    (3, 'shadow/astyle.dat', 17474,
     'cfbc24fb266b98775630b228eabd390ddb7e29be33239d206d065a20361388f4'),
    (3, 'shadow/tribe.dat', 2916,
     '7831b3f194945f2215a181929ac4de0d81175fc87f6a27327eb71b018ec95d13'),
    (3, 'shadow/tune', 25093,
     '6de96abab09b367d3bafde4759f5875778b6708c98139f646dc66c92164f7ba7'),
    (3, 'space/astyle.dat', 29025,
     '57cb6e2f44fe3379c01e3fa8a58acd1f5ed987697982e3cdceea62fc48180281'),
    (3, 'space/tribe.dat', 3097,
     'e790ef11dfefc7a6825e2cb7c697cbb7fa9655401dcf0582c3bf47b2658d2bb2'),
    (3, 'space/tune', 29724,
     'e0c383153dff1010f1e103e7229c296542a596681ec419d0af210dd361148b21'),
    (3, 'sports/astyle.dat', 22442,
     'ca4fe98d0fa3cecdd9e2b4415f8458905e6ee055862cb99d59db2170e633c18a'),
    (3, 'sports/tribe.dat', 3079,
     'd238319f9f310499fee731ae6555b0f0e19c0962901087a039b65a9ff54c55b7'),
    (3, 'sports/tune', 30113,
     'c57baf518bb40268b0bcb5c272390f14ff152d5bcf6cea12f6f878288b6aa055'),
]
SAVED_POSITIONS = 'L2-Saved-Positions'      # the player's own after the first save

# The main program, on disk 2, packed with RNC method 1: installed unpacked.
MAIN = 'Lemmings2'
MAIN_PACKED = (263294, 'f098749778dbede40e478f4784f752a7faba1f399d0f6dd67aaeff04476750c9')
MAIN_UNPACKED = (394024, '8d49aec4874845fdaf458a205d9d451c0f31546c575763cd79e56b279738627a')

# The game's own levels: RNC streams in the main program's hunk 0, each a
# bank of level records: (offset in hunk 0, unpacked size, SHA-256).
LEVEL_BANKS = [
    (0x1c66a, 86480, '653fb3560d94a41d6b34c26172eed4634fd3860a24e0e10a572fddc83fa7d08a'),
    (0x1ddac, 86480, '9bf1353258f0e4d70ee7d791a9a36b3df5ed756f16ca9fb020fc12d442b79a46'),
    (0x1fe6a, 86480, '1b61e6ba55e6d82b755a3e612d8a63d0fe4ff62a0b13a1daa87be961b59ef887'),
    (0x22298, 86480, '3edb7c1cc8d54f479e16bf9a6477d5d4d4d39b7ec8f6b073a5517db6db2cd9eb'),
    (0x24386, 86480, '5278b6fb63bc5e3c212ec05eaa02eddfcfe91b8e95ba7ab7c249656363043987'),
    (0x26c0e, 86480, 'f5101a89a833d6e218c6b0e8f9f6bd838fc19700e261cff517ed8406f84ccbd9'),
    (0x289c2, 86480, 'fdad7688e4d70a88801aa995df9cc86a60c290e256f92c1a1b25b68a8697476a'),
    (0x2b12a, 86480, '67f583215dd90d7340373012f3b628b77750f8d31f6b9cf7bd580e19127d9294'),
    (0x2d4ae, 86480, '603ef072a1aa219b03ec1ed6e9e5515dd56771522a35c8c542a7c0c57166d439'),
    (0x2ff80, 86480, '5aefc08fc9ceb4d13178f9e8effdb4aa7091b63f56e5be0023b9594467f683ac'),
    (0x31ebe, 86480, '0c532a4c28ea9c953fc721986b43087f1d5263c3e462525bdf3aef2385e56961'),
    (0x348c2, 86480, '028697cee6b58cc4a63c45e23e302f14f2be32bc0508fe6dbfc7f25b3d5df415'),
    (0x36c54, 34592, '5497c78245703f71f2f8b709968453a768932fffd918a631a9e0cfd89db1f795'),
]
RECORD_SIZE = 0x21C8                    # a level record (FORM L2LV)
RECORD_STYLE, RECORD_CELLS = 0x66, 0x74 # its style (LE16) and map (BE32 cells)
MAP_CELLS = 1971
STYLES, TILES = 12, 1024                # data/EditorTiles: a byte per style and tile
CELL_TILE, CELL_STEEL, CELL_DECOR = 0x3FF, 1 << 28, 1 << 30

# The game's disk-3 check (hunk 0 $1B6E) compares the long word at $B4 with
# the one in its own code: move.l ($b4).w,d7 / cmp.l #...,d7 at $1B76. The
# slave puts that long word at $B4; it is copied from your main program into
# the slave's gate_value, GATE_SLOT bytes into its code (src/whdload/slave.s).
GATE_CODE, GATE_OPCODES = 0x1B76, bytes.fromhex('2e3800b4bebc')
GATE_SLOT = 0x34

# BEGIN GENERATED BY build.py - do not edit by hand
BLOB_SHA256 = {
    'Lemmings2.slave': '4a7b7534f035786aa2ee63332d1017dae73fb2b8dd2eee7195f4954cae7d97e0',
    'Editor': '1a2872b32a0c2c421f4b5b3c689f3c3f5edc1323004057491103db08a9ef6547',
    'Lemmings2.info': '47756be30c5375b632acba1b570bee8dbff009ddfb6b0670daf9b1c41af53b60',
}
BLOBS = {
    'Lemmings2.slave': (
        'AAAD8wAAAAAAAAABAAAAAAAAAAAAAAEkAAAD6QAAASRw/051V0hETE9BRFMAERAGAA8AAAAA'
        'AAACHgAAAAAAWQAMAAAAOABPAGsAAAAAAAAAAAAAAAAAAExlbW1pbmdzIDI6IFRoZSBUcmli'
        'ZXMAMTk5MyBETUEgRGVzaWduIC8gUHN5Z25vc2lzAExldmVsIEVkaXRvciBWMS4wCmJ5IFRp'
        'bW8gSGVpbW9uZW4KaHR0cHM6Ly9naXRodWIuY29tL3RpbW9oZWltb25lbi9hbWlnYS1sZW1t'
        'aW5nczItZWRpdG9yLXBhdGNoAGRhdGEvTGVtbWluZ3MyAGRhdGEvRWRpdG9yAFVuc3VwcG9y'
        'dGVkIGRpc2sgb3BlcmF0aW9uAFRoaXMgaW5zdGFsbCBuZWVkcyBmYXN0IG1lbW9yeQBUaGUg'
        'aW5zdGFsbCB0b29sIGhhcyBub3QgY29tcGxldGVkIHRoaXMgc2xhdmUAZGF0YS9FZGl0b3Ig'
        'aXMgdG9vIGxhcmdlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOYAAAAJAAZGF0YS8AAAAAAAAA'
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
        'AAAAAAABF5ZKuAAEAAEbmEjn//4AAA4uG0ACsAAADjIT/AAAAAAONgC/7AEAAOVQO3wAAgAA'
        '5VQBmkItAAFqZEq4AAQAAWpoZgAA6AABa7RhAAHq/////0P6/0giiCRIIDr9+LC8ACAAAGQO'
        'SHr+zUh5AAAAK2AAAkogOv3yZg5Iev7YSHkAAAArYAACNkH6/nUiev3GTqoACLC8AAYDKGYA'
        'AWggev20TqoAMLB81yFmAAFYIHr9pEKnSHn/////LzyIEAADSHkAAAAILzyIEAACSHkAACAA'
        'LzyIEAAAIk9OqgBQT+8AHCB6/XBYiEP6/rZwA0foAAQiyyIQ5YkgQVHI//Kw/AAAZgABACZ6'
        '/phB+v7yIBhrDCIYsrMIAGYAAOpg8CJL0/wAAReWMvxO+UH6APgiiCJL0/wAARuYMvxO+UH6'
        'APYiiEPrDi4y/E65QfoBViLIIvxOcU5xMrxOcSJL0/wAAOVSMrwAMSJL0/wAAWpkMvxO+UH6'
        'AJoiyDK8TnEiS9P8AAFrtCK8TnFOcUH6/YIoevzE2fwACAAAIkxOqgAIIExCp0h5AAAACC88'
        'iBAAAiJPTqoAUE/vAAywvAAEAABjDkh6/cBIeQAAACtgAADwQfr9zE6USoBnDC8ASHkAAAAr'
        'YAAA2iR6/bZOqgAgQrgABCH6/HYAtHAAcgAkPAAIIACRyE7TSHkAAAAJYAAAsC86/ZAGlwAB'
        'auovOv2GBpcAAWciTnUbfAAwAeNCrQKCUe0B6k51SOd//gwoADoAA2YCWIhF+v15dD4U2FfK'
        '//xCEkH6/WYkev1GSgBnDgwAAAFmMiABTqoADGAWJkgoSU6qACRKgGcSIEsiTE6qAAgugEzf'
        'f/5wAE51TN9//iA8AAAAzU51SHr8hEh5AAAAK2AAABwbQAKwE/wAAAC/7AGwOvujZwJOdUh5'
        '/////y86/N5Yl051AAAD8g=='
    ),
    'Editor': (
        'AAAD8wAAAAAAAAACAAAAAAAAAAEAACJfAADELwAAA+kAACJfYAABlkwyRUQAAnvWAALK7AAA'
        'ASQAAG8kAABypAACxuwAAobsAADY5Eq4AAQAANjoZgAANAAA2uhKuAAEAADa7GcA/noAABnU'
        'YQAAEgAAGdg7QAEkAAADNkotAecAAAM6ZgD9RAAAC9ggLQJeAAAL3LC8AAAAAAuusDwACQAA'
        'C7JnAAECAACa1kotAd4AAJraZgBKrAAAAepKLQHmAAAB7mcAAD4AAPfqBgUICAAA81ZI5+D+'
        'AAFhckJtAU4AAWF2Q+0BoAABZERhAKZ2AAFkSAZAACAAAWNYUkAvAAABY1xD7QGgAAFj+NBB'
        'UkAAAPhKYQACjAAA+NgvADIAAAD5jEjnAPAAAPoUSi0B2wAAE5ZCLQHEAAABRmEAEloAAAFK'
        'YQAiSAAAFOxwAAZCAAAU8AAs4Ur/////AAFhnE65AAATigABYbYgeQABwQQAAWR4QfkAAWSG'
        'AAFj/EH5AAHBDP////8AAAEAAJD0wgAAAcT////+/////wAPALUADgANASYAkwAOABoAKAC1'
        'AAYAJwAtALUADgAsSOd/fkP5AAJ6rnAGIthRyP/8DLkAAB3AAAJ6xmUABk4meQACerJB+v5k'
        'IBhrDCIYsrMIAGYABj5g8CZ5AAJ6tkH6/4ogGGsMIhiyswgAZgAGJGDwJnkAAnqyQfr/RCAY'
        'axgyGLJzCABmAAYKIhjSi7KzCAJmAAX+YOQgOQACerrQvAAERsAgS9H8AAHAvLCQZgAF4iPA'
        'AAJ7WiA5AAJ6utC8AAD0ACBL0fwAAcDQsJBmAAXCI8AAAmoSIDkAAnqy0LwAAAYCI8AAAnrK'
        'IDkAAnqy0LwAAWXcI8AAAnrOIDkAAnqy0LwAABcSI8AAAnrSIDkAAnqy0LwAABUOI8AAAnrW'
        'IDkAAnqy0LwAABUaI8AAAnraIDkAAnqy0LwAABjOI8AAAnreIDkAAnqy0LwAABmuI8AAAnri'
        'IDkAAnqy0LwAABnoI8AAAnrmIDkAAnqy0LwAABtuI8AAAnrqIDkAAnqy0LwAAA/II8AAAnru'
        'IDkAAnqy0LwAAOXYI8AAAnryIDkAAnqy0LwAAOJyI8AAAnr2IDkAAnqy0LwAAOKGI8AAAnr6'
        'IDkAAnqy0LwAAOKqI8AAAnr+IDkAAnqy0LwAAPNWI8AAAnsCIDkAAnqy0LwAAQq8I8AAAnsG'
        'IDkAAnqy0LwAAACAI8AAAnsKIDkAAnqy0LwAAACyI8AAAnsOIDkAAnqy0LwAAAM+I8AAAnsS'
        'IDkAAnqy0LwAAAviI8AAAnsWIDkAAnqy0LwAAAu2I8AAAnsaIDkAAnqy0LwAAAy2I8AAAnse'
        'IDkAAnqy0LwAAJreI8AAAnsiIDkAAnqy0LwAAAHyI8AAAnsmIDkAAnqy0LwAAAIuI8AAAnsq'
        'IDkAAnqy0LwAAPfqI8AAAnsuIDkAAnqy0LwAANkeI8AAAnsyIDkAAnqy0LwAANpoI8AAAns2'
        'IDkAAnqy0LwAAY0WI8AAAns6IDkAAnqy0LwAAcPkI8AAAns+IDkAAnq20LwAAAkEI8AAAntC'
        'IDkAAnq20LwAAAoEI8AAAntGIDkAAnq20LwAAAIgI8AAAntKIDkAAnq20LwAAASkI8AAAntO'
        'IDkAAnq20LwAAEwsI8AAAntSIDkAAnq20LwAAEyII8AAAntWIDkAAnqy0LwAABOiI8AAAnte'
        'IDkAAnqy0LwAACOUI8AAAntiIDkAAnqy0LwAAB8QI8AAAntmIDkAAnqy0LwAAAP4I8AAAntq'
        'IDkAAnqy0LwAAMpiI8AAAntuIDkAAnqy0LwAACGkI8AAAntyIDkAAnqy0LwAAAmiI8AAAnt2'
        'IDkAAnqy0LwAAA9UI8AAAnt6IDkAAnqy0LwAABeYI8AAAnt+IDkAAnqy0LwAABKcI8AAAnuC'
        'IDkAAnqy0LwAABOKI8AAAnuGIDkAAnqy0LwAATwQI8AAAnuKIDkAAnqy0LwAATvqI8AAAnuO'
        'IDkAAnqy0LwAAA+II8AAAnuSIDkAAnqy0LwAAAFOI8AAAnuWIDkAAnqy0LwAAcZiI8AAAnua'
        'IDkAAnq20LwAAAg4I8AAAnueIDkAAnq20LwAAEScI8AAAnuiIDkAAnqy0LwAAMZ8I8AAAnuu'
        'IDkAAnqy0LwAAMWEI8AAAnuyIDkAAnqy0LwAANI6I8AAAnu2IDkAAnqy0LwAAb20I8AAAnu6'
        'IDkAAnqy0LwAAWFyI8AAAnu+IDkAAnqy0LwAAPhKI8AAAnvCIDkAAnqy0LwAAPjYI8AAAnvG'
        'IDkAAnqy0LwAAPmMI8AAAnvKIDkAAnqy0LwAAPoUI8AAAnvOIDkAAnqy0LwAABOWI8AAAnvS'
        'M/wAAQACfAoz/AADAAJ8DCA5AAJ6wtC8AAAAACPAAAJ7piA5AAJ6wtC8AAABACPAAAJ7qmEA'
        'ARAieQACerLT/AAA2OQy/E75IvwAAAg+MrxOcSJ5AAJ6stP8AADa6DL8Tvki/AAACFIyvE5x'
        'InkAAnqyQ+kZ1DL8Trki/AAACNoyvE5xInkAAnqyQ+kDNjL8Tvki/AAACRQyvE5xInkAAnqy'
        'Q+kL2DL8Tvki/AAAfnoyvE5xInkAAnqyQ+kLrjL8Tvki/AAACPYyvE5xInkAAnqy0/wAAJrW'
        'MvxO+SL8AAAJiDK8TnEieQACerJD6QHqMvxO+SL8AAAJaDK8TnEieQACerJD6QFGMvxO+SL8'
        'AAAqDjK8TnEieQACerJD6RTsMvxO+SL8AAAg1DK8TnFwAGAOQfoYjyAIYAZB+hhgIAhM337+'
        'TnUkeQACeq5B+hijTqoAJLC8AAAwAGYOQfoYk0P5AAAjLE6qAAhOdUjn//hhABM0TN8f/y85'
        'AAJ7Mk51KHkAAnrOTpRhABGoYQARvCB5AAJ7QiJ5AAJ7Sih5AAJ68k6UYQABJFD5AAJ72GEA'
        'BJJKQGcssHwAAmcGYQABjmAEYQAg+EpAZuRKOQACe9hnCFH5AAJ72FiPLzkAAnsOTnVhAAEU'
        'YQARQEo5AAJ72GcOUfkAAnvYLzkAAns2TnUvOQACewpOdUo5AAJ71mYMSHoADC85AAJ65k51'
        'cDw7QAEkTnWwPAAJZhBKOQACe9ZmCC85AAJ7Hk51LzkAAnsaTnVKLQHnZwgvOQACewpOdUo5'
        'AAJ71mYILzkAAnsSTnVhABDGYQAKwko5AAJ8TGYAdQ5KQGcOsHwAAmYA/zJhACA8YARhAADG'
        'SkBmAP8iLzkAAnsOTnVKLQHmZwpKbQGUZgxR7QHmLzkAAnsqTnUvOQACeyZOdUptAZRnDEot'
        'Ad5mBi85AAJ7Ik51SjkAAnvXZiQz7QFMAAJ74DPtASAAAnviIHkAAnq+Q/kAAu70YVBQ+QAC'
        'e9dOdUo5AAJ712c+QfkAAu70InkAAnq+YTI7eQACe+IBIDA5AAJ74LBtAUxnEDtAAUxhABAK'
        'KHkAAnreTpRR+QACe9ZR+QACe9dOdTA8CHEi2FHI//xOdWEaSkBrFEH5AALNLGEAXWhR+QAC'
        'e+RhfHAATnVhAA/IMDkAAnvca2RhAAaGSioAPGdaYQAHfiR5AAJ6rkH5AAJ8ak6qACSwvAAA'
        'IchmPkH5AAJ8akP5AALNLE6qAAhB+QAC7GxhAAJMZiJB+QACzSxhdEpAaxYyOQACzZTgWUH5'
        'AALsdGEAAYxmAk51YQAPTnD/TnUzwAACfF4oeQACeupOlEH5AALNLCJ5AAJ6vmEA/0QwOQAC'
        'fF6wbQFMZww7QAFMKHkAAnreTpRQ+QACe9YwLQEgKHkAAnriTpQoeQACetpOlE51DJBGT1JN'
        'ZnoMqAAAIcAABGZwDKhMMkxWAAhmZgyoTDJMSAAMZlwMqAAAAEoAEGZSDKhMMk1IAF5mSAyo'
        'AAAABgBiZj4MqEwyTVAAbGY0DKgAAB7MAHBmKnIAEigAaeFJEigAaLJ8AAdkGHAAECgAZ+FI'
        'ECgAZrB8AAxkBmEIZgJOdXD/TnVI5/7AQ+gALHwHdAAUKQAB4UoUEbR8ADNiOlSJUc7/7CJ5'
        'AAJ6stP8AAHFouVJOjEQAJp8ABbpTTwxEALnTpx8AMBD6ABKOAVhEmYIVIk4BmEKYAJwAUzf'
        'A39OdSBJYToyAEHpAARhMjQAQekACGEqNgBKQmsgskJtHLZBbRi2RG4UMAGQQsB8AA9mCjAD'
        'kEHAfAAPTnVwAU51cAAQKAAB4UgQEE51SOf/wEP6AI5+AB4xAAAieQACerLT/AABxaLlSTox'
        'EADpTdp8AgA8MRAC507cfAIAeD9hUrB8//9nOrBHZEBhRrB8/gBtOLBFbjRyD8JAZi5hNLB8'
        '/gBtJrBGbiJyB8JAZhxhIrB8AChiFGEasHwAKGIMUYhQiFHM/7qwAGACcAFM3wP/TnVwABAo'
        'AAHhSBAQVIhOdQ4ODRESDgwPDhcNEgyQTDJCT2YIDKgAAAKAAAROdTItASxnKDAtASSQQSB5'
        'AAJ7OrBoAEpvDjItASTiSbBBbghwAk51cANOdXABTnVwAE51YQAM7mEAAmZhAAyQYQAFDGEA'
        'DKhhAAzQE/wAAQACe9lhAAF4YQBy8mEAc7xKQGoAAQKwfP/+ZySwfP/9ZwAAsLB8//tm0kH6'
        'D5lKeQACe9pnBEH6D7ZhAHReYLwwATICsnwAFGWysnwAgGQqknwAFEjBgvwADDQ5AAJ73sT8'
        'AAnUQbR5AAJ72mSOM8IAAnvcYQAErGCCsnwAjGQA/3ywfACgZBJKeQACe95nAP9sU3kAAnve'
        'YB40OQACe95SQjYCxvwACbZ5AAJ72mQA/0wzwgACe94+OQACe97O/AAJYQB5WGEADCRhAARW'
        'YAD/LLI8AANnsLI8AARnvHD/sjwAAWcKcAGyPAACZgD/Dj45AAJ73GsA/wTeQGsA/v6+eQAC'
        'e9pkAP70YQB5EGEABBJgAP7osHwAAmcqsHwAA2c0sHwABGc0sHwABWcKUkBCOQACe9lOdUI5'
        'AAJ72WEAC3RwAE51YQAGbkpAawRwAk51kchgCmEAdkZgBGEAdHgvCCh5AAJ6+k6UYQADkiAf'
        'ZwD+iiBAYQBzImAA/oBwGzI5AAJ73GsQMAFhAAIScABKKgA8ZgJwA051AAgAjgBgAHAAAB6Y'
        'AAAdRABwAI4AYABlAAAfggAAHWAA2ACOAGAAbgAAHp0AAB18AAgAogBgAHIAAIfcAAAdkQBw'
        'AKIAYAB/AABfmgAAHbkA2ACiAGAAEQAAH4cAAB3Y//8ACACiAGAAcgAAIDgAAB33AHAAogBg'
        'AGUAAB+CAAAeEADYAKIAYAARAAAgPwAAHiP//wAIAKIAYAANAAAeoQAAHkQA2ACiAGAAEQAA'
        'HqgAAB5t//9CeQACe9oz/P//AAJ8XCA8AABAAEH6DSRD+QAChuwkeQACeq5OqgAUM8AAAnxg'
        'SfkAAobsU3kAAnxga2YgTEoYZvwjyAACfGYsCJyMU4a8fAAFZUa8fAAfYkBD6P/7DBkALmY2'
        'EBmAPAAgsDwAbGYqEBmAPAAgsDwAdmYeEBmAPAAgsDwAbGYSYQB0bGYMDHkCAAACe9pkAmE+'
        'KHkAAnxmYJIwOQACe9xqAnAAsHkAAnvaZQgwOQACe9pTQDPAAAJ73HIASkBrCEjAgPwACTIA'
        'M8EAAnveTnV4ADo5AAJ72rhFZB42BNZF4kswA2FKIkxhAAF6SkBuBjgDUkRg4joDYN5B+QAC'
        'xuwwOQACe9rQQEPwAADYREXwQACzymcGM2EAAmD2QfkAAobsIAyQiDSAUnkAAnvaTnVB+QAC'
        'xuzQQDAwAABB+QAChuzQwE51LwFyADIAgvwACbJ5AAJ8XGcMSOf/3jABYRZM33v/SEHC/ABA'
        'RfkAAsrs1cEiH051PwDA/AAJPgBF+QACyux6CL55AAJ72mQYMAdhnkjnBSBhFkzfBKBF6gBA'
        'UkdRzf/iM98AAnxcTnUiSnAPQplRyP/8Q9IS2Gb8YQAAiCZ5AAJ6rkH5AAJ8ak6rACSwvAAA'
        'IchmbEH5AAJ8akP5AALNLE6rAAhB+QACzSxhAPmKSkBrTjVAADhB+QAC7GxhAPtEZj5B+QAC'
        '7HQwKgA4MjkAAs2U4FlhAPqMZiZB+QACzUBD6gAgcBcS2FHI//wVeQACzXAAOhV5AALNcgA7'
        'UOoAPE51QfoK6EP5AAJ8ahLYZvwTfAAv//9B0hLYZvxOdUjnQMAQGLA8AEFlCrA8AFpiBNA8'
        'ACASGbI8AEFlCrI8AFpiBNI8ACCwAWYISgBm1HAAYAhiBHD/YAJwAUzfAwJOdWEAB/xB+gqN'
        'MjwAAGEACExhAAkmYQD8akH6/IJD+gqDYQBtaHAAMjwAFDQ8AUA2PAB4KHkAAnr+TpRhAAfC'
        'SnkAAnvaZhxB+g0WMjwANGEACApB+g0hMjwAQGEAB/5gAAFoPjkAAnvezvwACXwAvnkAAnva'
        'ZAAAzDAHYQD+JHQBvnkAAnvcZgJ0ADPCAAJ8ZDIGwvwADNJ8ABQzwQACfGJwCGEAB3hKKgA8'
        'Z2JB6gAgdBg2PADAYQAH7DA8AMwyOQACfGI0OQACfGRhAAdQcAAQKgA6YQAIFBb8ADpwABAq'
        'ADuwfAAKZAQW/AAwYQAH/DA8APQyOQACfGI0OQACfGRhAAcaMCoAOGEACAhgKEHSdB82PADA'
        'YQAHjDA8AMwyOQACfGI0OQACfGRhAAbwQfoMXmEAByhSR1JGvHwACWUA/y4MeQAJAAJ72mN8'
        'SnkAAnveZxRwCDI8AIB0AWEABr5B+gw0YQAG9jA5AAJ73lJAwPwACbB5AAJ72mQWMDwA+DI8'
        'AIB0AWEABpRB+gwVYQAGzDI8AIBhAAaaQfoMDGEABrwwOQACe95SQGEABz5B+gv+YQAGqHAA'
        'MDkAAnvaUECA/AAJYQAHJGAAB25hAAWyYQAGLDI8ABxhAAZYIHkAAns6dBhhAAacMjwAQGEA'
        'BkRB+gvBYQAGZjAtASxhAAbsQfoLvGEABlYwLQEkYQAG3EH6C7FhAAZGMjwAVmEABhRhAPiS'
        'E8AAAnxGPgBmCkH6C51hAAYoYBZB+guqYQAGHjAHYQAGpkH6C6NhAAYQMjwAZmEABd5B+guZ'
        'YQAGACB5AAJ7OjAoAEphAAaAQfoLlmEABephAAbCQfr6hEP6C5pwAGEAawZhAAUYE/wAAgAC'
        'e9lhAGw4SkBr8EI5AAJ72T8AYQAFEjAfQfoAChAwAABIgE51AAIBAEI5AAJ8EEK5AAJ8Qih5'
        'AAJ6+k6UYQABdGEABPoT/AAEAAJ72WEAa+5KQGdqsHwAAWd4sHz//GdysHz//WcQsHz//mbY'
        'MAEyAmEAAOxgzkH5AAJ8CnQMcP+yPAADZzJwAbI8AARnKkH5AAJ8DHQHcP+yPAABZxpwAbI8'
        'AAJnEjABYTJnmEK5AAJ8QmEAAVhgjGEAANxghmEAAkZKQGsA/35COQACe9lwAE51QjkAAnvZ'
        'cP9OdbA8AAhnKrA8AH9nJGE4ZjJyABI5AAJ8ELJ8ABRkJEH5AAJ8EhGAEABSOQACfBBgDko5'
        'AAJ8EGcKUzkAAnwQcAFOdXAATnWwPAAtZyqwPABfZySwPAAwZSSwPAA5YxiwPABBZRiwPABa'
        'YwywPABhZQywPAB6YgYAPAAETnUCPAD7TnVB+QACfAp0DLJ8AEZlKLJ8AFJlFEH5AAJ8DHQH'
        'snwAWmUUsnwAZmQOcgGwfACwZAJy/zABYAJOddBQagQwAlNAsEJlAnAAMIBhAAO2QrkAAnxC'
        'YFphAAO6QfoIOTI8AABhAAQKMjwAEnQAYQAD4kH6CC1hAAP6QfoIQjI8ADBhAAD0QfoIOzI8'
        'AEhhAADoQfoINTI8AFxhAADcYQAErmEOQfr4oEP6CDVwAGAAaPAwPABwMjwAMDQ8ANA2PAA4'
        'KHkAAnr+TpRwADI8AHQ0PAFAdgwoeQACev5OlGEAAzQyPAAwYWgyPABIYQAAlkH6B+FhAAN8'
        'MDkAAnwKYQAEKEH6B9NhAANqMjwAXGF0QfoHwWEAA1xhdDACYQAD4kH6B7lhAANMMANhAAPU'
        'QfoHp2EAAz4gOQACfEJnDjI8AHRhAAMEIEBhAAMoYAAEAGEyQfkAAnwSdAAUOQACfBBgBhAY'
        'YQADFlHK//gW/ABfQfoHXGAAAvxwKHQBYQACtGAAAvAwPABwdAFgAAKmIHkAAnqy0fwAAcWi'
        'MDkAAnwM5Ug0MAAANjAAAk51QfoHWko5AAJ8EGd+QfoHbQx5AgAAAnvaZHBhfGEAAKBB+gd2'
        'vnkAAnvaZV5B+QACfChD+QACfGphAG82JHkAAnquQfkAAnxqTqoAJEH6B0pKgGY2YQAAjGEA'
        'AeYkeQACeq4gPAAAIchB+QACfGpD+QACzSxOqgAMYQBvNmEA9z5hPGEAbwRwAE51I8gAAnxC'
        'YQD+dHD/TnVB+QACfBJD+QACfChwABA5AAJ8EGACEthRyP/8QfoGbBLYZvxOdX4AvnkAAnva'
        'ZBgwB2EA+ChD+QACfChhAPlSSkBnBFJHYOBOdUH5AALNLDA8CHFCmFHI//xB+QACzSwgvEZP'
        'Uk0hfAAAIcAABCF8TDJMVgAIIXxMMkxIAAwhfAAAAEoAEEPoABRF+QACfBJwABA5AAJ8EHIX'
        'dCBTQGsCFBoSwlHJ//RD6AAsRegAPEf6AJhwBxKbVIkU/AAKUcj/9hF8AAUARBF5AAJ8CwBI'
        'YQD+eJR8ABbpSudLlnwAwEH5AALNLBFCAFLgShFCAFMRQwBU4EsRQwBVIXxMMk1IAF4hfAAA'
        'AAYAYhF5AAJ8CwBmEXkAAnwNAGghfEwyTVAAbCF8AAAezABwQ+gfQCL8TDJCTyL8AAACgDA8'
        'AT8y/P//Ucj/+mAATfASFhgzExQVESh5AAJ69k6UKHkAAnr6TpRhAFaOcAcoeQACeu5OlE51'
        'IHkAAntGInkAAntOKHkAAnryTpROdSB5AAJ7QiJ5AAJ7Tih5AAJ68k6UTnUreQACe1ICHmAI'
        'K3kAAntWAh47fAAVAYYoeQACetJOlE51O3wANAFcKHkAAnrKTpROdUf5AAJ+7Bb8AAdOdRb8'
        'AAdCG0IbFvwAoBb8AGROdWHsFvwABBb8AAEWwBbBFvwACBbCTnUvAnQBYQQkH051FvwAB0Ib'
        '4kkWwRb8AKAW/ABkFvwABRb8AAgWwk51YdYQGGcEYQRg+E51sDwAIGUQsDwAI2cKsDwAemIE'
        'FsBOdRb8ACBOdSJLU0JrChAYZwZh2FHK//i3yWcMDCsAIP//ZgRTi2DwTnVI5wgIKHkAAnsu'
        'IktTQmsgEBhnHGGseAAYK///mHwAIBg0QACWRGsGUcr/5mACU4u3yWcMDCsAIP//ZgRTi2Dw'
        'TN8QEE51wLwAAP//dACA/AAKSEDQPAAwPwBSQkJASEBKQGbqMB8WwFNCZvhOdSB5AAJ7PudI'
        '0MAQGLA8AGFlCrA8AHpiBJA8ACBhAP82dAdgAP9MQhNB+QACfuwoeQACewJOlE51IHkAAnta'
        'RfkAAnyqR/rl8n4DTJsAcFSLYT5Rz//2dB0yPACycARhAADKUkCwfABDZvRSQbJ8AMRm6kX5'
        'AAJ8qkf65b5+A1iLPBs4Gzo8ALVhKFHP//JOdS8HfgswBDhGMgVhWBTCUkBTTLj8AABm8FJF'
        'Uc//6C4fTnUvB34LMAQ4RjIFFBq0PAAdZwJhZFJAU0y4/AAAZupSRVHP/+IuH051NgHG/AAo'
        'IkjTwzYA5kvSwzYARkPGfAAHTnVh5HQAByl9AGcECMIABAcpXcBnBAjCAAMHKT6AZwQIwgAC'
        'BykfQGcECMIAAQcRZwQIwgAATnVhrggCAABnBAfRYAIHkQgCAAFnBgfpH0BgBAepH0AIAgAC'
        'ZwYH6T6AYAQHqT6ACAIAA2cGB+ldwGAEB6ldwAgCAARnBgfpfQBOdQepfQBOdUxldmVscwBD'
        'dXN0b20gTGV2ZWxzAENsaWNrIGEgbGV2ZWwsIG9yIHVzZSB0aGUgY3Vyc29yIGtleXMAVGhl'
        'cmUgaXMgbm8gbGV2ZWwgeWV0OiBtYWtlIG9uZSB3aXRoIE5ldwBBIGRhbWFnZWQgZmlsZTog'
        'b25seSBSZW5hbWUgb3IgRGVsZXRlAFBsYXkgdGhlIHNlbGVjdGVkIGxldmVsIChQKQBFZGl0'
        'IHRoZSBzZWxlY3RlZCBsZXZlbCAoRSkATWFrZSBhIG5ldyBsZXZlbCAoTikAR2l2ZSB0aGUg'
        'c2VsZWN0ZWQgZmlsZSBhbm90aGVyIG5hbWUgKFIpAERlbGV0ZSB0aGUgc2VsZWN0ZWQgZmls'
        'ZSAoRGVsKQBCYWNrIHRvIHRoZSB0aXRsZSBzY3JlZW4gKEVzYykAUGxheSB0aGUgbGV2ZWwg'
        'YWdhaW4gKFIpAEVkaXQgdGhlIGxldmVsIChFKQBCYWNrIHRvIHRoZSBsaXN0IG9mIGxldmVs'
        'cyAoRXNjKQBXcml0ZSB0aGUgbmV3IGxldmVsIGFuZCBlZGl0IGl0IChSZXR1cm4pAEJhY2sg'
        'dG8gdGhlIGxpc3Qgd2l0aG91dCBhIG5ldyBsZXZlbCAoRXNjKQBQbGF5AE5ldwBDcmVhdGUA'
        'Q2FuY2VsAE5ldyBMZXZlbABFZGl0b3IgVjEuMCBieSBUaW1vIEhlaW1vbmVuAEZpbGUAU3R5'
        'bGUAU2l6ZQAubHZsADwgIAAgID4AIHggAFR5cGUgYSBuYW1lLiBDdXJzb3Iga2V5czogc3R5'
        'bGUgYW5kIHNpemUAVHlwZSBhIG5hbWUgZm9yIHRoZSBmaWxlIGZpcnN0AFRoZSBsaXN0IGlz'
        'IGZ1bGw6IDUxMiBsZXZlbHMAVGhlcmUgaXMgYSBsZXZlbCBvZiB0aGlzIG5hbWUgYWxyZWFk'
        'eQBFZGl0AEJhY2sAVGhlcmUgYXJlIG5vIGxldmVscyBpbgB0aGUgTGV2ZWxzIGRpcmVjdG9y'
        'eSB5ZXQAZGFtYWdlZAA8IFByZXZpb3VzAE5leHQgPgBQYWdlIAAgb2YgAFlvdSBzYXZlZCAA'
        'IG9mIAAgTGVtbWluZ3MATm8gTGVtbWluZ3Mgd2VyZSBzYXZlZABHcmFkZSAAIG9mIDMAQmVz'
        'dCBncmFkZTogdXAgdG8gACBsb3N0AFJlcGxheQBMZXZlbHMAUmVwbGF5IGl0LCBlZGl0IGl0'
        'LCBvciBiYWNrIHRvIHRoZSBsaXN0AEVkaXRvcjogdGhpcyBpcyBub3QgdGhlIHN1cHBvcnRl'
        'ZCBnYW1lAEVkaXRvcjogbm90IGVub3VnaCBjaGlwIG1lbW9yeSBmcm9tIHRoZSBzbGF2ZQBk'
        'YXRhL0VkaXRvclRpbGVzANR8ACwwAtBD0nwAgHYA4knjUwgCAAhnAlhDCAAACGcCVEPhSIZA'
        '4UqCQjABSEAwA0zfAA5OdQAAAAAAAAAEBAQEBAAECgoKAAAAAAofCgofCgAEDxQOBR4EGRoC'
        'BAgLEwwSFAwVEg0EBAgAAAAAAgQICAgEAggEAgICBAgAFQ4fDhUAAAQEHwQEAAAAAAAEBAgA'
        'AAAfAAAAAAAAAAAABAECAgQICBAOERMVGREOBAwEBAQEDg4RAQIECB8eAQEOAQEeAgYKEh8C'
        'Ah8QEB4BAR4OEBAeEREOHwECBAgICA4REQ4REQ4OEREPAQEOAAQAAAQAAAAEAAAEBAgCBAgQ'
        'CAQCAAAfAB8AAAgEAgECBAgOEQECBAAEDhEXFRcQDw4RER8REREeEREeEREeDxAQEBAQDx4R'
        'ERERER4fEBAeEBAfHxAQHhAQEA8QEBcREQ4REREfERERDgQEBAQEDgEBAQEREQ4REhQYFBIR'
        'EBAQEBAQHxEbFRURERERGRUTERERDhERERERDh4RER4QEBAOERERFRINHhERHhQSEQ8QEA4B'
        'AR4fBAQEBAQEERERERERDhERERERCgQREREVFRsREREKBAoRERERCgQEBAQfAQIECBAfDggI'
        'CAgIDhAICAQCAgEOAgICAgIOBAoRAAAAAAAAAAAAAB8IBAAAAAAAAAAOAQ8RDxAQHhERER4A'
        'AA4QEBAOAQEPERERDwAADhEfEA8GCAgeCAgIAA8REQ8BDhAQHhEREREEAAwEBAQOAgAGAgIS'
        'DBAQEhQYFBIMBAQEBAQOAAAaFRUVEQAAHhEREREAAA4REREOAB4RER4QEAAPEREPAQEAABYY'
        'EBAQAAAPEA4BHggIHggICAYAABEREREPAAAREREKBAAAEREVFQoAABEKBAoRABEREQ8BDgAA'
        'HwIECB8DBAQIBAQDBAQEBAQEBBgEBAIEBBgAAAkWAAAAAPQB/wABAAIAAYAAAAGCAAABhAAA'
        'AYYAAAGIAAABigAAAYwAAAGOAAABkAAAAZIAAAGUAAABlgAAAZgAAAGaAAABnAAAAZ4AAAEC'
        'AAAAkgA4AJQA0AEIAAABCgAAAOAAAADiAAAA5AAAAOYAAADoAAAA6gAAAOwAAADuAAD2Af8A'
        'AQBCAP////4AAAIjA0UEaAmrABIN3giJD8MDag5VBcYOtAAAAAAP/0H6/1YieQACe6YwPABD'
        'MthRyP/8InkAAnumQ+kAXiA5AAJ7qnIDSEAygEhAM0AABFCJ0LwAAAcwUcn/7E51SOf/4EpC'
        'bwAAjkpDbwAAiDoA2kJTRXz/PgDOfAAP7m4+Bc58AA8KRwAPdP/vauhI6E2aQGYCzEIgeQAC'
        'e6rC/AAo0cHQQNDAU0MiSH4DMgQkSeJJZBaNWjAFZypTQGAENPz//1HI//qFUmAaMAZGQMFa'
        'MAVnEFNAYAJCWlHI//wwAkZAwVJD6QcwUc//xEHoAChRy/+2TN8H/051SOf/4LA8ACBjYLA8'
        'AH5iWsB8AP+QfAAgwPwAB0H6+8bQwCJ5AAJ7qsT8ACjTwjAB6EjQQNLAfBvCfAAPnEF6BngA'
        'GBjtrCRJMgN+A+JJZASJkmAGIARGgMGSReoHMFHP/+xD6QAoUc3/2EzfB/9OdUjnyIBTRGsM'
        'EBhnCGGCXEFRzP/2TN8BE051Lwhw/1JAShhm+iBfTnVI5/+AMBEyKQACNCkABHYMeAK6fAAB'
        'ZxC6fAAFZwq6fAACZgZ4CWACeANhAP6geAR2AWEA/ph0AXYMYQD+kHgF0GkABFNAYQD+hDAR'
        '0nwACzQpAAR2AWEA/nR2Brp8AANmAnYHunwAAmYCdgggaQAIYYDA/AAGU0AyKQAEkkDiQdJR'
        'NCkAAlRCeChhAP9MunwABGU2eAgwEVNAMikAAlNBNCkABFRCdgFhAP4i0nwADWEA/hoyKQAC'
        'dAF2DGEA/g7QaQAEUkBhAP4ETN8B/051SOf4gDARMikAAjQpAAR2DHgBYQD96DApAAZhABWk'
        'MhE0KQACVEI4KQAESMSI/AAGYQD+1kzfAR9OdUjn+ABwADICNDwBQHYIeAFhAP2wTNcAH3IE'
        'eDRhAP6wTN8AH051cAByADQ8AUB2LngBYQD9jkH5AAAABHAfMPz//1HI//pQ+QAAAEhQ+QAA'
        'AElQ+QAAAEdCOQAAAEZKOQAAAEZmwCJ5AAAAAEX5AAAABDARaywwKQAGYQAT2EppAAZqDko5'
        'AAAAR2cOYQD/OGAIulJnBGEA/l40xUPpABBg0EI5AAAAR0o5AAAASGdIQjkAAABISjkAAABL'
        'ZhBB+QAAAEx0HHYGYQD/NmAQMDwBEnIcdCp2CHgBYQD85ko5AAJ75mcSQfoa/TI8ARJ0HHYM'
        'eAdhAP3YSjkAAABJZxpCOQAAAElB+QAAALh0JjY5AAAARGEA/uphAk51QfkAAAC4YQD9xHIz'
        'kkBB+gF0YQD9uLJAbAxB+gF+YQD9rLJAbRQ4AMD8AAYyPAE8kkB0JnYJYQD9ek51Mi0BCJJ8'
        'AMprQDAtAQYieQAAAABKUWsySmkABmsmsFFlIjQR1GkABLBCZBiyaQACZRI0KQAC1HwADLJC'
        'ZAYwKQAGTnVD6QAQYMpw/051InkAAAAASlFrDLBpAAZnCEPpABBg8JPJTnVI58DAMgBD+QAA'
        'ALhwABLYZwpSQLB8ADVl9EIRsnkAAABEZhhB+QAAALhD+QAAAO4QGLAZZgZKAGb2YBwzwQAA'
        'AERB+QAAALhD+QAAAO4S2Gb8UPkAAABJTN8DA051QfkAAABMQ/kAAACCEBiwGWYUSgBm9hA5'
        'AAJ75rA5AAAASmYCTnVB+QAAAExD+QAAAIIS2Gb8E/kAAnvmAAAASlD5AAAASE51Fthm/FOL'
        'TnVI5+AAwLwAAP//dACA/AAKSEDQPAAwPwBSQkJASEBKQGbqMB8WwFNCZvhCE0zfAAdOdVYx'
        'LjAgYnkgVGltbyBIZWltb25lbgBWMS4wIGJ5IFRpbW8gSC4AYQDgqkpAa3Q/AEH5AALNLEP5'
        'AAABJGEA4GxB+QACfGpD+QAAIuwS2Gb8UfkAAnvmUPkAAnvkYQBRMEH5AALNLGEAPcQzwQAA'
        'pexnJkH5AALNLEP5AAABJGEA4CpB+QACzSxD+QAApf5hAOAaUPkAAnvmMB9hAOCucABOdXD/'
        'TnVKOQACe+RmFC85AAJ7li85AAJ7Yi85AAJ7Xk51Si0Bz2cIKHkAAnseTpQT/AADAAJ72VH5'
        'AAJ761H5AAJ8D0H6Aj4rSAIiM/wAEAAAbvphAAKAO3wA9wFWYQADLGEADGxKOQACfA5nMlH5'
        'AAJ8DjP5AACl7gAAduYz+QAApfAAAHboUPkAAHbqUfkAAnvzUfkAAG8WYQA7CGB0QnkAAG8E'
        'YQA9REJ5AAJ8CGEAEnIz/P//AAJ77Ep5AABvHGcScAGweQAAbxxlAnAAYQAJQGAGcAFhAAlq'
        'UfkAAnvnUfkAAnvoUfkAAnvyUfkAAnvzUfkAAHbqQnkAAnv0M/z//wACe/Yz/P//AAJ7+GEA'
        'GxhhACMGE/wAAAACe+VhAAZwM/z//wAAbwJKOQACfE5nClH5AAJ8TmEADPwoeQACe15OlAw5'
        'AAEAAnvlZwATeAw5AAMAAnvlZwAu/GEAAoIoeQACe2ZOlCh5AAJ7ak6UUO0BySh5AAJ7bk6U'
        'Ue0BySh5AAJ7ck6UKHkAAnt2TpRKLQG8Zg5R+QAAbxYz/P//AAB25GEAA1BhAAN2DDkAAgAC'
        'e+VnUAw5AAQAAnvlZzYMOQAFAAJ75WcyEDkAAnvyZxCwPAABZxRhADeQYQA93GAoYQADgmEA'
        'CPJgHmEAJP5hAChsYBRhAECkYA5hAD5mYQA+tGAEYQAMoGEADQJhAA4WYQD7CGEAT0RQ7QHL'
        'SjkAAnvrZhhKOQACfA9mAED+SjkAAnxNZgBRnGAA/wBhKmEAALQreQACe5ICIih5AAJ7ik6U'
        'O3wAyQFWUfkAAnvkQjkAAnvZYADcDnAPPwAoeQACe4ZOlGEAAKQwH1HI/+5OdS15AAJ7pgCE'
        'sHwABG0qSi0By2ceQi0By0JtAPwiLQHyK20B7gHyK0EB7gptAAEBFmAGO3wABAD8KHkAAnuC'
        'TpRKeQAAbvpnCFN5AABu+mE6TnVhAPdsLXkAAnumAIQgeQACerYxfCTCAQIhfACKAAABxE51'
        'IHkAAnq2IXz////+AcQxfPTCAQJOdSB5AAJ7nmEmYTRB+vcKYBBB+QAAUyxhFmEkQfkAAFMs'
        'InkAAnumRekASFCJYBAieQACerZF6QHEQ+kANE51s8pkOjAZsHwBgGUusHwBvmIoMhg0EXYC'
        'eA96ATwBzEQ+As5EvkZnCGIE1EVgApRF6UzpTVHL/+YyglSJYMJOdTAtAQyQfAAW6UgzwAAA'
        'bvYwLQEO50iQfADAM8AAAG74MC0A/sB8//CweQAAbvZvBjA5AABu9jtAAP4wLQEAwHz/8LB5'
        'AABu+G8GMDkAAG74O0ABAE51YQAAmko5AAB26mcYUfkAAHbqO3kAAHbmAP47eQAAdugBAGBy'
        'YQAAiDItAP40LQEACAMAAGcQsnwAEG0iknwAEFDsAAFgGAgDAAFnEjAB0HwAELB5AABu9m4E'
        'MgBQ1AgDAAJnELR8ABBtJJR8ABBQ7AACYBoIAwADZxQwAtB8ABCweQAAbvhuBjQAUOwAAztB'
        'AP47QgEAUe0Byk51MC0BFuVIKHkAAnua2MBClE51dgAQLQKvsDwAA2YECMMAALA8AARmBAjD'
        'AAGwPAABZgQIwwACsDwAAmYECMMAA0pDZjQwLQEGMi0BCLJ8AKBkHEpAZgQIwwAAsHwBP2YE'
        'CMMAAUpBZhAIwwACYAqyfAD3ZgQIwwADTnUoeQACe3pOlMB8AP8zwAAAbv6wPABBZQqwPABa'
        'YgSAPAAgM8AAAG78TnVwAAxtAKABCGUCcAGweQAAbwJnMDPAAABvAkpAZhAreQACe6ICHjt8'
        'ABABhmAOK3kAAntSAh47fAAVAYYoeQACe35OlE51YQD4rjPAAABvADA5AABu/GcEYQABakot'
        'Ab5nGlH5AABvFgxtAKABCGUAA9wwOQAAbwBrJGAkSi0BvGcKDG0AoAEIZQAD1EotAcJnDAxt'
        'AKABCGQEYAACEE51YQALULp8AANnCj8AYQACSjAfYAJOdbB8ACxnAE3isHwAHGQANK6wfAAB'
        'ZwABgLB8AAJnAAF8sHwAA2cAAXiwfAAEZwBNhrB8AAVnAEzysHwABmcATQiwfAAHZwAHprB8'
        'AAhnAAgSsHwACWcADhqwfAAKZwABmLB8AAtnAAGksHwADGcAAaqwfAANZwABqgw5AAMAAnvl'
        'ZxqwfAAOZwAOHLB8AA9nAA4msHwAEGcADixgGLB8AA5nACmasHwAD2cAKaCwfAAQZwApsLB8'
        'ABFnAAfcsHwAEmcAB9iwfAATZwAH2LB8ABRnACkwsHwAFWcAIsqwfAAWZwAi6LB8ABdnACLm'
        'sHwAGGcAIuSwfAAZZwAi4rB8ABpnACMSsHwAG2cAIw5OdbA8AHRnAACCsDwAb2d+sDwAbGd8'
        'sDwAZWcATIywPAB1ZwBL5rA8AHNnUrA8ABFnAAcisDwAbWcAAOIMOQABAAJ78mcAIKAMOQAC'
        'AAJ78mcAMtKwPABwZwANCrA8AHJnAACIsDwAa2cAAJSwPABkZwAAmrA8AGlnAACaTnVKOQAC'
        'e+ZmAAZaTnVwAGAGcAFgAnACsDkAAnvyZ0wTwAACe/JR+QACe/NR+QAAbxZB+g9CUfkAAABL'
        'EDkAAnvyZxRB+itWsDwAAWcKQfpBRlD5AAAASyPIAAAAADP8//8AAG8AUPkAAABGTnVGOQAC'
        'e+dR+QACe+hQ+QAAAEdOdUY5AAJ76FD5AAAAR051RjkAAnvpTnVGOQACe+pOdUYtAetnCih5'
        'AAJ7ik6UTnUoeQACe45OlE51O3wABQFcKHkAAnrKTpROdTAtAQbQbQD+0HwAEOhIMi0BCNJt'
        'AQDSfAAQ5klOdUjnIACwfAABbSQ0LQEMVUKwQm4asnwAAm0UNC0BDldCskJuCkzfAAQAPAAE'
        'TnVM3wAEAjwA+051NgHG7QEM1kDli0H5AAABmNHDTnVI5/iAYa5mIGHitJBnGiCCUPkAAnvm'
        'UPkAAnxHUPkAAG8iUnkAAnvwTN8BH051YQD/ZjPAAABvGDPBAABvGmF0UfkAAG8iInkAAG8S'
        'fAB6ADQZZz7EvAAAA/9KOQACe+dnBHQAYBhKOQACe+lnBAjCAB5KOQACe+pnBAjCABwwOQAA'
        'bwzQRTI5AABvDtJGYQD/cFJFunkAAG8IZbRSRrx5AABvCmWoSjkAAG8iZwRhABrYTnU0OQAA'
        'bwhTQuJCkEIzwAAAbww0OQAAbwpTQuJCkkIzwQAAbw5OdUo5AAJ76GZQUPkAAG8WYAD/REo5'
        'AABvFmc8SjkAAnvoZjRKOQACe+dmFAx5AAEAAG8IZiIMeQABAABvCmYYYQD+fLB5AABvGGYA'
        '/wqyeQAAbxpmAP8ATnVR+QACe+hQ+QAAAEdhAP5WYQD+cGYsYQD+oiQQMALAfAP/Zx5hWAgC'
        'AB5W+QACe+kIAgAcVvkAAnvqUfkAAnvnTnVB+hGOcAxgAATiM8AAAnvs5UhB+QAAU6wgcAAA'
        'cAAQKAACM8AAAG8IECgAAzPAAABvClyII8gAAG8SYCgz/P//AAJ77DPAAABvEDP8AAEAAG8I'
        'M/wAAQAAbwoj/AAAbxAAAG8SSOf8wFD5AAAARyB5AABvEjA5AABvCMD5AABvClNAQ/kAACMs'
        'Mi0BTML8BADTwXYAeAB6ADIYwnwD/2cWUkMUMRAACAIAAGcCUkQIAgABZwJSRVHI/+DYRLhD'
        'UvkAAnvp2kW6Q1L5AAJ76kzfAz9OdQxtAKABCGR6YQD9REo5AAJ76GcIdAF2AWAAAMxhAP5O'
        'InkAAG8SfAB6ADQZZyYwOQAAbwzQRTI5AABvDtJGYQD9LGYQxHwD/0o5AAJ752cCdABhMFJF'
        'unkAAG8IZcxSRrx5AABvCmXAMDkAAG8MMjkAAG8ONDkAAG8INjkAAG8KYGROdUjn8ODpSJBt'
        'AP5rJrB8AWBkIOdJkm0BAGsYsnwAuGISIm0B8sL8ACzTweZI0sBhCGEWTN8HD051IG0CTsS8'
        'AAAD/+2K0cJOdXADJElyBzSYReoALFHJ//hD6SEAUcj/7E516UiQbQD+50mSbQEA6UrnS0jn'
        '/+AgbQHy6EDoQtRAU0I4AToB2kNTRTwEYS48BWEqPARTRVJGvEVuGkpGaxS8fADAZBA+ADY8'
        'gABhKj4CdgFhJGDgTN8H/051SkZrFrx8AMBkED4AvkJuCjY8//9hBlJHYPJOdUpHaxi+fAAW'
        'ZBIyBsL8ACwiSNPBMgfSQdLBYAJOdUjn/2A4ETopIQA8KUIAPiljAEX5AABu5HQAcg8DA2ci'
        'cAADB2cCUEADBmcCWEADBWcCVEADBGcCUkBKMgAAZwIDwlHJ/9gyA7VBRkMcOQAAbvQeOQAA'
        'bvV6AzgRyEPiDmQCiELiD2QCiEEyhEPpIQBRzf/oTN8G/051SOf/wCB5AAJ7nnYAev8+PH//'
        'MBhhSLJFbwQ4AzoBskdsBDwDPgFSQ7Z8ABBl5BPEAABu9BPGAABu9dpHIHkAAnueQ/kAAG7k'
        'dg8wGGEQ0kGyRVPZUcv/9EzfA/9OdXIPwkDoSHQPxEDE/AAG0kLoSMB8AA/A/AAD0kBOdUjn'
        '/+AgbQHy6EDoQtRAU0I4AVREOgHaQ1dFPARhMDwFYSw8BFRGvEVsHkpGa/a8fADAZBQ+ADY8'
        'IABhAP6wPgJ2BGEA/qhg3EzfB/9OdUpGayS8fADAZB4+ADY8Cqq+QmcMYQD+iDY8qqpSR2Dw'
        'xnyqqGAA/nhOdSR5AAJ6riA8AAAhyEH5AAAi7EP5AAABJE6qAAxCrQKqQm0CrlH5AAJ75mEA'
        'QyZH+QAAbqRhABX4Zh5B+g2RYQDxIkH5AAAi7GEA8RhB+QAAbqRwC2AAANgvCEH6KZlhAPEC'
        'IF9hAPD8QfkAAG6kcAxgAAC8SjkAAnvmZzIT/AAAAAJ8T0H6CbBhOEf5AABuLEH6DSRhAPDM'
        'QfkAACLzYQDwwkH6DSdgAPC6YQD/VFD5AAJ76051E/wAAAACe+VgAPkOE/wAAgACe+UjyAAA'
        'AABR+QAAAEsz/P//AABvAFD5AAAARk51YQDvbDPAAABvADA5AABu/LA8AA1mDEo5AAJ8T2YA'
        'RPhgorA8ABFnqLA8AGRmCEo5AAJ8T2eSSi0BvmcKMDkAAG8AagD21E51M8AAAG8GQ/kAAG6k'
        's8hnBBLYZvwz/AAoAABvBE51SnkAAG8EZxZTeQAAbwRB+QAAbqQwOQAAbwZgAO9UMDkAAG8A'
        'a0KwfAAHZihhABS0ZyJH+QAAdmgvCEH6KFlhAO/WIF9hAO/QQfkAAHZocAxgAO8eMDkAAG8A'
        'YQDu+iBpAAxwBmAA7wpB+gyuDDkAAgACe+VmFkH6C8RKOQACfE9nAACQQfpF6WAAAIgMOQAE'
        'AAJ75WYGQfo/KWB2DDkABQACe+VmBkH6P3tgZgw5AAEAAnvlZxAMOQADAAJ75WYYQfonp2AE'
        'QfoLRQxtAKABCGVAQfoMRGA6DDkAAgACe/JnADbkDG0AoAEIZCZKOQACe/JmAB6aQfoKrko5'
        'AAJ752cEQfoKxEo5AAJ76GcEQfoK2nAHYADuWkf5AAAATEo5AAAAS2YAAJAMOQAEAAJ75WdY'
        'DG0AoAEIZFAMOQABAAJ78mcAHKJhAPfSOAA6AUH6C3dhAO7CYQDuxhb8ACwwBWEA7rwW/AAg'
        'FvwAIDAEMgVhAPfGZgphAPf4JBBhPmA2QfoLS2EA7pBgLEH6C1ZhAO6GQfkAAAE4cBciSxIY'
        'ZwYWwVHI//i3yWcMDCsAIP//ZgRTi2DwQhNgAO4UMALAfAP/ZghB+gs3YADuTEH6CxxhAO5E'
        'YQDuSAgCAB5mDggCABxmFkH6Cx1gAO4sQfoLHGEA7iQIAgAcZwhB+gsVYADuFk51LwF6ALB8'
        'AANiEjIAU0GyOQACe/JnAAESYAABArB8AARnAAD6sHwABmIQYQBCGrp8AANnAAD6YAAA5LB8'
        'AAdmDko5AAJ75mcAAORgAADQQfkAAnvnsHwACmcAAL5B+QACe+iwfAALZwAAsEH5AAJ76bB8'
        'AAxnAACiQfkAAnvqsHwADWcAAJSwfAAPZiIMOQADAAJ75WcMSnkAAnvuZwAAjmB6SnkAAnv6'
        'ZwAAgmBusHwAEGYqDDkAAwACe+VnEDI5AAJ77rJ5AABvIGRgYE4yOQACe/qyeQAAcyZkUGA+'
        'sHwAEWcSsHwAKmcMsHwAMWcGsHwALGYEegRgIrB8ABRlHLB8ABxlBmEANQBgBGEAHL66fAAD'
        'ZxhgBEoQZgyweQAAbwBmClJFYAZ6AmACegMiH051SOfgEHYGsHyAAmYMQfkAAG4sdghgAADC'
        'R/kAAG58sHyACGUIYQA1fGAAAKawfIAEZQhhABzSYAAAmLB8gANmQkH6CX9hAOyaMDkAAnvu'
        'UkBhAOyWFvwALdB8ABOweQAAbx5jBjA5AABvHmEA7HxB+uMeYQDsbDA5AABvHmEA7GpgTkp5'
        'AAJ77GswQfoJLmEA7FAwOQACe+xhAOxOFvwAIDA5AABvCGEA7EAW/AB4MDkAAG8KYQDsMmAW'
        'QfoI+GEA7CAwOQAAbxDAfAP/YQDsGkITQfkAAG58TN8IB051QnkAAG8cQnkAAG8eQnkAAnvu'
        'QfkAAGasMDwB3yD8/////1HI//hB+QAAV6wwPAO/QphRyP/8IG0CTgyoTDJCTP/2ZmBViNHo'
        '//wMkEwyQkVmUi4oAARQiEXweAA8GFNGa0JD+QAAU6x6ALHKZBq6fAEAZBQiyGE0cAAwKAAE'
        'ZwjRwFJFUc7/5DPFAABvHDA5AABvHpB8ABRqAnAAM8AAAG8gTnVCeQAAbyBOdUjn//BwABAQ'
        'cgASKAABdAAUKAACdgAWKAADR+gABjgA2EK4fAAUYko4AdhDuHwAYGJAuHkAAG8eYwYzxAAA'
        'bx5TQzwBzPwAFNxAPgJTR0P5AABmrBOFYABD+QAAV6w4BthEM5tAAFJGUc//5FJBUcv/0kzf'
        'D/9OdUp5AABvHGciE/wAAQACe+VB+gNeI8gAAAAAM/z//wAAbwBQ+QAAAEZOdUH6B0JwCmAA'
        '+ngT/AAAAAJ75VH5AABvFmAA8wYwOQACe+5VQGoacABgFjA5AAJ77lRAsHkAAG8gbwYwOQAA'
        'byCweQACe+5nDDPAAAJ77lD5AAAAR051YQDvtCh5AAJ7ak6UKHkAAnt2TpRhAPAaYQDwQGEe'
        'YS5hAADKYQABOmEA+h5hAAF4YQDoJFDtActgAOw8YQDviggDAAJmgAgDAANmiE51Im0B8kPp'
        'AsI8OQACe+5+EzgGyPwAKEf5AABXrNfEehMoSXQAvHkAAG8eZAI0G0jnBEAiTGEA9kxhAPZY'
        'TN8CIFSMUc3/3kPpAWBSRlHP/8JOdXD/dAAyLQEIsnwAoGQ85knSeQACe+6yeQAAbx5kLML8'
        'ABQ0LQEG6ErSQkH5AABmrHAAEDAQALA8AP9mAnD/QfkAAFes0kE0MBAATnVhAOhiM8AAAG8A'
        'MDkAAG78sDwAEWcA/rJKLQG+Zy4MbQCgAQhkGmGMSkBrRmEA9DBR+QACe+dR+QACe+hgAP6K'
        'MDkAAG8AagDvxk51Si0BwmcgYQD/YDACwHwD/2cUYQD0MFH5AAJ751H5AAJ76GAA/lhOdWEA'
        '/z5KQGs85UhB+QAAU6wgcAAAcAAQEOlI0HwAEHIAEigAAZJ5AAJ77udJ0nwAEHQAFCgAAulK'
        'dgAWKAAD50tgAPVoTnVH+QAAAExhAP7ySkBrVDgAOgJB+gV+YQDooDAEYQDoouVMQfkAAFOs'
        'IHBAABb8ACBwABAoAAJhAOiIFvwAeBAoAANhAOh8FvwAIBb8ACAwBcB8A/9nDEH6BTRhAOhc'
        'YQDoYEITYADoCgACAAAALgABAABCRAAAQrUAMgAAAC4AAgAAQkwAAF+pAGIAAAAiAAMAAEJU'
        'AAB1xACGAAAAHAAEAABCWgAAfwIAyAAAABwABQAAQl8AAH8iAOYAAAAcAAYAAEJkAAB/OwEE'
        'AAAAHAAHAABCaQAAQtoBIgAAABwACAAAQm4AAEL5AAIADQAoAAkAAEJzAABDGgAuAA0AYIAB'
        'AAAAAAAAAAAAkgANACIACgAAQnoAAEM9ALYADQAcAAsAAEKAAABDawDUAA0AIgAMAABChQAA'
        'Q5cA+AANACIADQAAQosAAEPC//8AAgAAACIADgAAQpEAAEPqAOYAAAAcAA8AAEKWAABEEwEE'
        'AAAAIgAQAABCmQAARDMAKAAAALqAAwAAAAAAAAAA//8ABAAAATiAAgAAAAAAAAAAAFgADQAi'
        'ABEAAEJpAABEVQCAAA0ANAASAABCngAARH4AugANAC4AEwAAQqYAAESr//9UZXJyYWluAE9i'
        'amVjdHMAUGFyYW0AVGVzdABVbmRvAFJlZG8AU2F2ZQBNZW51AFBpZWNlcwBFcmFzZQBQaWNr'
        'AERlY29yAFN0ZWVsAEJhY2sAVXAARG93bgBEaXNjYXJkAENhbmNlbABVbnNhdmVkAFRlcnJh'
        'aW46IGRyYXcgdGhlIGxldmVsJ3MgZ3JvdW5kIChUKQBTYXZlIHRoZSBsZXZlbCB0byBpdHMg'
        'ZmlsZSAoUykAQmFjayB0byB0aGUgbGlzdCBvZiBsZXZlbHMgKEVzYykAQ2hvb3NlIGEgdGVy'
        'cmFpbiBwaWVjZSBvciB0aWxlIChQKQBFcmFzZSB3aXRoIHRoZSBicnVzaCdzIHNoYXBlIChS'
        'LCByaWdodCBjbGljaykAVGFrZSBhIHRpbGUgZnJvbSB0aGUgbGV2ZWwgYXMgdGhlIGJydXNo'
        'IChLKQBEZWNvcjogbGVtbWluZ3MgcGFzcyB0aHJvdWdoIHRoZSBjZWxscyAoRCkAU3RlZWw6'
        'IGNhbm5vdCBiZSBkdWcgb3IgYmFzaGVkIGF3YXkgKEkpAEJhY2sgdG8gdGhlIGxldmVsIHdp'
        'dGhvdXQgY2hvb3NpbmcgKEVzYykAU2hvdyB0aGUgcm93cyBhYm92ZSAoY3Vyc29yIHVwKQBT'
        'aG93IHRoZSByb3dzIGJlbG93IChjdXJzb3IgZG93bikAU2F2ZSB0aGUgY2hhbmdlcywgdGhl'
        'biB0aGUgbGlzdCAoUmV0dXJuKQBMZWF2ZSB0aGUgY2hhbmdlcyB1bnNhdmVkLCB0aGVuIHRo'
        'ZSBsaXN0IChEKQBLZWVwIGVkaXRpbmcgKEVzYykAQ2xpY2s6IGRyYXcgICAgUmlnaHQgY2xp'
        'Y2s6IGVyYXNlAENsaWNrOiBlcmFzZSAgICBSaWdodCBjbGljazogZHJhdwBDbGljazogdGFr'
        'ZSB0aGlzIHRpbGUgYXMgdGhlIGJydXNoAENsaWNrOiB0YWtlIHRoZSBwaWVjZSAgICBSaWdo'
        'dCBjbGljazogb25lIHRpbGUAUmV0dXJuOiBzYXZlICAgRDogZGlzY2FyZCAgIEVzYzoga2Vl'
        'cCBlZGl0aW5nAFNhdmUgdGhlIGNoYW5nZXMgdG8gAD8AU2F2ZWQgAFRoZXJlIGlzIG5vIHRp'
        'bGUgdG8gdGFrZSBoZXJlAFRoaXMgc3R5bGUgaGFzIG5vIHRlcnJhaW4gcGllY2VzAENlbGwg'
        'AEJvcmRlciwgbm90IGVkaXRhYmxlAExldmVsOiAAVGlsZSAAUGllY2UgAFJvd3MgAEVtcHR5'
        'ACBTb2xpZAAgRGVjb3IAIFN0ZWVsAAAASOf/+HAAKHkAAnuuTpQ+KP/+vnwAIGMCfiAzxwAC'
        'fAZH+QAAbyRTR2t2JohhfBdAABgXQQAZQ/oWLBdxAAAAGnAAcgB0AHYAYQACLkPrAARhAAO6'
        'MCsABMB8//BEQDdAABDQawAI0HwAD8B8//A3QAAUMCsABsB8//hEQDdAABLQawAKXkDAfP/4'
        'N0AAFjAQwPwADEHwCBRH6wAcUc//jGEAAMhM3x//TnVI5z/AcgB4AHoAPCgAAj4QQegAFFNH'
        'a1Q0EAgCAA1nBAjBAAAIAgAMZwQIwQABCAIAC2cMdgAWArZ8ABBkAgfEJigABiADwLwAABgA'
        'sLwAABAAZhBwFuCrxnwAP7Z8ABBkAgfFQegADFHP/65wALx8AAJnRnABCAUAAGY+cAIIBQAB'
        'ZjZwDAgFAAJmLnAIvHwAD2cmcApKRmYESkRmHEP6FQp0AAUEZwhwABAxIABqClJCtHwAEGXs'
        'cA1M3wP8TnVI5//AQnkAAnv6QnkAAHMmQnkAAHMkSnkAAnwGZwAA2Dg8ABB6AHwAfgBD+QAA'
        'cqRCUXYAQfkAAG8kdAAyPAAgtHkAAnwGZGq2KAAaZly4fAAQZgJyADAE0EHQaAAUsHwBMGMi'
        'uHwAEGccvnwAH2QW2kZQRXwAUkcwB9BAM4UAADg8ABBgyNhBMUQADDFHAA7YaAAUvGgAFmQE'
        'PCgAFjAH0EAzhgBAMjwAEFJCQegAHGCOUkO2fAAFZQD/elJHM8cAAHMkU0feRzAxcADQcXBA'
        'UEByADQANgHWQ5RxMAC0fACgYwxSQbJ5AABzJGXmU0EzwQAAcyZM3wP/TnUvAcL8ABxB+QAA'
        'byTRwSIfTnVI5//gQnkAAHayQnkAAHa0Q/kAAHbsM8AAAHa4M8EAAHa6M8IAAHa8OgI8AzP8'
        'EAAAAHa2PhBB6AAUU0drblN5AAB2tmtmNBgIAgAPZgYwOQAAdrjQWAgCAA5nCggCAA1nClSI'
        'YAgyOQAAdrrSWFiIOBhhPggCAA1nClNFawZB6P/0YLoIAgAMZx4wOQAAdrhB6P/0CAIADWcE'
        '0mgABDo5AAB2vFNGapZRz/+UTN8H/051UnkAAHayDHkCAAAAdrJiCDLAMsEyxDLCCAQADWYo'
        'CAIACmYiCAIAC2ccdgG4fIAAZw4vCmEkNioAAsbqAAQkX9d5AAB2tE51MDkAAHaysHwCAGME'
        'MDwCAE51LwQkbQJSyHwA/+VMJHJAAigfTnUvBCRtAkYIBAAOZwQkbQI+yHwA/+VMJHJAACRq'
        'AAIoH051SOcIIDgpAAQIBAANZigwEcB8//AyKQACwnz/+HQQdgi4fIAAZyZhojQqAALpSjYq'
        'AATnS2AWYaYwEdBSMikAAtJqAAI0KgAENioABkzfBBBOdUjn/8AgSTg8f/86BDw8gAA+BkP5'
        'AAB27GEA/0w/AGAgYYywRGwCOACyRWwCOgHUQLRGbwI8AtZBtkdvAj4DUIlTV2rcVI+4fH//'
        'Zgh4AHoAfBB+CEiQAPBM3wP/TnUvAEH5AAAgbMD8AArRwCAfTnUvCGHqMhjhWTQY4Vo2GOFb'
        'OBjhXDoY4V0gX0pBTnVI53yAYcrhWTDB4VowwuFbMMPhXDDE4V0wxUzfAT5OdUjn/IBCeQAA'
        'drJhtmsasnkAAnwGZBJhAP2UIFAwAjIDNAQ2BWEA/ZhM3wE/TnVI53wAcD9hjGoIUcj/+nAA'
        'YBpSQLB8AEBlEnAAYQD/dmsKUkCwfABAZfJw/0zfAD5KQE51SOf/8EJ5AAJ7/HAEI8AAAnwC'
        'QnkAAnwAQnkAAHaoQnkAAHaqQnkAAHasQnkAAHauM/z//wAAdrB+AEX5AAB1KBW8AP9wAEX5'
        'AAB1aEIycABF+QAAdahCMnAARfkAAHXoUPJwAEX5AABzKDAH50hCsgAAQrIABDAHYQD+5msA'
        'ATSyeQACfAZkAAEqPAFhAP8QUnkAAnv8cAAwOQAAdrLA/AAI0LwAAAAW0bkAAnwCMDkAAHa0'
        '0XkAAnwAQ/kAAHMoMAfnSNLAYQD+KDIGYQD8fEX5AAB1KBAoABgVgHAAsDwAAWYGUnkAAHaq'
        'IlAwKQACsHwAAmcmsHwADWcwsHwADmd+sHwAD2dEsHwADGYAAKQIKQABAAtmAACaYDBSeQAA'
        'dqhyATA5AAB2qGA+MDkAAHassHwAIGR6RfkAAHYoFYcAAFJ5AAB2rHICYB4wOQAAdq6wfAAg'
        'ZFpF+QAAdkgVhwAAUnkAAHaucgNF+QAAdagVgHAARfkAAHVoFYFwAGAyRfkAAHVoFbwABHAA'
        'MDkAAHawaggzxwAAdrBgFkX5AAB16BWAcAAVhwAAM/z//wAAdrBSR758AEBlAP6AMDkAAHas'
        'sHkAAHauYwYwOQAAdq5B+QAAdihD+QAAdkhF+QAAdehyAGAWdAAUMBAAdgAWMRAAFYMgABWC'
        'MABSQbJAZeZwAEp5AAB2qGYECMAAAAx5AAQAAHaoYwQIwAABSnkAAHaqZgQIwAACSnkAAHaw'
        'awQIwAADMjkAAHassnkAAHauYwQIwAAEDHkAQAACfABjBAjAAAUMuQAAEAAAAnwCYwQIwAAG'
        'M8AAAnv+QfkAAHUoMDkAAnv2axYMMAD/AABmDjP8//8AAnv2UfkAAnvzMDkAAnv4axAMMAD/'
        'AABmCDP8//8AAnv4TN8P/051LwAwOQACe/5nFkH6DtbiSGUEWIhg+CBQIB+w/AAATnWRyCAf'
        'sPwAAE51SOf/+EH5AAAgbCJ5AAJ7ujA8AT8yGOFZMsFRyP/4IG0CYkP5AACG7EX5AAABmDA8'
        'B7Ii0CDaUcj/+ih5AAJ7tk6UKHkAAnuyTpQgbQJiQ/kAAIbsMDwHsiIQJBlrBrOC1IJnBgjB'
        'AB8ggViIUcj/6lDtAehhAPy0TN8f/051SOf/gD4ASLkAPgAAdr5hAPv8SLkAPgAAdshMuQA+'
        'AAB2vmEA/AZhAPyESkFrGkH6FDoMuQAAEAAAAnwCYipB+hQCMAdhRGYgYQD/OFD5AAJ75lD5'
        'AAJ8R1D5AAAAR0zfAf8APAAETnUwB0y5AD4AAHbIYQD7tmEA/DRwDGEA6dpM3wH/AjwA+051'
        'SOfAgEH5AABzKOdI0MAMUAAQbTIMaAAQAAJtKjItAQzpSZJ8ABCyaAAEbRoyLQEO50mSfAAQ'
        'smgABm0KTN8BAwA8AAROdUzfAQMCPAD7TnVI5zAANADUULR8ABBsCjA8AB+QUMB8//A2LQEM'
        '6UuWfAAQNADUaAAEtENvFJZoAATGfP/wMAM0ANRQtHwAEG1MNAHUaAACtHwAEGwMMjwAF5Jo'
        'AALCfP/4Ni0BDudLlnwAEDQB1GgABrRDbxaWaAAGxnz/+DIDNAHUaAACtHwAEG0KTN8ADAI8'
        'AP5OdUzfAAwAPAABTnUwLQEG0G0A/tB8ABAyLQEI0m0BANJ8ABBOdUjnf8A8AD4Bej9B+QAA'
        'dSgMMAD/UABnWEH5AABzKDAF50jQwLxQbUi8aAAEbEK+aAACbTy+aAAGbDYwBWEA+oJhAPk2'
        'OABD+QAAduxgHmEA+XC8QG0U1EC8QmwOvkFtCtZBvkNsBDAFYAxQiVHM/+BRzf+YcP9M3wP+'
        'TnVI5yCAMjkAAnv0YQD35FiIYQD/WDQQ1GgABOJCkEJQQMB8//A0KAAC1GgABuJCkkJYQcJ8'
        '//hhAP6cTN8BBE51M8AAAnv2UPkAAABHTnVhANcoM8AAAG8AM/z//wACe/gMbQCgAQhkDmEA'
        '/wBhAP8WM8AAAnv4MDkAAG78ZxJKOQACe/NnBkotAbxmBGEA37hKOQACe/NnEEotAbxmAAFQ'
        'UfkAAnvzTnVKLQG+ZyZCeQAAduIz+QAAbwAAAHbkDG0AoAEIZQAAvjA5AABvAGoA3lJOdUot'
        'AbxnJjA5AABvALB5AAB25GYYYShmFFJ5AAB24gx5AAMAAHbiZRRgAN4kSi0BwmcKMDkAAnv4'
        'agABhk51sHwAFmUMsHwAGWIGADwABE51AjwA+051chSwPABwZ0ByFbA8AH9nOHIWsDwALWcw'
        'chewPAA9ZyiwPAArZyJyGLA8AFtnGnIZsDwAXWcSchqwPAAsZwpyG7A8AC5nAk51MAFhAOj+'
        'unwAA2cEYADduE51MDkAAnv4agZhAADKa1phAP6sPgBhAPhsM8IAAHbSM8MAAHbUYQD9wJBC'
        'M8AAAHbWkkMzwQAAdthB+QAAcygwB+dI0MBD+QAAdtowGJBCMsAwGJBDMsAwGJBCMsAwGJBD'
        'MsBQ+QACe/NOdQxtAKABCGRgYQD9cpB5AAB21pB5AAB20lBAwHz/8NB5AAB20pJ5AAB22JJ5'
        'AAB21FhBwnz/+NJ5AAB21EH5AAB22mEA/KJlIDwAPgEwOQACe/ZrFGEA98K8QmYEvkNnCDQG'
        'NgdgAPumTnVhAPgYayI+AGEA/Z5lIDQANgEwBzI5AAJ79HgAegBhAPuCZhQwB051QfoQDGAE'
        'QfoPtHAMYQDlxHD/TnU+AHL/dP92/3j/ev9hAPtYUfkAAnvzvnkAAnv2Zggz/P//AAJ79kf5'
        'AABupEH6D2phANXAMAdSQGEA1cBB+QAAbqRwBmAA5XgwOQACe/ZqsE51MDkAAnv2axJhAPcW'
        'SkZmBNhHYALaR2AA+vxOdXwAfv9g3nwAfgFg2HwBfv9g0nwBfgFgzDA5AAJ79moIcP9KR2oC'
        'cEB8P9BHwHwAP0H5AAB1KAwwAP8AAGYGUc7/6k51YQD8+GAIfv9gyn4BYMZI58CAQfkAAHMo'
        '50jQwDAQ0GgABOJAkHwAsMB8//BqAnAAsHkAAG72bwYwOQAAbvYyKAAC0mgABuJBknwAYMJ8'
        '//BqAnIAsnkAAG74bwYyOQAAbvgzwAAAduYzwQAAduhQ+QAAdupM3wEDTnUMbQCgAQhkEko5'
        'AAJ782YKSnkAAnv4agJhJGEAAYQwOQACe/ZrAmFkMDkAAnv4awyweQACe/ZnBGEAAIROdWEA'
        '/ABlRjwAPgEyOQACe/RhAPPgJkggUzAGMgdhAACUYQABQDArAATQRpBtAP4yKwAG0keSbQEA'
        'NCsACJRrAAQ2KwAKlmsABmAAASZOdUjn+EBhAPXyYQD0pjgAQ/kAAHbsYBJhAPTgkG0A/pJt'
        'AQBhAAD+UIlRzP/sTN8CH051SOfwgEH5AABzKOdI0MAwEDIoAAI0KAAElEA2KAAGlkGQbQD+'
        'km0BAGEAAMZM3wEPTnVI5//4dAB2AGEA80hhAACiR/kAAHbsYQD0ND4AYEI4KwAECAQADWY2'
        'uHyAAGcwYQD0LihqAAY8KgAEU0YyKwAC5kEwE+hAOioAAlNFNBxhAN/AUkBRzf/2UkFRzv/m'
        'UItRz/+8R/kAAHbsYQDz4D4AYDQ4KwAECAQADWcoIG0CRggEAA5nBCBtAj7IfAD/MBMyKwAC'
        'NDyAAHYAegAoeQACewZOlFCLUc//ykzfH/9OdUouAAIILgAGAAJm+E51SOf/gEpCbzZKQ28y'
        'IG0B8jgA2EJTRDoB2kNTRTwBYSS6QWcaPAVhHDwBUka8RWwOPgBhZLhAZ/I+BGFcYOxM3wH/'
        'TnVI5/gASkZrRrx8AMBkQEpAagJwALh8AV9vBDg8AV+wRG4sMgDCfAAPdP/iajYAhnwAD7ZE'
        'bxAyBEZBwnwAD3b/42vEQzYEYTowA1JAYNBM3wAfTnVI56AASkZrILx8AMBkGkpHaxa+fAFg'
        'ZBAwB8B8AA80PIAA4GowB2EGTN8ABU51SOdQQDIGwvwALCJI08EyAOhJ0kHSwTYCYQDfaEzf'
        'AgpOdUf5AAAATD45AAJ7+GoeQfoKxGEA0hwwOQACe/xhANIaQfoKu2EA0gpgAAFeQfoKtmEA'
        '0f4wB1JAYQDR/kH6CrlhANHuMAdhAPNoMAFhANHqFvwAIEH5AAB1KHAAEDBwADwAYQABKkH5'
        'AAB1aHIAEjBwAEH5AAB1qHQAFDBwAEH5AAB16HYAFjBwALJ8AAFnGLJ8AAJnTLJ8AANndrJ8'
        'AARnAACcYAAAuhb8ACAwAmEA0Yi0fAAEYh5B+go4YQDRcjA5AAB2qLB8AARjAnAEYQDRaGAA'
        'ALRB+gonYQDRVGAAAKgW/AAgMAJSQGEA0Uy2PAD/ZxRB+goUYQDRNjADUkBhANE2YAAAgkH6'
        'CgthANEiYHa2PAD/ZxxB+goHvHwACGcEQfoKCWEA0QgwAlJAYQDRCGBUQfoKC2EA0PZgSrY8'
        'AP9nEkH6CgdhANDmMANSQGEA0OZgMkH6CgNhANDUYCgwB2EA8kxhAPAySigAGWcYQfoJ9mEA'
        '0LowBGEA0LwW/AAsMAVhANCyQhNgANBcLwiwfAANYg5B+gQO5UggcAAAYQDQjiBfTnVB+giv'
        'cAdKOQACe/NmAM/UYQD1QmciR/kAAHZoLwhB+gjdYQDQZCBfYQDQXkH5AAB2aHAMYADPrEH6'
        'CEJwB2AAz6JI5/uAfgA8ALx8ABplCkp5AAJ7/GZOYEq8fAAVZUYwOQACe/ZrPLx8ABVnOGEA'
        '8ZhhAO9+FCgAGXYAMAS8fAAYZQR2ATAFBwJnGLx8ABZnDrx8ABhnCLB8AChsBmAGSkBuAn4D'
        'OgdM3wHfTnVI5/6AsHyABGYkMDkAAnv0YQDP0Bb8ACAyOQACe/RhAO8kcAAQKAAYYQD/DmBa'
        'sHyAB2YUQfoJLWEAz6AwOQACfAZhAM+eYEB8ABb8AFewfIAFZwh8ARd8AEj//xb8ACAwOQAC'
        'e/ZrHGEA8PBhAO7WDSgAGWcOMARKRmcCMAVhAM9iYAQW/AAtTN8Bf051SnkAAnwGZyhR+QAC'
        'e/MT/AADAAJ75UH6BDwjyAAAAAAz/P//AABvAFD5AAAARk51QfoJRXAKYADe4BP8AAAAAnvl'
        'YQDXdE51MDkAAnv6Zw5TQDPAAAJ7+lD5AAAAR051MDkAAnv6sHkAAHMmZA5SQDPAAAJ7+lD5'
        'AAAAR051YQDUJCh5AAJ7ak6UKHkAAnt2TpRhANSKYQDUsGEAAQZhGGEAAWZhAN6QYQABrGEA'
        'zJZQ7QHLYADQrmEAzYQzwAAAbwAwOQAAbvywPAARZwD/bLA8AAFnAP9ysDwAAmeCSi0Bvmco'
        'DG0AoAEIZBZhaEpAaxozwAACe/RQ+QAAAEdgAP86MDkAAG8AagDU3k51LwlD+QAAcqQ0KAAO'
        'tHkAAnv6ZSzUQjQxIAAyOQACe/rSQZRxEABQQjIC0mgAFrJ8AKBiDDIoAAwiXwI8AP5OdSJf'
        'ADwAAU51SOdwgAxtAKABCGQ4QfkAAG8kcACweQACfAZkKGGaZRw2LQEGlkFrFLZoABRkDjYt'
        'AQiWQmsGtmgAFmUKUkBB6AAcYNBw/0zfAQ5OdWEA+oIgbQHyQegCwHIDIkgwPAbfQplRyP/8'
        'QeghAFHJ/+5H+QAAbyR+AL55AAJ8BmQyIEthAP82ZSLSawAQ0m0A/tJ8ABDUawAS1G0BANR8'
        'ABAwATICIFNhAPl6UkdH6wAcYMZOdWEA+hwwOQACe/RhFGEA/0BKQGsKsHkAAnv0ZwJhAk51'
        'SOfwgDIAYQDshmEA/tplGDAB0HwAEDIC0nwAEDQoABQ2KAAWYQD55kzfAQ9OdUf5AAAATGEA'
        '/vhKQGs6MgBB+gWgYQDM4GEAzOQW/AAgFvwAIGEA7DpwABAoABhhAPwkcAAQKAAZZw7lSEH6'
        'AH4gcAAAYQDMsEITYADMYv//C///CwMLBAUHBgn///8AAQIDAwMDAwMDAwMDBAAAXngAAF6B'
        'AABehgAAXowAAF6RAABemAAAXqEAAF6pAABesAAAXrcAAF7CAABeywAAXtIAAF7WAABe3gAA'
        'XvMAAF8MAABfHQAAXzkAAF9QAABfcQAAYnAAAGKHAABiowACAAAALgABAABCRAAAQrUAMgAA'
        'AC4AAgAAQkwAAF+pAGIAAAAiAAMAAEJUAAB1xACGAAAAHAAEAABCWgAAfwIAyAAAABwABQAA'
        'Ql8AAH8iAOYAAAAcAAYAAEJkAAB/OwEEAAAAHAAHAABCaQAAQtoBIgAAABwACAAAQm4AAEL5'
        'AAIADQAiABQAAF+UAABf1QAnAA0AXoAEAAAAAAAAAAAAiAANACgAFQAAX5oAAF/8ALMADQAY'
        'gAUAAAAAAAAAAADNAA0ADAAWAABfoQAAYCoA2wANAAwAFwAAX6MAAGBIAOoADQAYgAYAAAAA'
        'AAAAAAEEAA0ADAAYAABfoQAAYGUBEgANAAwAGQAAX6MAAGCIASEADQAOABoAAF+lAABgqgEx'
        'AA0ADgAbAABfpwAAYNL//wACAAAAIgAOAABCkQAAYPYAKAAAALqABwAAAAAAAAAAAOYAAAAc'
        'AA8AAEKWAABEEwEEAAAAIgAQAABCmQAARDP//0VudHJhbmNlAEV4aXQAV2F0ZXIAVHJhcABI'
        'YXphcmQATGF1bmNoZXIAQm91bmNlcgBTd2l0Y2gAVGFyZ2V0AFRlbGVwb3J0ZXIAU3dpbmdp'
        'bmcARGV2aWNlAEljZQBTY2VuZXJ5AHRoZXJlIGlzIG5vIGVudHJhbmNlAG9ubHkgZm91ciBl'
        'bnRyYW5jZXMgd29yawB0aGVyZSBpcyBubyBleGl0AGEgdGVsZXBvcnRlciBoYXMgbm8gcGFy'
        'dG5lcgBhIHN3aXRjaCBoYXMgbm8gdGFyZ2V0AHRyYXBzIGFuZCBkZXZpY2VzIG92ZXIgdGhl'
        'IGxpbWl0AHRvbyBtYW55IG9iamVjdCBwYXJ0cyBmb3IgdGhlIGdhbWUAVHlwZXMARGVsZXRl'
        'AC0AKwA8AD4AT2JqZWN0czogcGxhY2UsIG1vdmUgYW5kIGRlbGV0ZSBvYmplY3RzIChPKQBD'
        'aG9vc2UgdGhlIHR5cGUgb2Ygb2JqZWN0IHRvIHBsYWNlIChQKQBEZWxldGUgdGhlIHNlbGVj'
        'dGVkIG9iamVjdCAoRGVsLCByaWdodCBjbGljaykARmV3ZXIgY29waWVzIHNpZGUgYnkgc2lk'
        'ZSAoLSkATW9yZSBjb3BpZXMgc2lkZSBieSBzaWRlICgrKQBGZXdlciBjb3BpZXMgb25lIHVu'
        'ZGVyIGFub3RoZXIgKFspAE1vcmUgY29waWVzIG9uZSB1bmRlciBhbm90aGVyIChdKQBTZWxl'
        'Y3QgdGhlIHByZXZpb3VzIG9iamVjdCBpbiBvcmRlciAoLCkAU2VsZWN0IHRoZSBuZXh0IG9i'
        'amVjdCBpbiBvcmRlciAoLikAQmFjayB0byB0aGUgbGV2ZWwsIHRoZSB0eXBlIGFzIGl0IHdh'
        'cyAoRXNjKQBDbGljazogcGxhY2Uvc2VsZWN0ICBEcmFnOiBtb3ZlICBSaWdodCBjbGljazog'
        'ZGVsZXRlAFJlbGVhc2UgdGhlIGJ1dHRvbiB0byBwdXQgdGhlIG9iamVjdCBkb3duAENsaWNr'
        'OiBwbGFjZSBvYmplY3RzIG9mIHRoaXMgdHlwZQBXYXJuaW5nOiAAU2F2ZSAoUyk7IHdhcm5p'
        'bmc6IABTYXZlZDsgd2FybmluZzogAE9iamVjdHMgACBvZiA2NABPYmplY3QgAFR5cGUgACBv'
        'ZiAAICBUeXBlIAAsIG5vdCB1c2VkACwgdG9nZ2xlcyAALCBubyB0YXJnZXQAIG9mIHN3aXRj'
        'aCAALCB0YXJnZXQgb2Ygc3dpdGNoIAAsIG5vIHN3aXRjaAAsIHBhaXJzIHdpdGggACwgbm8g'
        'cGFydG5lcgAgIFJlcGVhdCAAICByZXBlYXRzIHNpZGUgYnkgc2lkZQAgIHJlcGVhdHMgb25l'
        'IHVuZGVyIGFub3RoZXIAICByZXBlYXRzIGJvdGggd2F5cwBPYmplY3QgdHlwZXMgb2YgdGhp'
        'cyBzdHlsZTogAERlbGV0ZWQgb2JqZWN0IABObyByb29tOiB0aGUgb2JqZWN0IHdvdWxkIGxl'
        'YXZlIHRoZSBtYXAATm8gcm9vbTogdGhlIGdhbWUncyBvYmplY3QgbWVtb3J5IGlzIGZ1bGwA'
        'QWxsIDY0IHBsYWNlcyBmb3Igb2JqZWN0cyBhcmUgdXNlZABUaGlzIHN0eWxlIGhhcyBubyBv'
        'YmplY3RzAABhAMSqM8AAAG8AMDkAAG78ZwRhAM1mSi0BvmcuQnkAAHbiM/kAAG8AAAB25DIt'
        'AQiyfACgZUCyfADKZQABnjA5AABvAGoAzBBOdUotAbxnJjA5AABvALB5AAB25GYYYRhmFFJ5'
        'AAB24gx5AAMAAHbiZQRgAMviTnWwfAAfZxKwfAAgZwywfAAkZQywfAApYgYAPAAETnUCPAD7'
        'TnWwPAB2ZhYwPAAjMjkAAG7+sjwAYWQ8MDwALWA2MjwAJ7A8AHJnCjI8ACmwPABnZhIwATI5'
        'AABu/rI8AGFkFFNAYBBB+gAeMhhnFjQYsAFm9jACYQDWuLp8AANnBGAAy3JOdQBwAB0AbgAc'
        'AH8AHgAtAB8APQAgACsAIAAsACEALgAiAFsAJABdACUAALB8ABxnAAdEsHwAHWcACISwfAAe'
        'ZwABvLB8AB9nAAFEsHwAIGcAAUCwfAAhZwAA+rB8ACJnAAD4sHwAI2cABDiwfAAtZwAFVrB8'
        'ACRnAAM2sHwAJWcAAzKwfAAmZwADyrB8ACdnAAPGsHwAKGcAA8ywfAApZwADyLB8ACpnAAdE'
        'sHwAK2cABzCwfAAuZwAFoLB8AC9nAAW0sHwAMGcABciwfAAxZwAGSLB8ADJnAAcITnUwLQEG'
        'sHwBAGQI6khhBmcCYEBOdUH5AAABUNDA0MBhBEpBTnVyABIoAAHhSRIQTnU/ARCB4EkRQQAB'
        'Mh9OdVD5AAJ75lD5AAJ8R1D5AAAAR051M8AAAnwIUPkAAABHSOf/8DA5AAJ8CCh5AAJ7xk6U'
        'TN8P/051YQpq2E51YRZq0k51MDkAAnwIU0BrBGGGZ/hKQE51MDkAAnwIUkCwfAAIZAphAP9w'
        'Z/JKQE51cP9OdX7/YAJ+ATA5AAJ8CGEA/1ZnXEH5AAABYHIAEjAAANJHSkdqELJ8AAFtRLJ8'
        'AGNjCnJjYAayfABjbjQRgQAAIHkAAns6QegAKDQA1EIxgSAAQe0BZDGBIABI5//wwUEoeQAC'
        'e8pOlEzfD/9gAP8iTnUwOQACfAhhAP7sZ1ZB+QAAAVBD+QAAAWAyANJB0MHSwHIGkkBrEBDo'
        'AAIQ6AACEukAAVHJ//JCUEIRMDkAAnwIYQD+smYKSkBnBlN5AAJ8CGEAAIpB+hOjcAZhANIw'
        'YAD+vk51SOf/8CR5AAJ7OkH5AAABOCJKcBcS2FHI//xwABA5AAABaBVAADg7QAF2EDkAAAFq'
        'FUAAOTtAAXhB+QAAAW5D6gA+cAdhAP5aMsFUiFHI//YwOQACfAhhAP44ZgZTQGr2cAAzwAAC'
        'fAhQ7QHbKHkAAnvOTpRM3w//SOf/8EH5AAABUEP5AAABYCR5AAJ7OkftAWRwAGEA/go1gQAY'
        'cgASGTWBACg3gQAAVIhUQLB8ABBl4ih5AAJ7wk6UTN8P/2AA/hpI57B4cAA2PAAzEigAZoIo'
        'AGdmAnYGQ+gALEXoADwmSShKdAdhLrJDZgQwAWAIFtEW6QABGNJUiVKKUcr/6LfJZwhCG0Ib'
        'Qhxg9DIATN8eDUpBTnVyABIpAAHhSRIRTnUyOQAApexnIkJ5AACl7EH6EoyyfAAGZwRB+hKz'
        'cAxhANDmM/wAeAAAbwROdX7/YAJ+AWEAAIQ0AEjAgPwAD0pHawRSQGAKIgBIQUpBZgJTQMD8'
        'AA+wfAAPbAJwD7B8AklvBDA8AklKR2sGsEJvSGAEsEJsQkjAgPwAPBPAAAABaCB5AAJ7OhFA'
        'ADg7QAF2SEATwAAAAWoRQAA5O0ABeEjn//BQ7QHbKHkAAnvOTpRM3w//YAD85E51cAAQOQAA'
        'AWjA/AA8cgASOQAAAWrQQU51fv9gAn4BQfkAAAF8dBR2TGAQfv9gAn4BQfkAAAF6dDt2SmEA'
        '/IrSR2siSkdrBrJCYhpgBrJCYwIyAmEA/H4geQACezoxgTAAYAD8fk51LDkAAAFyLjkAAAF2'
        'Q/kAAAFuJHkAAns6ReoAPjgtAP46OQAAbvZhLjgtAQA6OQAAbvhhIkH6EE68uQAAAXJmCL65'
        'AAABdmcEQfoQXnALYQDPmGAA/CYgSTIEYQD8EEHpAARhAPv8skRuCjAEkEHAfAAPZwoyBMJ8'
        'AA9hAPvwNUEABEHpAAhhAPvYskRtCjABkETAfAAPZw4yBZJEwnz/8NJEYQD7yDVBAAg0hFSJ'
        'VIpOdUP5AACl8mFWQfkAAKXyMBAyKAACNDwBQDY8AKBhKmEAy/YwKAAEMigABjQoAAiUQNR8'
        'AUDEfP/wNigACpZB1nwAoGEEYADNSpBtAP7QfAAQwHz/8JJtAQDSfAAQTnVB+QAAAW5wBWEA'
        '+0YywVSIUcj/9k51Q/kAAnxQYeIT/AAFAAJ75UH6CpgjyAAAAABR+QAAAEsz/P//AABvAFD5'
        'AAAARlD5AAAAR051YQC9sDPAAABvADA5AABu/GcucjGwPAANZyByMrA8ABFnGHIusDwAdGcQ'
        'ci+wPABiZwhyMLA8AHdmBjABYADFNEotAb5nCjA5AABvAGoAxQ5OdUH5AAJ8UGAA/wpB+QAC'
        'fFA4LQD+YVhUiDgtAQBhUFD5AAAAR051QfkAAnxQOC0A/mFYVIg4LQEAYVBQ+QAAAEdOdUH5'
        'AAJ8UEJoAAQxeQAAbvYACGFSVIhCaAAEMXkAAG74AAhhQlD5AAAAR051MUQABDIoAAiyRGwC'
        'MgSSRMJ8//DSRDFBAAhgHjFEAAgyKAAEskRvAjIENASUQcR8//AyBJJCMUEABDIQNCgABLJC'
        'bAIyArJoAAhvBDIoAAiSQsJ8//DSQjCBTnVD+QACfFBB+QAAAW4keQACezpF6gA+dAB2AHAF'
        'YQD5yrJRZxB0AbB8AARlAnYBMhFhAPnCNMFUiFSJUcj/4EpCZwAAhkH6DhlKQ2cEQfoORnAL'
        'YQDNHGEA+apgbEH5AAABOEP5AACl0HAXEhiyPAAgZQyyPAB6YgayPAAjZgJyIBLBUcj/5kH5'
        'AACl0HAYDDAAIAD/ZgRTQGb0E8AAAKXoE/wABAACe+VB+gh8I8gAAAAAUfkAAABLM/z//wAA'
        'bwBQ+QAAAEZOdRP8AAAAAnvlYADFPnAAEDkAAKXoQfkAAKXQchewQWIKEbwAIBAAUcn/9EP5'
        'AAABOCR5AAJ7OnQAchcQGLARZwJ0ARLAFMBRyf/ySkJnsmEA+OpgrGEAu3gzwAAAbwAwOQAA'
        'bv5nZLA8AA1noLA8ABFnjrA8AAhnPrA8AH9nOLA8ACBlRrA8AHpiQLA8ACNnOnIAEjkAAKXo'
        'snwAGGQsQfkAAKXQEYAQAFI5AACl6FD5AAAAR2AUSjkAAKXoZwxTOQAApehQ+QAAAEdKLQG+'
        'ZwowOQAAbwBqAMKgTnVQ+QACfA9OdVH5AAJ8DzPtAP4AAKXuM+0BAAAApfBhAL8mYQC/rit5'
        'AAJ7kgIiO3wAyQFWE/wABQACe9lhAKyOYQAC3nAHKHkAAnruTpRhTko5AACl6WYGYQACXGAK'
        'QfoMvXAGYQDLZmEArExQ+QACfA5B+QAAASRD+QACzSxhAJxkYQCsUkH5AAABimEA97YwAWEA'
        'nPAvOQACew5OdSR5AAJ6stX8AAFhnEH6AXglSAACJHkAAnqy1fwAAWG2NLxOdSR5AAJ6stX8'
        'AAFkeEH6AoYlSAACInkAAnqy0/wAAWREMvxOuSL8AABvijK8TnEieQACerLT/AABY1gy/E65'
        'IvwAAG+wMrxOcSJ5AAJ6stP8AAFj+jL8Trki/AAAb8AyvE5xQfkAAAGKYQD3GEpBV/kAAKXq'
        'YQACCmEAANgxfAAEACJR+QAApelCLQHCKHkAAnu+TpQkeQACerIgCtC8AAATitX8AAFhnCVA'
        'AAIkeQACerLV/AABYbY0vCB5JHkAAnqyIArQvAABZIbV/AABZHglQAACJHkAAnqy1fwAAWRE'
        'JPxhAKZ2JLwGQAAgJHkAAnqy1fwAAWNYJPxSQC8AJLxD7QGgJHkAAnqyIArQvAABwQzV/AAB'
        'Y/o0/FJANPxB+SSAYQABXGEqMXwABQAiKHkAAnvSTpQgeQACerZB6AVEQmgAAkJoAAZCaAAK'
        'QmgADk51IHkAAnqy0fwAAcEEIFBOdUjn4MgoeQACe4ZOlHQBSi0BwmYQKHkAAnt6TpSwPAAR'
        'ZwJ0AEpCTN8TB2YCTnVQ+QAApelYj051SOcECEo5AACl6mcIunwABWYCejIoeQACewZOlEzf'
        'ECDQfAAgTnVSQGEeIl8vAC8JQ+0BoE51UkBhDiB5AAJ6stH8AAHBDE51SjkAAKXqZwiwfAAG'
        'ZgJwM051QfkAAAFQQ/kAAKW4cBcS2FHI//xF7QGgQfkAAAFQR/kAAAFgfgcyGmEA9XBUiHQK'
        'Q/kAAKW4SfkAAKXIdgd4ABgpAAHhTBgRVIm4QWYGShRnAhQUUoxRy//mFsJRz//IQnkAAnwI'
        'YAD1QCB5AAJ7TjAYsHz//2cSsHwBgGUIsHwBvmICQlBUiGDmTnVI58DgJHkAAnquTqoAIEzf'
        'BwNOdQcHAESgZAUIAUNob29zZSB0aGUgOCBza2lsbHMgb2YgdGhlIGxldmVsLgcASqBkBQgB'
        'UmlnaHQgYnV0dG9uIG9yIEVzYzoga2VlcCB0aGUgb2xkIG9uZXMuAEH6CCsyLQEIsnwAoGUO'
        'QfoIgLJ8AMplBEH61ThwB2AAt4ovADA5AAJ8CGEA9FhnEEH5AAABYHIAEjAAAAI8APtM3wAB'
        'TnVI5/uAfgA8ALx8AB5nTrx8AB9nVrx8ACBnXrx8ACFnZrx8ACJnaLx8ACRnarx8ACVncHQU'
        'QfkAAAF8vHwAJmduvHwAJ2dydDtB+QAAAXq8fAAoZ1q8fAApZ15gaDA5AAJ8CGEA89pnWmBa'
        'YQD/cGdSsnwAAWNMYExhAP9iZ0SyfABjZD5gPmEA9CRrNmA2YQD0LmsuYC5hAPbwsHwAD2Mi'
        'YCJhAPbksHwCSWQWYBZhAPOeSkFnDGAMYQDzlLJCZAJgAn4DOgdM3wHfTnVI5+CAsHyACGYg'
        'QfoDjGEAty5hAP78ZwowAWEAtypgAADmFvwALWAAAN6wfIAJZjJB+gNtYQC3CHAAEDkAAAFo'
        'YQC3BBb8ADpwABA5AAABarB8AApkBBb8ADBhALbqYAAAprB8gApmEEH6AzthALbQQfkAAAF8'
        'YBSwfIALZhpB+gMrYQC2ukH5AAABemEA8vQwAWEAtrJgbrB8gA1mRkH6AxlhALaaQfkAAnxU'
        'chB0EGEaQfoDG2EAtoZB+QACfFgyPAFPNDwAr2ECYDowGNBB6EhhALZyFvwALDAQ0ELmSGAA'
        'tmRB+gLLYQC2VEH5AACl0HAAEDkAAKXoYAIW2FHI//wW/ABfQhNM3wEHTnUAAgAAAC4AAQAA'
        'QkQAAEK1ADIAAAAuAAIAAEJMAABfqQBiAAAAIgADAABCVAAAdcQAhgAAABwABAAAQloAAH8C'
        'AMgAAAAcAAUAAEJfAAB/IgDmAAAAHAAGAABCZAAAfzsBBAAAABwABwAAQmkAAELaASIAAAAc'
        'AAgAAEJuAABC+QACAA0AIgAcAAB1RAAAdfQAJwANACgAHQAAdUoAAHYPAFIADQAoAB4AAHVR'
        'AAB2OgB9AA0ANIAIAAAAAAAAAAAAswANAAwAHwAAX6EAAHZaAMEADQAMACAAAF+jAAB2egDQ'
        'AA0ADgAhAABfpQAAdpkA4AANAA4AIgAAX6cAAHa6APEADQAiACMAAHVYAAB23AEVAA0AKAAt'
        'AAB1XgAAdv8AAgAaADqACQAAAAAAAAAAAD4AGgAMACQAAF+hAAB38gBMABoADAAlAABfowAA'
        'eAYAXAAaAC6ACgAAAAAAAAAAAIwAGgAMACYAAF+hAAB4GgCaABoADAAnAABfowAAeEIAqgAa'
        'AC6ACwAAAAAAAAAAANoAGgAMACgAAF+hAAB4XwDoABoADAApAABfowAAeIf//wAEAAABOIAM'
        'AAAAAAAAAAAAWAANACIAKgAAdYUAAHioAIAADQAuACsAAEKmAAB4wP//AAQAAAE4gA0AAAAA'
        'AAAAAAAEAA0ANAAuAAB1ZQAAdzQAOgANAEwALwAAdW4AAHdjAIgADQA6ADAAAHV7AAB3lQDc'
        'AA0AIgAxAAB1hQAAd74BBAANAC4AMgAAQqYAAHfY//9UaXRsZQBTa2lsbHMAUmVtb3ZlAFN0'
        'YXJ0AExpbWl0cwBUb3AgbGVmdABCb3R0b20gcmlnaHQAV2hvbGUgbWFwAE9LAENvdW50IABU'
        'aW1lIABSYXRlIABMb3N0IABUaXRsZTogAFNjcm9sbCBsaW1pdHM6IGNlbGxzIAAgdG8gAFBh'
        'cmFtZXRlcnM6IHRpdGxlLCBza2lsbHMsIHRpbWUgYW5kIGdyYWRpbmcgKEwpAFR5cGUgdGhl'
        'IGxldmVsJ3MgdGl0bGUgKE4pAENob29zZSA4IHNraWxscyB3aXRoIHRoZSBnYW1lJ3MgcGlj'
        'a2VyIChQKQBSZW1vdmUgdGhlIHNlbGVjdGVkIHNraWxsIChEZWwpAEZld2VyIG9mIHRoZSBz'
        'ZWxlY3RlZCBza2lsbCAoLSkATW9yZSBvZiB0aGUgc2VsZWN0ZWQgc2tpbGwgKCspAFNlbGVj'
        'dCB0aGUgc2tpbGwgdG8gdGhlIGxlZnQgKCwpAFNlbGVjdCB0aGUgc2tpbGwgdG8gdGhlIHJp'
        'Z2h0ICguKQBTdGFydCB0aGUgbGV2ZWwgd2l0aCB0aGlzIHZpZXcgKFYpAExpbWl0IHRoZSBz'
        'Y3JvbGxpbmcgYW5kIHRoZSBsZW1taW5ncycgYXJlYSAoU2hpZnQrVikAVGhlIGxldmVsIHNj'
        'cm9sbHMgdXAgYW5kIGxlZnQgdG8gdGhpcyB2aWV3IChUKQBUaGUgbGV2ZWwgc2Nyb2xscyBk'
        'b3duIGFuZCByaWdodCB0byB0aGlzIHZpZXcgKEIpAFRoZSBsZXZlbCBzY3JvbGxzIG92ZXIg'
        'dGhlIHdob2xlIG1hcCAoVykAVXNlIHRoZXNlIGxpbWl0cyAoUmV0dXJuKQBLZWVwIHRoZSBv'
        'bGQgbGltaXRzIChFc2MpADE1IHNlY29uZHMgbGVzcyAoWykAMTUgc2Vjb25kcyBtb3JlIChd'
        'KQBMZW1taW5ncyBjb21lIG91dCBtb3JlIHNsb3dseSAoU2hpZnQrUikATGVtbWluZ3MgY29t'
        'ZSBvdXQgZmFzdGVyIChSKQBCZXN0IGdyYWRlOiBmZXdlciBtYXkgYmUgbG9zdCAoU2hpZnQr'
        'RykAQmVzdCBncmFkZTogbW9yZSBtYXkgYmUgbG9zdCAoRykAVXNlIHRoaXMgdGl0bGUgKFJl'
        'dHVybikAS2VlcCB0aGUgb2xkIHRpdGxlIChFc2MpAFR5cGUgdGhlIHRpdGxlICAgQmFja3Nw'
        'YWNlOiBkZWxldGUgICBSZXR1cm46IGRvbmUARnJhbWU6IHN0YXJ0IHZpZXcgKFYpLiBEb3R0'
        'ZWQ6IGxpbWl0cyAoU2hpZnQrVikAU2Nyb2xsIHRoZSB2aWV3LCB0aGVuIHNldCBUb3AgbGVm'
        'dCBvciBCb3R0b20gcmlnaHQAQ2xpY2sgYSBza2lsbCBpbiB0aGUgcGFuZWwgdG8gc2VsZWN0'
        'IGl0AFRoZSBsZXZlbCBub3cgc3RhcnRzIHdpdGggdGhpcyB2aWV3AFN0YXJ0IHZpZXcgc2V0'
        'OyB0aGUgc2Nyb2xsIGxpbWl0cyB3ZXJlIHdpZGVuZWQATGltaXRzIHNldDsgbGVtbWluZ3Mg'
        'dGhhdCBsZWF2ZSB0aGUgZG90dGVkIGZyYW1lIGRpZQBMaW1pdHMgc2V0OyB0aGUgc3RhcnQg'
        'dmlldyBtb3ZlZCBpbnNpZGUgdGhlbQBUaGUgc2tpbGxzIGFyZSBhcyB0aGV5IHdlcmUAU2tp'
        'bGwgcmVtb3ZlZDsgdGhlIGxhdGVyIG9uZXMgbW92ZWQgbGVmdABBdHRyYWN0b3IgcmVtb3Zl'
        'ZDogaXQgZmFpbHMgaW4gdGhlIENsYXNzaWMgc3R5bGUAQmxvY2tlciByZW1vdmVkOiBpdCB3'
        'b3JrcyBvbmx5IGluIHRoZSBDbGFzc2ljIHN0eWxlAABCeQACfEhCeQACfEpCuQAA6Y5R+QAC'
        'fEdB+QAAASRD+QAApf5hAI72QfkAAAEkQ/kAAMfGYACO5uVIRfkAAOmOIDIAAEX5AADqEtXA'
        'TnUwPAhxs4hWyP/8TnVB+QAAASRD+QAAx8Zh5lb5AAJ75k51SjkAAnxHZwAAqEotAbxmAACg'
        'Si0BwGYAAJhKLQKvZgAAkEo5AAJ8R2cAAIZR+QACfEdB+QAApf5D+QAAASRhnmdkM/kAAnxK'
        'AAJ8SAx5ACAAAnxIZBIwOQACfEhhAP9qsLwAAV4oYwRhSGDgYQAAkjA5AAJ8SFJAM8AAAnxI'
        'M8AAAnxK5UhB+QAA6Y6V/AAA6hIhigAAQfkAAAEkQ/kAAKX+YQCOCGEA/0JQ+QAAAEdOdSI5'
        'AADpkjA5AAJ8SGEA/wiQgUP5AADqEkHxGADkiGACIthTgGr6QfkAAOmOMDkAAnxIU0AkKAAE'
        'lIEgwlHI//ZTeQACfEhTeQACfEpOdUH5AACl/kP5AAABJHIAsnwIcmREJBgmGVJBtoJn8FNB'
        'NMEmSkJaeAB6ALWDJMNSRFJFSoNnAnoAUkGyfAhyZAy6fAADZAYkGCYZYN6YRTaE2kXaRZTF'
        'YLYk/P//AABOdWEA/mYyGrJ8//9nIjQa5UlB+QAAASTQwUP5AACl/tLBU0ImGreYt5lRyv/4'
        'YNZOdUotAbxmAP8aDHkAVQAAbv5nHmEA/n4wOQACfEpnAP8CU0AzwAACfEphpkH6AodgIGEA'
        '/mAwOQACfEqweQACfEhkAP7eYYpSeQACfEpB+gJsLwhhAP4GYQDQ1mEA6YBQ+QAAAEcgX3AG'
        'YAC7mrB8AAVmEko5AAJ8R2YiSnkAAnxKZhpgFko5AAJ8R2YOMjkAAnxKsnkAAnxIZQJ6A051'
        'YQDQZGcuLwgT/AABAAJ8T0H6ASphALrkR/kAAG4sQfrj72EAq3YgX2EAq3BB+gG9YACraAw5'
        'AAIAAnvlZgRhALquUPkAAnxNTnVR+QACfE0z7QD+AACl7jPtAQAAAKXwYQCufmEArwYreQAC'
        'e5ICIih5AAJ7ik6UO3wAyQFWQjkAAnvZUfkAAnvkUPkAAnxMQfkAAAEkQ/kAAs0sYQCL4GEA'
        'm85B+QAAAYphAOcyMAFhAIxsLzkAAnsOTnVKQGfQUfkAAnxMsHwAAmcQSjkAAnvmZwCKGFD5'
        'AAJ8TlD5AAJ75GAA7yJKOQACfExmEi85AAJ7FiAtAl6wvAAAAAhOdSAtAl6wvAAAAAhvLiB5'
        'AAJ7QiJ5AAJ6tkPpADQoeQACevJOlCt5AAJ7kgIiKHkAAnuKTpRYj3ACYIJOdQAEAAABOIAC'
        'AAAAAAAAAAAAWAANACIALAAAQloAAH9cAIAADQAuABMAAEKmAABEq///UGxheSB0aGUgbGV2'
        'ZWwgYXMgaXQgaXMgbm93IChFKQBVbmRvIHRoZSBsYXN0IGNoYW5nZSAoVSkAUmVkbyB0aGUg'
        'Y2hhbmdlIHVuZG9uZSAoU2hpZnQrVSkAVGVzdCBwbGF5IGl0IGFsbCB0aGUgc2FtZSAoUmV0'
        'dXJuKQAuIFRlc3Q/AFJldHVybjogdGVzdCAgICBFc2M6IGtlZXAgZWRpdGluZwBVbmRvbmUA'
        'UmVkb25lAAAjyAACahYjyQACahozwAACaiYz/P//AAJqKEK5AAJqIkJ5AAJqKkJtAq4IOQAG'
        'AL/gAWf2KHkAAnt2TpRhBGAAAegkeQACahZ8AEpSawphYkXqABBSRmDyYQCaGiR5AAJqFkpS'
        'awphAACmReoAEGDyYACbPDI5AAJqJrFBZzIzwAACaiYkeQACahZ8AEpSayANAWcUSOdCIGEY'
        'YQCZ2GFuYQCbDEzfBEJF6gAQUkZg3E51SOf/4Hgeeh9+HTA5AAJqJg0AZwZ4HHodfg9MkgAH'
        'PAJ2EmEAAdo4BXYBYQAB0nQBdhJhAAHKOAfQRlNAUkF2EWEAAbxMkgAHUkDSfAARU0J2AWEA'
        'AapM3wf/TnUW/AAHMBLiSBbAMCoAAlhA4kgWwDAS0GoABOJIFsAW/ABkFvwABRb8AAhCGyBq'
        'AAhgAJmSKHkAAnuGTpQoeQACe3ZOlGEArfQwLQEGMi0BCGF6M8AAAmooYQAAwDI5AABu/Gck'
        'JHkAAmoWcABKUmsOsmoABmc2ReoAEFJAYO4yOQAAbv5w/U51cPxKLQHCZhpw/0otAb5nEjA5'
        'AAJqKGoMcP4yLQEGNC0BCE51MjkAAmomAQFmEEJ5AAJqKj8AYQCYljAfTnUyAHD7TnUkeQAC'
        'ahZ0ADYSayiwQ2Uc1moABLBDZBQ2KgACskNlDNZ8ABKyQ2QEMAJOdUXqABBSQmDUcP9OdSPI'
        'AAJqHjP8AJYAAmoqQrkAAmoiTnVKeQACaipnEFN5AAJqKiB5AAJqHnQAYBwgeQACahowOQAC'
        'aihrDCJ5AAJqFulIIHEADHQBsfkAAmoiZ0ojyAACaiJI5yCAcAAyPAC4NDwBQHYMKHkAAnr+'
        'TpRM3wEEYQCX7Bb8AAdCGxb8AFwW/ACgFvwAZBb8AAUW/AAIFsJhAJgqYACZAk51SOf/4CB5'
        'AAJqEsL8ACjRwTIA5knQwToA2kJTRT4F5k+eQcB8AAdy/+ApynwAB3AHkEV0/+EqSkdmAsIC'
        'fAQiSDoDU0UkSQgEAABnGkpHZgSDEmAygxowB1VAawZQ2lHI//yFEmAgRgFGAkpHZgTDEmAQ'
        'wxowB1VAawZR2lHI//zFEkYBRgJD6QAoUc3/uEHoH0DiTFHO/6hM3wf/TnUoeQACevpOlGEA'
        'lxxB+gSuMjwAAGEAl2xhAACKQfoE0TI8AGBhAJdcYQCYNkH6BEpD+gTYcABhAPx6E/wABgAC'
        'e9lhAP2wsHz//GcGSkBr6mcKQjkAAnvZkchOdUI5AAJ72WEAlpphAAO4YQAAkEH6BUxKQGsg'
        'R/kAAmpuQfoFNWEApaZB+QACfHFhAKWcQhNB+QACam4vCGEAi+BhAJZWIF9OdUH6myoyPAAw'
        'YQCT3EH6BCsyPABAYQCT0DI8ADBhAJPUMDkAAnvcYQCM/EHSdB82PADOYQCW9DI8AEBhAJO2'
        'QfoEA0oqADxnAJaYQeoAIHQYNjwAzmAAltJI539+JHkAAnquQfkAAnxqTqoAWGEAA1xB+QAC'
        'fGpOqgAkSoBmRkf5AAJqrj45AAJqLGAUQfkAAnxxIkthAI2sSkBnJEfrACBRz//qDHkAgAAC'
        'aixkEiJLQfkAAnxxEthm/FJ5AAJqLHAAYAJw/0zffv5OdTI5AAJqLGciQ/kAAmquU0EgTEjn'
        'QEBhAI1eTN8CAkpAZwxD6QAgUcn/6LAATnUgTEP5AAJ8amEAAoZI5wAgJHkAAnquQfkAAnxq'
        'TqoAJCRfSoBXwEoATnUwOQACe9xhAIv4Q9JF+QACfBJyABAZsDwALmYGSikAA2cUYQCQ7mYM'
        'snwAFGQGFMBSQWDgcgATwQACfBBCuQACfEIoeQACevpOlGEAlRJB+gKxMjwAAGEAlWJhAP6A'
        'QfoCuzI8AFhhAJJaYQCWLGFSQfoCYEP6AuhwAGEA+m4T/AAHAAJ72WEA+6SwfP/8ZyiwfP/9'
        'ZhIwAWEAkDJn4EK5AAJ8QmEcYNZKQGvSZgphTEpAagZhDGDGkchCOQACe9lOdTA8AHAyPABY'
        'NDwA0HYMKHkAAnr+TpRwADI8AHQ0PAFAdgwoeQACev5OlGEAlHAyPABYYQCRpGAAkYZB+plU'
        'SjkAAnwQZwABRmEAkoIwOQACe9xhAIrqQdJD+QACfChhAIv8QfoC+EpAZwABImEAkoRB+pla'
        'vnkAAnvaZQABEEH5AAJ8KEP5AAJ8amEAARgkeQACeq5B+QACfGpOqgAkQfqZLEqAZgAA5mEA'
        'AOxB+QACfGpD+QACai4S2Gb8JHkAAnquQfkAAmouTqoAJC4AQfoCq768AAGAAGIAALIvB2EA'
        'k5QuHyR5AAJ6rkqHZxBB+QACai5D+QAA6hJOqgAIQfkAAnwoQ/kAAnxqYQAAmCAHQfkAAnxq'
        'Q/kAAOoSTqoADGEAAMJB+QACfGpOqgAksIdmUkH5AAJqLkP5AAJ8ahLYZvxhAP0uQfoCe0pA'
        'ayBH+QACam5B+gH6YQCiREH5AAJ8KGEAojpCE0H5AAJqbi8IYQCIfmEAkXxhQmEAku4gX3AA'
        'TnVhAJLkQfoCFyPIAAJ8QnD/TnUwOQACe9xhAImgYACKni8IQfqVghLYZvwTfAAv//8gXxLY'
        'ZvxOdb55AAJ72mUIPjkAAnvaU0czxwACe9xrDnAAMAeA/AAJM8AAAnveTnVCrQKqQm0Crk51'
        'AAgAogBgAA0AAF+aAACISgDYAKIAYAARAAAeqAAAiGz//wAIAKIAYAANAACH3AAAiIAA2ACi'
        'AGAAEQAAHqgAAIih//9EZWxldGUgTGV2ZWwAUmVuYW1lIExldmVsAFJlbmFtZQBUaXRsZQBO'
        'ZXcAZGFtYWdlZABEZWxldGluZyBjYW5ub3QgYmUgdW5kb25lLgBSZXR1cm46IGRlbGV0ZSAg'
        'ICBFc2M6IGtlZXAAVHlwZSB0aGUgbmV3IG5hbWUgb2YgdGhlIGZpbGUARGVsZXRlIHRoZSBm'
        'aWxlIGZvciBnb29kIChSZXR1cm4pAEtlZXAgdGhlIGZpbGUgKEVzYykAR2l2ZSB0aGUgZmls'
        'ZSB0aGlzIG5hbWUgKFJldHVybikAS2VlcCB0aGUgb2xkIG5hbWUgKEVzYykARGVsZXRlZCAA'
        'VGhlIGZpbGUgY291bGQgbm90IGJlIGRlbGV0ZWQAUmVuYW1lZCB0byAAVGhlIGZpbGUgaGFz'
        'IHRoaXMgbmFtZSBhbHJlYWR5AFRoaXMgZmlsZSBpcyB0b28gbGFyZ2UgdG8gcmVuYW1lIGhl'
        'cmUAVGhlIG5ldyBmaWxlIGNvdWxkIG5vdCBiZSB3cml0dGVuAENvcGllZCwgYnV0IHRoZSBv'
        'bGQgZmlsZSBpcyBzdGlsbCB0aGVyZQAAAAAD7AAAAM8AAAAAAAAHHAAABzYAAAdOAAAHZgAA'
        'B34AAAeWAAAHsAAAB8gAAAfgAAAH+AAADtIAAA7WAAAO4gAADuYAAA7yAAAO9gAADwIAAA8G'
        'AAAPEgAADxYAAA8iAAAPJgAADzQAAA84AAAPRAAAD0gAAA9UAAAPWAAAD2YAAA9qAAAPdgAA'
        'D3oAAEDmAABA6gAAQPYAAED6AABBBgAAQQoAAEEWAABBGgAAQSYAAEEqAABBNgAAQToAAEFG'
        'AABBSgAAQVYAAEFaAABBZgAAQWoAAEGGAABBigAAQZYAAEGaAABBpgAAQaoAAEG2AABBugAA'
        'QcgAAEHMAABB2AAAQdwAAEHoAABB7AAAQhoAAEIeAABCKgAAQi4AAEI6AABCPgAAXKQAAFyo'
        'AABcrAAAXLAAAFy0AABcuAAAXLwAAFzAAABcxAAAXMgAAFzMAABc0AAAXNQAAFzYAABc3AAA'
        'XOAAAFzkAABc6AAAXOwAAFzwAABc9AAAXPgAAFz8AABdAAAAXQwAAF0QAABdHAAAXSAAAF0s'
        'AABdMAAAXTwAAF1AAABdTAAAXVAAAF1cAABdYAAAXWwAAF1wAABdfAAAXYAAAF2MAABdkAAA'
        'XawAAF2wAABdzAAAXdAAAF3cAABd4AAAXfwAAF4AAABeDAAAXhAAAF4cAABeIAAAXiwAAF4w'
        'AABePgAAXkIAAF5eAABeYgAAXm4AAF5yAABuFgAAbjAAAG5KAABzBgAAcwoAAHMWAABzGgAA'
        'cyYAAHMqAABzNgAAczoAAHNGAABzSgAAc1YAAHNaAABzZgAAc2oAAHN2AABzegAAc4YAAHOK'
        'AABzlgAAc5oAAHOmAABzqgAAc8YAAHPKAABz1gAAc9oAAHPmAABz6gAAc/YAAHP6AAB0BgAA'
        'dAoAAHQWAAB0GgAAdDYAAHQ6AAB0RgAAdEoAAHRmAAB0agAAdHYAAHR6AAB0lgAAdJoAAHSm'
        'AAB0qgAAdMgAAHTMAAB02AAAdNwAAHT6AAB0/gAAdQoAAHUOAAB1GgAAdR4AAHUqAAB1LgAA'
        'dToAAHU+AAB+6AAAfuwAAH74AAB+/AAAh4YAAIeKAACHlgAAh5oAAIeoAACHrAAAh7gAAIe8'
        'AAAFKwAAAAEAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAABngAAAbAAAAG6AAAB1AAA'
        'Ae4AAAIUAAACLgAAAjQAAAJOAAACVAAAAmAAAAJmAAACcgAAAngAAAKEAAACigAAApYAAAKc'
        'AAACqAAAAq4AAAK6AAACwAAAAswAAALSAAAC3gAAAuQAAALwAAAC9gAAAwIAAAMIAAADFAAA'
        'AxoAAAMmAAADLAAAAzgAAAM+AAADSgAAA1AAAANcAAADYgAAA24AAAN0AAADgAAAA4YAAAOS'
        'AAADmAAAA6QAAAOqAAADtgAAA7wAAAPIAAADzgAAA9oAAAPgAAAD7AAAA/IAAAP+AAAEBAAA'
        'BBAAAAQWAAAEIgAABCgAAAQ0AAAEOgAABEYAAARMAAAEWAAABF4AAARqAAAEcAAABHwAAASC'
        'AAAEjgAABJQAAASgAAAEpgAABLIAAAS4AAAExAAABMoAAATWAAAE3AAABOgAAATuAAAE+gAA'
        'BQAAAAUMAAAFEgAABR4AAAUkAAAFMAAABTYAAAVCAAAFSAAABVQAAAVaAAAFZgAABWwAAAV4'
        'AAAFfgAABYoAAAWQAAAFnAAABaIAAAWuAAAFtAAABcAAAAXGAAAF0gAABdgAAAXkAAAF6gAA'
        'BfYAAAX8AAAGCAAABg4AAAYaAAAGIAAABiwAAAYyAAAGPgAABkQAAAZQAAAGVgAABmIAAAZo'
        'AAAGdAAABnoAAAaGAAAGjAAABpgAAAaeAAAGqgAABrAAAAa8AAAGwgAABs4AAAbWAAAG3gAA'
        'BuQAAAbwAAAG9gAABwIAAAcMAAAHJgAAB0AAAAdYAAAHcAAAB4gAAAegAAAHugAAB9IAAAfq'
        'AAAIGgAACDQAAAhMAAAIVAAACGQAAAhqAAAIcAAACHwAAAieAAAIpgAACK4AAAi+AAAIxgAA'
        'CMwAAAjUAAAI3AAACOgAAAj+AAAJBgAACQ4AAAkcAAAJJAAACSwAAAk8AAAJYgAACXoAAAmC'
        'AAAJlgAACZ4AAAmoAAAJsAAACbYAAAm8AAAJxAAACcwAAAnUAAAJ2gAACeIAAAnqAAAJ/gAA'
        'CgYAAAoMAAAKJgAACjAAAApAAAAKVgAAClwAAApuAAAKdAAACn4AAAqKAAAKlgAACp4AAAq0'
        'AAAKugAACsIAAArIAAAK0gAACuIAAArqAAAK9AAACvwAAAusAAAMQAAADPAAAA0wAAANYAAA'
        'DYwAAA2YAAANoAAADboAAA3EAAANzAAADdoAAA3kAAAN6gAADiIAAA4yAAAOYgAADmoAAA6U'
        'AAAOsgAAD4IAAA+KAAAPmgAAD6AAAA+qAAAPsAAAD7YAAA/EAAAQEgAAEBwAABAkAAAQLgAA'
        'EDYAABA+AAAQUgAAEFwAABCEAAAQigAAEKYAABCyAAAQugAAEMYAABDaAAAQ9AAAEQgAABEQ'
        'AAARMAAAEUwAABFSAAARZAAAEWoAABF0AAARhgAAEZIAABGcAAARqgAAEbwAABHEAAAR1gAA'
        'EmIAABJuAAASkgAAEp4AABKwAAASugAAEsoAABLuAAAS9AAAEyQAABMqAAATTgAAE1QAABN0'
        'AAATfAAAE5gAABOkAAAT0gAAE+gAABQMAAAUVAAAFI4AABS8AAAUygAAFOgAABTuAAAU9AAA'
        'FQYAABU2AAAVTgAAFWwAABWIAAAVkgAAFa4AABW6AAAVxAAAFcwAABXUAAAWHgAAFjIAABZq'
        'AAAW3AAAFvAAABcSAAAXUAAAF2wAABd0AAAXqAAAF7QAABfKAAAX2AAAF+oAABfyAAAX+AAA'
        'GAIAABgIAAAYIgAAGC4AABg0AAAYUAAAGF4AABhkAAAYbAAAGIYAABiUAAAYqAAAGLgAABjo'
        'AAAY8AAAGSYAABk+AAAZaAAAGXAAABmwAAAZuAAAGcYAABnQAAAZ1gAAGdwAABnmAAAZ7AAA'
        'GfIAABn8AAAaBgAAGhQAABokAAAaLgAAGtgAABtCAAAbagAAG3AAABt6AAAbgAAAG7QAACRS'
        'AAAkYgAAJGwAACTEAAAlSgAAJwAAACcQAAAnFgAAJxwAACciAAAnKAAAJzAAACc2AAAnTgAA'
        'J2wAACdyAAAnegAAJ4AAACeIAAAnqAAAJ8IAACfKAAAn0AAAJ9gAACfmAAAoMAAAKHAAACiQ'
        'AAAopgAAKK4AACi0AAAoxgAAKMwAACjSAAAo3AAAKOgAACjuAAAo/gAAKQQAACkOAAApFAAA'
        'KSIAACkeAAApKAAAKZoAACmgAAApqgAAKbAAACm6AAApwAAAKcoAACnUAAAp3AAAKeIAACns'
        'AAAp8gAAKfwAACoQAAAqGAAAKh4AACokAAAqMgAAKjwAACpCAAAqSAAAKlgAACpwAAAqeAAA'
        'KoIAACp+AAAqjAAAKogAACqSAAAqmAAAKp4AACqqAAAqtAAAKsAAACrGAAAq0AAAKuYAACrs'
        'AAAq8gAAKvgAACr+AAArBAAAKwwAACsUAAArJAAAKzAAACs2AAArPgAAK0gAACtSAAArXgAA'
        'K2wAACt0AAArgAAAK4wAACuUAAArogAAK6oAACu6AAArxAAAK84AACvWAAAsKgAALDIAACw8'
        'AAAsUAAALFgAACxmAAAsbAAALHoAACyOAAAsxgAALM4AACzWAAAs5AAALOwAAC0CAAAtGAAA'
        'LSgAAC0yAAAtOAAALUYAAC2gAAAtsAAALb4AAC3GAAAt2AAALeAAAC3wAAAt+AAALf4AAC4G'
        'AAAuPgAALmwAAC6OAAAvAgAALw4AAC8kAAAvOAAAL0AAAC9KAAAvWgAAL2gAAC92AAAvfAAA'
        'L44AAC+eAAAwXAAAMSwAADE4AAAxbAAAMYIAADGKAAAxkAAAMZYAADGgAAAxpgAAMbwAADHC'
        'AAAxygAAMdAAADHYAAAx3gAAMeQAADHsAAAx8gAAMfoAADICAAAyEAAAMhoAADIqAAAylAAA'
        'Mq4AADK0AAAyugAAMsAAADLQAAAy1gAAMt4AADLkAAAy+AAAMwQAADMQAAAzHAAAMyQAADMy'
        'AAAzPAAAM0QAADNSAAAzXgAAM2QAADNwAAAzeAAAM4AAADOKAAAzkgAAM5oAADOkAAAzrgAA'
        'M7oAADPEAAAz0AAAM9YAADP6AAA0BAAANAoAADQcAAA0JAAANDQAADQ+AAA0RgAANFAAADRW'
        'AAA0XgAANGYAADRwAAA0bAAANHoAADSAAAA0hgAANIwAADSUAAA00AAANNoAADTyAAA1BgAA'
        'NRQAADUcAAA1LgAANTwAADVGAAA1TgAANVQAADVaAAA1YAAANnIAADasAAA2sgAANt4AADcI'
        'AAA3DgAANxYAADccAAA3zgAAN9oAADfgAAA38gAAN/wAADgQAAA4GgAAODYAADhCAAA4TAAA'
        'OFgAADhmAAA4fAAAOIYAADiSAAA4mAAAOJ4AADimAAA4rAAAOLgAADi+AAA4ygAAOOIAADjw'
        'AAA4/AAAOQIAADkSAAA5GgAAOSIAADkoAAA5LgAAOTgAADlMAAA5YgAAOW4AADmIAAA5lAAA'
        'OagAADm4AAA5yAAAOdIAADn0AAA6BgAAOhQAADogAAA6MgAAOjgAADpEAAA6VgAAOqwAADss'
        'AAA7XgAAO2wAADt6AAA7iAAAO5YAADusAAA7tAAAO8AAADvUAAA73AAAO+IAADvsAAA78gAA'
        'PDoAADxcAAA8aAAAPJgAADysAAA8tAAAPMYAADzSAAA84gAAPPAAADz+AAA9EgAAPSIAAD0u'
        'AAA9NAAAPToAAD1AAAA9VAAAPZAAAD22AAA9vAAAPcoAAD3SAAA+DAAAPhQAAD4oAAA+MgAA'
        'PlIAAD5cAAA+ZgAAPm4AAD50AAA+iAAAPo4AAD6YAAA+pgAAPq4AAD62AAA+vAAAPsQAAD7K'
        'AAA+1gAAPt4AAD8oAAA/NgAAP0QAAD+CAAA/iAAAP5wAAD+wAAA/wgAAP8gAAD/uAAA/9AAA'
        'P/4AAEAgAABAJgAAQDwAAEBWAABAeAAAQJoAAEY6AABGTgAARlQAAEeiAABHqAAAR64AAEe0'
        'AABHyAAAR9IAAEfeAABIXAAASIQAAEiOAABIoAAASLAAAEi2AABIvAAASMIAAEjIAABIzgAA'
        'SNoAAEjqAABI+gAASRIAAEk2AABJSgAASV4AAElmAABJngAASaYAAEpSAABKoAAASvIAAEr8'
        'AABLVAAAS1wAAEtiAABLaAAAS24AAEt0AABLegAAS4IAAEuKAABLlgAAS6AAAEuqAABLtAAA'
        'S9AAAEvgAABL6AAAS/gAAEv+AABMBAAATAoAAEwgAABMNAAATGwAAEx0AABMfAAATIgAAEyS'
        'AABMnAAATKgAAEyyAABMugAATMQAAEzQAABM3AAATOQAAEzsAABM/AAATQwAAE0SAABNGgAA'
        'TSAAAE0mAABNLAAATVIAAE1gAABNbAAATXgAAE2EAABNigAATZgAAE2oAABNtAAATboAAE3A'
        'AABN0gAATdgAAE3eAABN8AAATf4AAE4qAABOMAAATkgAAE5OAABOYAAATmgAAE50AABOrAAA'
        'TrgAAE7AAABO2gAATvAAAE72AABO/AAATxAAAE8yAABQOAAAUEYAAFB0AABQrgAAUOoAAFDw'
        'AABQ/AAAUQQAAFEaAABRIAAAUSgAAFE6AABRSgAAUVgAAFFiAABRXgAAUXIAAFGEAABRigAA'
        'UZYAAFGeAABRsAAAUi4AAFJGAABSTAAAUlgAAFJgAABSZgAAUnIAAFKQAABSpAAAUqoAAFK2'
        'AABSvAAAUsIAAFLOAABS1AAAUuQAAFMWAABTTgAAU1QAAFNeAABTZAAAU3oAAFOGAABTkAAA'
        'U8QAAFPcAABUAgAAVCAAAFQoAABURAAAVEwAAFRSAABUWAAAVF4AAFRyAABUegAAVIgAAFSS'
        'AABUmgAAVLIAAFUEAABVLAAAVWoAAFW+AABV9gAAVwAAAFcGAABXFgAAV1QAAFdmAABXcgAA'
        'V34AAFfAAABYrgAAWL4AAFjUAABY+AAAWQgAAFlgAABZbgAAWZIAAFm2AABZ5AAAWewAAFn0'
        'AABZ/gAAWgYAAFoMAABaIAAAWiwAAFo2AABaPAAAWkQAAFpKAABaVAAAWloAAFpmAABabgAA'
        'WqAAAFqmAABa1gAAWtwAAFrmAABa9AAAWv4AAFsMAABbRgAAW04AAFuoAABbsAAAW/AAAFwA'
        'AABcOgAAY3oAAGOAAABjkgAAY5wAAGOYAABjtAAAY8YAAGPMAABj2AAAY+AAAGQcAABkRAAA'
        'ZWQAAGWOAABllAAAZZoAAGWiAABlqAAAZbIAAGW4AABl0gAAZeQAAGYGAABmEgAAZj4AAGZe'
        'AABmcAAAZnwAAGaCAABmqgAAZroAAGbYAABm3gAAZvAAAGb+AABnDAAAZyQAAGc2AABnQAAA'
        'Z1AAAGdWAABnXAAAZ4YAAGf2AABn/gAAaBoAAGhwAABodgAAaIYAAGicAABosAAAaLwAAGjM'
        'AABo3gAAaQQAAGkUAABpGgAAaSAAAGkmAABpNAAAaUAAAGlMAABpVAAAacYAAGnOAABqJAAA'
        'ajoAAGpEAABqTgAAalQAAGpcAABqYgAAamgAAGp0AABqegAAarYAAGrCAABqzAAAauAAAGro'
        'AABq/AAAawQAAGsOAABrHgAAaygAAGuMAABrkgAAa5gAAGvoAABr7gAAbBIAAGwmAABsLgAA'
        'bDgAAGw+AABsRgAAbEwAAGxWAABsYgAAbGgAAGx+AABshAAAbKwAAGyyAABs5gAAbPIAAGz8'
        'AABtAgAAbQoAAG0SAABtGAAAbSQAAG0wAABtOAAAbUAAAG1IAABtVgAAbWYAAG12AABtgAAA'
        'bZwAAG2iAABtqAAAbbYAAG3GAABtzgAAbeIAAG3yAABuBgAAbiAAAG46AABuVAAAbmAAAG50'
        'AABufgAAboYAAG6eAABurgAAbsYAAG7eAABu9gAAbyAAAG8oAABvRAAAb1gAAG9oAABvggAA'
        'b5AAAG+gAABvxgAAb9QAAG/mAABv7AAAb/4AAHAEAABwFgAAcBwAAHBGAABwUAAAcHYAAHEE'
        'AABxEAAAcVoAAHFuAABxggAAciwAAHI8AAByYgAAcngAAHKYAAByrAAAct4AAHLmAAB6+AAA'
        'ev4AAHsEAAB7CgAAexAAAHsWAAB7IAAAeyYAAHsyAAB7PAAAe1IAAHtYAAB7YAAAe2gAAHuK'
        'AAB7lAAAe5oAAHugAAB7rgAAe6oAAHu2AAB7vgAAe9gAAHvgAAB75gAAe+4AAHv0AAB7/gAA'
        'fAQAAHwSAAB8GgAAfCAAAHwsAAB8QAAAfEYAAHxaAAB8YAAAfGgAAHxuAAB82AAAfOAAAH0C'
        'AAB9DgAAfRoAAH0sAAB9MgAAfT4AAH1WAAB9agAAfXIAAH18AAB9hAAAfYoAAH2gAAB9rgAA'
        'fcwAAH3YAAB94AAAfegAAH3wAAB9/gAAfgYAAH4UAAB+GgAAfiAAAH4mAAB+LAAAfjoAAH5K'
        'AAB+VgAAfmIAAH5sAAB+cgAAfnwAAH6EAAB+ogAAfqgAAH6yAAB+ugAAfsIAAH+6AAB/wAAA'
        'f8YAAH/OAAB/1AAAf9oAAH/uAAB//AAAgBYAAIAuAACAOAAAgD4AAIB2AACA/AAAgQQAAIEa'
        'AACBJAAAgSwAAIFGAACBYAAAgXQAAIF+AACBlAAAgcwAAIHUAACB2gAAgeIAAIHqAACB8AAA'
        'gfoAAIIAAACCCAAAghYAAIIeAACCNAAAgm4AAIMIAACDRAAAg1oAAINkAACDfgAAg4wAAIOY'
        'AACDzAAAhAgAAIQOAACEHAAAhCoAAIQwAACEOAAAhFIAAIRcAACEZgAAhHgAAISAAACEqAAA'
        'hLYAAIS8AACE0AAAhNwAAIUGAACFDAAAhRIAAIVQAACFbgAAhYoAAIWgAACFtAAAhdAAAIXe'
        'AACF6gAAhgYAAIYQAACGFgAAhiAAAIYmAACGPgAAhkQAAIZOAACGVAAAhnYAAIaAAACGhgAA'
        'hpAAAIaWAACGogAAhqgAAIa2AACGxAAAhsoAAIbgAACG7gAAhvoAAIceAACHKAAAh04AAIdW'
        'AACHXgAAh24AAAAAAAAD8gAAA+sAAMQvAAAD8g=='
    ),
    'Lemmings2.info': (
        '4xAAAQAAAAAAAAAAABoAEwAEAAMAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAB'
        'AAAAAYAAAACAAAAAAAAAAAAAAAAAACgAAAAAAAAaABIAAgAAAAEDAAAAAAAANYAAAH/AAAD/'
        '4AABwHAAAZEwAACAIAAAAAAAAAAAAAH/8AAD//gAAf/wAAD/4AAA/+AAAP/gAAB7wAAAe8AA'
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAG7AAAB/wAAAf8AAAD+AAAH/8AAD//gAB//8AAb/'
        '7AAA/+AAAP/gAAB7wAAAe8AAAPvgAAH78AAAAAAIV0hETG9hZAAAAAAQAAAAFlNMQVZFPUxl'
        'bW1pbmdzMi5zbGF2ZQAAAAAIUFJFTE9BRAAAAAANTk9XUklURUNBQ0hFAA=='
    ),
}
# END GENERATED BY build.py


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def embedded(name: str) -> bytes:
    """A file build.py embedded: the slave, the editor or the icon."""
    if name not in BLOBS:
        raise SystemExit(f'{name} is missing: run build.py first')
    data = base64.b64decode(BLOBS[name])
    if sha256(data) != BLOB_SHA256[name]:
        raise SystemExit(f'{name}: the embedded copy is damaged')
    return data


# --- Disk images -------------------------------------------------------------

SPREAD = [sum(((byte >> bit) & 1) << (2 * bit) for bit in range(8)) for byte in range(256)]


def mfm_longs(odd: bytes, even: bytes) -> list[int]:
    """Long words from their odd and their even bits, 16 bits each, as an
    AmigaDOS sector stores them before MFM encoding."""
    return [(SPREAD[odd[i]] << 16 | SPREAD[odd[i + 1]]) << 1
            | SPREAD[even[i]] << 16 | SPREAD[even[i + 1]] for i in range(0, len(odd), 2)]


def mfm_checksum(data: bytes) -> int:
    value = 0
    for i in range(0, len(data), 2):
        value ^= SPREAD[data[i]] << 16 | SPREAD[data[i + 1]]
    return value


def ipf_to_adf(image: bytes) -> bytes:
    """The AmigaDOS sectors of an IPF image as an ADF image.

    An IPF image holds a track's blocks as streams of elements; on an
    AmigaDOS track each sector is a block whose data element is the 540
    bytes after the sync words, before MFM encoding: the sector header
    (format, track, sector, sectors to the gap), the label, the two
    checksums and the 512 data bytes, each long word as its odd bits, then
    its even bits. A track without such sectors (disk 3's protection
    track) leaves zeros."""
    if image[:4] != b'CAPS':
        raise SystemExit('not an IPF image')
    tracks, areas = {}, {}
    at = 0
    while at < len(image):
        kind = image[at:at + 4]
        length = struct.unpack_from('>I', image, at + 4)[0]
        if kind == b'IMGE':
            fields = struct.unpack_from('>14I', image, at + 12)
            tracks[fields[13]] = fields                # by data key
        elif kind == b'DATA':
            size, _, _, key = struct.unpack_from('>4I', image, at + 12)
            areas[key] = image[at + 28:at + 28 + size]
            at += size
        at += length
    adf = bytearray(80 * 2 * 11 * 512)
    for key, (cylinder, side, *_rest) in tracks.items():
        if cylinder >= 80:
            continue                                    # unformatted extra cylinders
        area, blocks = areas[key], tracks[key][10]
        for block in range(blocks):
            descriptor = struct.unpack_from('>8I', area, 32 * block)
            flags, at = descriptor[5], descriptor[7]
            sector = None
            while area[at] & 31:                        # 0: the stream's end
                kind, width = area[at] & 31, area[at] >> 5
                size = int.from_bytes(area[at + 1:at + 1 + width], 'big')
                at += 1 + width
                count = (size + 7) // 8 if flags & 2 else size
                if kind == 2 and count == 540:          # data
                    sector = area[at:at + 540]
                if kind != 5:                           # fuzzy bits store nothing
                    at += count
            if sector is None:
                continue
            header = mfm_longs(sector[0:2], sector[2:4])[0]
            header_sum = mfm_longs(sector[20:22], sector[22:24])[0]
            data_sum = mfm_longs(sector[24:26], sector[26:28])[0]
            track, number = header >> 16 & 255, header >> 8 & 255
            if (header >> 24 != 0xFF or track != cylinder * 2 + side or number > 10
                    or mfm_checksum(sector[0:20]) != header_sum
                    or mfm_checksum(sector[28:540]) != data_sum):
                raise SystemExit(f'IPF image: a damaged sector on track {cylinder}.{side}')
            words = mfm_longs(sector[28:284], sector[284:540])
            place = (track * 11 + number) * 512
            adf[place:place + 512] = struct.pack('>128I', *words)
    return bytes(adf)


def ofs_files(adf: bytes) -> dict[str, bytes]:
    """Every file of an AmigaDOS (OFS) disk image, by its path."""
    def block(number: int) -> bytes:
        return adf[number * 512:(number + 1) * 512]

    def long(data: bytes, offset: int) -> int:
        return struct.unpack_from('>I', data, offset)[0]

    files: dict[str, bytes] = {}

    def walk(directory: bytes, prefix: str) -> None:
        for slot in range(72):
            key = long(directory, 24 + 4 * slot)
            while key:
                header = block(key)
                name = prefix + header[433:433 + header[432]].decode('latin-1')
                kind = struct.unpack_from('>i', header, 508)[0]
                if kind == 2:                           # a directory
                    walk(header, name + '/')
                elif kind == -3:                        # a file
                    chunks, part = [], header
                    while True:
                        for index in range(long(part, 8)):
                            data = block(long(part, 308 - 4 * index))
                            chunks.append(data[24:24 + long(data, 12)])
                        extension = long(part, 504)
                        if not extension:
                            break
                        part = block(extension)
                    content = b''.join(chunks)
                    if len(content) != long(header, 324):
                        raise SystemExit(f'{name}: its size does not match its blocks')
                    files[name] = content
                key = long(header, 496)

    walk(block(880), '')
    return files


# --- RNC method 1 --------------------------------------------------------------

def crc16(data: bytes) -> int:
    """CRC-16 with the polynomial $8005, reflected (RNC's and WHDLoad's)."""
    table = []
    for i in range(256):
        value = i
        for _ in range(8):
            value = (value >> 1) ^ 0xA001 if value & 1 else value >> 1
        table.append(value)
    value = 0
    for byte in data:
        value = (value >> 8) ^ table[(value ^ byte) & 0xFF]
    return value


class BitStream:
    """RNC's bit stream: 16-bit little-endian words, read from the low bit,
    with the literal bytes between them."""

    def __init__(self, data: bytes):
        self.data = data
        self.cursor = 0
        self.pending = 0
        self.buffer = self.peek_word()

    def peek_word(self) -> int:
        # The decoder looks up to two bytes past the end; zeros are safe there.
        return int.from_bytes(self.data[self.cursor:self.cursor + 2], 'little')

    def read(self, width: int) -> int:
        value = self.buffer & ((1 << width) - 1)
        if width > self.pending:
            available = min(16, (len(self.data) - self.cursor) * 8)
            if width - self.pending > available:
                raise ValueError('truncated RNC stream')
            self.buffer >>= self.pending
            width -= self.pending
            self.cursor += 2
            self.buffer = (self.buffer & 0xFFFF) | (self.peek_word() << 16)
            self.pending = available
        self.pending -= width
        self.buffer >>= width
        return value

    def literals(self, count: int) -> bytes:
        if count == 0:
            return b''
        end = self.cursor + count
        if end > len(self.data):
            raise ValueError('truncated RNC literals')
        data = self.data[self.cursor:end]
        self.cursor = end
        self.buffer &= (1 << self.pending) - 1
        self.buffer |= self.peek_word() << self.pending
        return data


def huffman_table(bits: BitStream, previous):
    count = bits.read(5)
    if count == 0:
        return previous
    if count > 16:
        raise ValueError('RNC table over 16 symbols')
    widths = [bits.read(4) for _ in range(count)]
    table, code = [], 0
    for width in range(1, 17):
        for symbol, size in enumerate(widths):
            if size == width:
                table.append((width, int(f'{code:0{width}b}'[::-1], 2), symbol))
                code += 1
        code <<= 1
    return table


def huffman_value(bits: BitStream, table) -> int:
    for width, code, symbol in table or ():
        if bits.buffer & ((1 << width) - 1) == code:
            bits.read(width)
            return symbol if symbol < 2 else (1 << (symbol - 1)) | bits.read(symbol - 1)
    raise ValueError('invalid RNC code')


def rnc_unpack(data: bytes) -> bytes:
    """An RNC method 1 stream ("RNC", 1, its 18-byte header) unpacked, both
    of its CRCs checked."""
    if data[:4] != b'RNC\x01':
        raise ValueError('not an RNC method 1 stream')
    size, packed, unpacked_crc, packed_crc, _, blocks = struct.unpack_from('>IIHHBB', data, 4)
    stream = data[18:18 + packed]
    if len(stream) != packed or crc16(stream) != packed_crc:
        raise ValueError('RNC stream damaged')
    bits = BitStream(stream)
    bits.read(2)
    out = bytearray()
    tables = [None] * 3
    for _ in range(blocks):
        tables = [huffman_table(bits, previous) for previous in tables]
        chunks = bits.read(16)
        for index in range(chunks):
            count = huffman_value(bits, tables[0])
            if len(out) + count > size:
                raise ValueError('RNC stream damaged')
            out += bits.literals(count)
            if index + 1 == chunks:
                break
            distance = huffman_value(bits, tables[1]) + 1
            count = huffman_value(bits, tables[2]) + 2
            if distance > len(out) or len(out) + count > size:
                raise ValueError('RNC stream damaged')
            for _ in range(count):
                out.append(out[-distance])
    if len(out) != size or crc16(out) != unpacked_crc:
        raise ValueError('RNC stream damaged')
    return bytes(out)


# --- The install ---------------------------------------------------------------

def hunk0(program: bytes) -> int:
    """The file offset of hunk 0's contents in a hunk executable."""
    if struct.unpack_from('>2I', program) != (0x3F3, 0):
        raise SystemExit('not a hunk executable')
    count = struct.unpack_from('>I', program, 8)[0]
    at = 4 * (5 + count)
    if struct.unpack_from('>I', program, at)[0] not in (0x3E9, 0x3EA):
        raise SystemExit('hunk 0 is not a code or data hunk')
    return at + 8


def complete_slave(slave: bytes, main: bytes) -> bytes:
    """The slave with gate_value from the main program's disk-3 check."""
    code = hunk0(main) + GATE_CODE
    if main[code:code + len(GATE_OPCODES)] != GATE_OPCODES:
        raise SystemExit('the main program is not the supported version')
    value = main[code + len(GATE_OPCODES):code + len(GATE_OPCODES) + 4]
    slot = hunk0(slave) + GATE_SLOT
    if slave[slot:slot + 4] != bytes(4):
        raise SystemExit('the embedded slave is not the one patch.py expects')
    return slave[:slot] + value + slave[slot + 4:]


def tile_flags(main: bytes) -> bytes:
    """data/EditorTiles: for each style and tile, the flags most of the
    tile's cells have in the game's own levels: bit 0 Decor (non-colliding,
    cell bit 30), bit 1 Steel (indestructible, cell bit 28). The editor
    gives a new tile these flags."""
    base = hunk0(main)
    counts = [[[0, 0, 0] for _ in range(TILES)] for _ in range(STYLES)]
    for offset, size, digest in LEVEL_BANKS:
        at = base + offset
        packed = struct.unpack_from('>I', main, at + 8)[0]
        bank = rnc_unpack(main[at:at + 18 + packed])
        if len(bank) != size or sha256(bank) != digest:
            raise SystemExit('the main program\'s levels are not the expected ones')
        for record in range(0, size, RECORD_SIZE):
            style = struct.unpack_from('<H', bank, record + RECORD_STYLE)[0]
            for cell in struct.unpack_from(f'>{MAP_CELLS}I', bank, record + RECORD_CELLS):
                tile = cell & CELL_TILE
                if tile:
                    count = counts[style][tile]
                    count[0] += 1
                    count[1] += bool(cell & CELL_DECOR)
                    count[2] += bool(cell & CELL_STEEL)
    table = bytearray(STYLES * TILES)
    for style in range(STYLES):
        for tile, (cells, decor, steel) in enumerate(counts[style]):
            table[style * TILES + tile] = (2 * decor > cells) | (2 * steel > cells) << 1
    return bytes(table)


def read_images(paths: list[Path]) -> dict[int, dict[str, bytes]]:
    """The files of the three disks, from images checked by SHA-256."""
    disks: dict[int, dict[str, bytes]] = {}
    for path in paths:
        data = path.read_bytes()
        known = IMAGES.get(sha256(data))
        if known is None:
            raise SystemExit(f'{path}: not a supported disk image (SHA-256 {sha256(data)})')
        number, kind = known
        if number in disks:
            raise SystemExit(f'{path}: disk {number} given twice')
        disks[number] = ofs_files(ipf_to_adf(data) if kind == 'IPF' else data)
    missing = {1, 2, 3} - disks.keys()
    if missing:
        raise SystemExit(f'disk {min(missing)} is missing')
    return disks


def make_install(disks: dict[int, dict[str, bytes]]) -> dict[str, bytes]:
    """Every file of the install, checked, by its path in the install."""
    out = {}
    for number, name, size, digest in FILES:
        data = disks[number].get(name)
        if data is None or len(data) != size or sha256(data) != digest:
            raise SystemExit(f'disk {number}: {name} is not the expected file')
        out[f'data/{name}'] = data
    packed = disks[2].get(MAIN)
    if packed is None or (len(packed), sha256(packed)) != MAIN_PACKED:
        raise SystemExit(f'disk 2: {MAIN} is not the expected file')
    main = rnc_unpack(packed)
    if (len(main), sha256(main)) != MAIN_UNPACKED:
        raise SystemExit(f'disk 2: {MAIN} did not unpack to the expected program')
    out[f'data/{MAIN}'] = main
    out['data/Editor'] = embedded('Editor')
    out['data/EditorTiles'] = tile_flags(main)
    out[SLAVE] = complete_slave(embedded(SLAVE), main)
    out[ICON] = embedded(ICON)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('images', nargs=3, type=Path, metavar='DISK',
                        help='your images of the three disks (IPF or ADF), in any order')
    parser.add_argument('--out', type=Path, default=Path('Lemmings2'),
                        help='the install directory (default: Lemmings2)')
    args = parser.parse_args()
    for path in args.images:
        if not path.is_file():
            raise SystemExit(f'{path}: no such file')
    files = make_install(read_images(args.images))
    out = args.out
    if out.exists() and not out.is_dir():
        raise SystemExit(f'{out}: not a directory')
    written, kept = 0, []
    for name, data in sorted(files.items()):
        path = out / name
        if name == f'data/{SAVED_POSITIONS}' and path.exists():
            kept.append(name)                           # the player's saved positions
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        written += 1
    (out / 'Levels').mkdir(exist_ok=True)
    levels = len(list((out / 'Levels').glob('*.lvl')))
    print(f'{out}: Lemmings 2: The Tribes with the in-game level editor V{VERSION} '
          f'for WHDLoad, {written} files written'
          + (f', {", ".join(kept)} kept' if kept else '')
          + f'; Levels holds {levels} level{"" if levels == 1 else "s"}.')


if __name__ == '__main__':
    main()
